### ISSUE TITLE
Modified Italian layout

### ISSUE THREAD

**Issue by morellik** [dessalines/thumb-key#100]
[ThumbKeyITAv2.kt.txt](https://github.com/dessalines/thumb-key/files/11101027/ThumbKeyITAv2.kt.txt)

I changed the position of the letters to improve the writing

**Comment by morellik** [comment]
[ThumbKeyITAv2.kt.txt](https://github.com/dessalines/thumb-key/files/11101212/ThumbKeyITAv2.kt.txt)

Applied another little modification

**Comment by dessalines** [comment]
@morellik Now that the file is already added, you can make changes to it directly here: https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyITv1.kt

Click the edit button.

**Comment by morellik** [comment]
Ok, thanks. I'll edit the file directly. Thank you
