### ISSUE TITLE
english thumb-key symbols-numbers

### ISSUE THREAD

**Issue by superloach** [dessalines/thumb-key#1008]
### Language

English

### Variant

english thumb-key symbols-numbers

### Kind of request

New Layout

### More details

Like english two-hands symbols-numbers, but one-handed.

I am so tempted to check the clown box.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Follow the instructions on the readme to add your own layout.
