### ISSUE TITLE
Left-hand mode

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#101]
Some people use their left hands more, so the keyboard could be mirrored through settings.

**Comment by dessalines** [comment]
I'd rather people add specific lefthanded layouts, rather than try to do logic that flips the keyboard.

**Comment by GrimPixel** [comment]
That means each keyboard will need a left-hand variant and occupy the selection menu.

**Comment by dessalines** [comment]
Yep. Layouts don't take up much code-space, so I'll add anyone's custom layouts they'd like me to add.
