### ISSUE TITLE
Drag and return for special characters

### ISSUE THREAD

**Issue by jm355** [dessalines/thumb-key#1019]
### Describe your suggested feature

Currently drag and return only works for alphabet characters, but it seems like some special characters could have out and back values too, for example '?' could have a drag/return value of '¿', likewise '!' and '¡'. If the drag and return logic is purely based on the uppercase version of the character that may not work though, I don't want '!' to become '¡' when I'm typing uppercase

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I'm not going to add a separate drag and return layer outside of the numeric / capitalized one. You'll have to either add these extra characters to your symbol keyboard, or use a composed layout.
