### ISSUE TITLE
Principles of layout creation

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#102]
I am confused on the English keyboard why “E” is at the lower-right corner instead of in the middle, as lower-right corner requires more efforts to reach for the thumb finger; the most frequent words like “be”, “on”, “of”, are not optimised.
There need be some principles on the layout creation, like using upper-left and lower-right key less, keys of the most frequent words are available through a single swipe without changing direction too many times, more diagonal and less vertical or horizontal, etc.

**Comment by dessalines** [comment]
Read the principles on the readme: https://github.com/dessalines/thumb-key#thumb-key-letter-positions

Thumb-key prioritizes two principles: alternate thumbs, lower keys, and taps are easiest. So this means most common vowels on the bottom right, most common consonants on the bottom left.

> lower-right corner requires more efforts to reach for the thumb finger; 

Thumbs come from the bottom corners of the keyboard, so the bottom ones are easiest to type, and require the least movement. Try to make the keyboard large, and try to reach very high up on the phone if you want to see that higher = more difficult.

> the most frequent words like “be”, “on”, “of”, are not optimised.

[B and F are not anywhere near the most common letters](https://en.m.wikipedia.org/wiki/Letter_frequency). Even still, every one of those is optimized by alternating thumbs.

If you want to make your own layout, go right ahead, and I'll merge it.

**Comment by GrimPixel** [comment]
Even with this explanation, there are still some uncertainties, like why S is at the upper-left corner, a harder-to-reach place while R is easier.
