### ISSUE TITLE
Enable Thumb-key option in its settings

### ISSUE THREAD

**Issue by Noitarud** [dessalines/thumb-key#1021]
### Describe your suggested feature

There is a button to switch to other enabled android keyboards in your keyboard interface, good idea, but other vendors do not have the option so I cannot switch back to thumbkey from theirs. I need a button in the tk settings to also bring up the same keyboard selector so I do not need to fiddle in android settings to get tk reenabled.

### Other details

Pressing to type in "Test out Thumb-key" brings up wrong keyboard.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Swipe down on the emoji key.

**Comment by Noitarud** [comment]
the keyboard is in the disabled state, it won't work, I need access to the list from your settings (image) — I bring up your settings using icon on home screen but cannot do it here.
![Screenshot_20241205-224626](https://github.com/user-attachments/assets/9da891c7-6c85-43e5-9540-fad2a3eb8e66)

**Comment by dessalines** [comment]
When you install thumb-key, it takes you through the process of enabling it.

**Comment by Noitarud** [comment]
… and, then you can change to another vendor's keyboard by a down swipe on the face button. But I then try going to settings of tk from the home screen but the "process of enabling it" again is withheld in the settings.

i did find an alternative solution, enabling android's Talkback keyboard also enables the keyboard button on the task bar (see image above) which gives the needed function (but other users will need to make that bar show - I think it gave the option to show when I plugged in a mouse via OTG cable).
