### ISSUE TITLE
[CRITICAL] Unable to unlock screen after activating non-Latin keyboard

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#103]
There is no way to unlock the screen with a non-Latin keyboard. Switching keyboard layout needs to be done on the keyboard interface.

**Comment by dessalines** [comment]
What does a keyboard have to do with unlocking your screen? You're saying you have your phone password locked with characters that aren't on your given keyboard?

And you should still be able to switch your IME by swiping down from the top.

**Comment by GrimPixel** [comment]
No. That version of Android doesn't support so.
