### ISSUE TITLE
The navigation bar color does not change with the keyboard one

### ISSUE THREAD

**Issue by GaucovyAero** [dessalines/thumb-key#1032]
### Steps to reproduce

Theme: Dynamic

### Expected behavior

The navigation bar color should get blueish just like the keyboard.

### Actual behavior

The navigation bar stays black while the keyboard background goes blue

### version of the program

3.4.1

### Android version

crDroid 10.7 (Android 14)

### Device

Xiaomi Poco F3 8/256

### Other details

![ResizedImage_2024-08-29_21-27-19_2423](https://github.com/user-attachments/assets/40a9ddd1-f19d-4fcf-893c-57f0e9369ba3)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
We can't control the bottom nav color.

**Comment by GaucovyAero** [comment]
simple-keyboard on github does have an option like this and it works

https://github.com/rkkr/simple-keyboard

![Screenshot_20240830-152825_Simple Keyboard](https://github.com/user-attachments/assets/3e2089a0-4c16-4d11-8df3-1db80383ebe7)

![Screenshot_20240830-152908_DuckDuckGo](https://github.com/user-attachments/assets/48478d5e-517e-43b4-a542-b9526dde4d2d)

**Comment by GaucovyAero** [comment]
if you are not going to make this option available, at least make an option to make the keyboard background black

**Comment by dessalines** [comment]
I have no idea how to do this. If you want it, then add it.
