### ISSUE TITLE
Spanish Thumb-Key Symbols Layout

### ISSUE THREAD

**Issue by DiegoLpVn** [dessalines/thumb-key#1033]
### Language

Spanish

### Variant

Thumb-Key Symbols

### Kind of request

New Layout

### More details

Hi, I've downloaded the project and made changes to add a "Spanish Thumb-Key Symbols" layout.
I also tried to stick as loyal as possible to the current Spanish Thumb-Key layout, just added  the "ª" symbol and moved parenthesis to keep every letter in the same place.

![imagen](https://github.com/user-attachments/assets/66b56016-8157-41e7-90dd-700051562ab0)

I have the changes locally but I don't know how to create a remote branch or if I need permissions for it as it's the first time I try to contribute to a project.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Look up a video on how to create a github pull request.
