### ISSUE TITLE
Slide gesture doesn't move text cursor in Element message textbox when "Text formatting" is enabled

### ISSUE THREAD

**Issue by ymuspd** [dessalines/thumb-key#1042]
### Steps to reproduce

1. Install Element https://f-droid.org/en/packages/im.vector.app/ and login
2. Go to Element in-app settings -> Labs -> enable the "Enable rich text editor" toggle
3. Find someone to chat with, or create a new empty private room if you have no contact
4. Tap on the plus sign button at the bottom-left, and enable "Text formatting"
5. Tap on the message edit textbox, Thumb-Key should show up
6. Type some characters
7. Try to swipe left/right on space bar to move the text cursor

### Expected behavior

Cursor should follow the finger's movement to move left and right, like in other applications.

### Actual behavior

Cursor doesn't move at all.

### version of the program

3.4.5

### Android version

Android 12

### Device

Mi 10T lite

### Other details

If I remember it correctly, Gboard used to have a similar issue with Element and fixed in later version.

Currently Thumb-Key seems to be the only keyboard application I've tried that doesn't move cursor in Element when text formatting is enabled (Floris, GBoard, fcitx5 all works).

Swiping on backspace still works though.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Element bug, not thumbkey. Open up an issue over there.

**Comment by ymuspd** [comment]
https://github.com/element-hq/element-android/issues/8898
