### ISSUE TITLE
Tapping on the backdrop should move the keyboard in the corresponding direction

### ISSUE THREAD

**Issue by iliazeus** [dessalines/thumb-key#1055]
### Describe your suggested feature

When I switch hands, especially from right to left, the "move keyboard" action becomes too hard to reach. Also, having to cycle through all keyboard positions is annoying.

I propose that tapping on the backdrop should move the keyboard in the corresponding directioni That is, tapping to the left of the keyboard should move it one position to the left (from right to center, from center to left), and vice versa.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I'm not going to add this, as backdrops are optional, and there's already a fast shortcut for moving the keyboard position. If you want to add this tho, I'll re-open and assign it to you.
