### ISSUE TITLE
Add a way to disable the voice input button

### ISSUE THREAD

**Issue by iliazeus** [dessalines/thumb-key#1056]
### Describe your suggested feature

The "voice input" action is a thing I rarely use, but very often mistakenly trigger, since I use the "switch posiion" and "switch language" actions a lot. It is also very annoying, since it closes the keyboard completely to open the voice input panel.

Because of all that, it would be nice to have a way to just disable it altogether.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I'm probably not going to add settings to disable different feature keys, but if someone wants to work on this, I'll re-open and assign it to them.
