### ISSUE TITLE
Thumb-key does not invoke FUTO Voice-Input or Transcribro after a reboot or first install without first having started their respective app on GrapheneOS

### ISSUE THREAD

**Issue by Zakadius123** [dessalines/thumb-key#1068]
### Steps to reproduce

1. Reboot the phone.
2. Select any text input box with Thumb-key.
3. Attempt to use Speech-to-Text.

### Expected behavior

When trying to use Speech-to-text, Thumb-key starts and switches to the preferred STT app after a reboot or first installation.

### Actual behavior

Before Speech-to-text can be used, the user has to first open the respective app.

### version of the program

3.4.8

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 6

### Other details

I've tried a few other keyboards like the default AOSP keyboard and pressing the microphone icon will open both FUTO VI and Transcribro after a reboot. 

I haven't been able to reproduce on my Galaxy Tab S6 Lite and Samsung Galaxy A8 running the default Samsung Android OS. 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You'll need to lock either of those apps so that they're not closed in the background.

**Comment by vcavallo** [comment]
what does that mean? i have the same issue, same os. voice key does nothing for me, while it does work when i switch to the futo keyboard itself. 

Edit: Disregard, I'm a dummy. I didn't realize there was a separate Futo voice app. I only had the Futo keyboard installed. Everything is fine now after installing voice app. I wrote this addendum from voice through thumb key yay
