### ISSUE TITLE
Automatically add spaces in Latin Toki Pona layout

### ISSUE THREAD

**Issue by adiee5** [dessalines/thumb-key#1071]
### Language

Toki Pona

### Variant

Latin (*not* sitelen emoji one)

### Kind of request

Changes on an existing layout

### More details

Currently, user has to manually press space after every keystroke. But since most of keys produce whole words, It would make sense to make those keys automatically place spaces after the words. That would significantly improve typing speed and convenience.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Good point, I'll do this shortly.

**Comment by adiee5** [comment]
nice
