### ISSUE TITLE
Add carron to English compose

### ISSUE THREAD

**Issue by adiee5** [dessalines/thumb-key#1073]
### Language

English

### Variant

thumb-key compose

### Kind of request

Changes on an existing layout

### More details

It'd be really nice if this keyboard layout also had a [caron](https://en.wikipedia.org/wiki/Caron) diacritic. I find it useful.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You'll have to either ping the person who made that layout, or add it yourself, because I don't maintain the composed layouts.

**Comment by adiee5** [comment]
Oh, ok, i may do that.

**Comment by adiee5** [comment]
@mpice-mn you seem to have created this, where do you recommend me to add a new compose key?

**Comment by mpice-mn** [comment]
@adiee5 I can add it - I already have another small change to that layout in my local version of the app that I still want to make a PR for.
I'd probably put it on the top-right swipe of the N.

**Comment by adiee5** [comment]
Ok, I can wait then

**Comment by adiee5** [comment]
@mpice-mn i don't see any changes in your forked public repo, so i guess you haven't pushed that yet.
