### ISSUE TITLE
more granular layout switcher

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#1077]
### Describe your suggested feature

I suggest a new, more granular approach for the layout switcher: this could be turned on in the settings. 

as long as the user has at most 3 layouts selected, swiping on the layout switcher would do the following:
when swiped and not yet released, the top three keys would be replaced with your selected layouts. then, releasing on top of the layout key would switch to it.

for example:
selected layouts: english, slovak, russian
the top three keys become this when swiping (re-renders) and when you let go on what is normally o, it will always select russian, on top of r, it will always select slovak and on top of s, it will always select english.

### Other details

this way, it's way more predictable what layout you're going to switch to, and eliminates the need of having to remember in what order are the layouts defined and thus cycled.
this is especially useful if the user has memorised multiple layouts, and uses 'hide letters' - waiting for the android popup to tell you which layout you're using in a major slowdown imo.

i am open to different ideas how this could be implemented as well, just let it be a deterministic layout switcher, not a cycler.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
That sounds really complicated, and the layout switcher is already really fast. 

I probably won't work on this, but I'll re-open and assign it to anyone who wants to do this, as long as it adds a setting that its default off.
