### ISSUE TITLE
Add a breve diacritic to compose layouts

### ISSUE THREAD

**Issue by slashdevslashurandom** [dessalines/thumb-key#1087]
### Language

English (and other Latin-based languages)

### Variant

Compose

### Kind of request

Changes on an existing layout

### More details

This feature requests suggests that the breve diacritic (◌̆) be added to "Compose" layouts for Latin-based scripts.

It can be added to the letters `AaEeIiOoUu` to represent short vowels in transcriptions of Latin and Greek. Esperanto uses `Uu` with a breve for a "w"-like semivowel.

In Turkic languages, it can be added to `Gg`.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by adiee5** [comment]
*english thumbkey compose* recently had breve added, check it out
