### ISSUE TITLE
Make uppercase and lowercase letters the same size

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#109]
https://stackoverflow.com/questions/75891662/android-is-there-a-fixed-size-font-ie-force-same-height-and-width-for-uppercas

Might have to do a sizing based on the mode unfortunately.

**Comment by WadeWT** [comment]
Would it be possible to use small caps?  [https://stackoverflow.com/questions/15963396/small-caps-on-textviews-edittexts-and-buttons-in-android](url)

**Comment by dessalines** [comment]
Hadn't thought of that, Its a possibility, thx!
