### ISSUE TITLE
Enter key makes "Send" action when it's not supposed to

### ISSUE THREAD

**Issue by adiee5** [dessalines/thumb-key#1105]
### Steps to reproduce

1. Open discord
2. type a message
3. press enter

### Expected behavior

new line is created in the message (that's what all other keyboard software do at least)

### Actual behavior

Message gets sent

### version of the program

3.4.14

### Android version

Android 13

### Device

Samsung Galaxy S20

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You didn't search for issues related to this.

**Comment by adiee5** [comment]
I'm pretty sure I couldn't find anything. Could you provide an issue ID?

**Comment by adiee5** [comment]
after some research i could find it. It's interesting that most apps do find a way to find it, even though discord apparently doesn't set API correctly. However, i think you should mention this stuff somewhere in an FAQ or other places, so that people can know, that you know there is this issue and especially that one can force a new line by holding the enter key.
