### ISSUE TITLE
auto-apostophe for contractions, possesives

### ISSUE THREAD

**Issue by mgroves** [dessalines/thumb-key#1127]
### Steps to reproduce

Type a contraction like "dont" or "wont" or "doesnt", etc.

### Expected behavior

Word should automatically turn it into "don't". This should also be the case for "im", "doesnt", etc, and maybe even words like "Steves" if possible.

If this is an existing feature, I haven't figured out how to turn it on, but I admit that I'm relatively new to thumb-key (having used Messagease for years)

### Actual behavior

Typing "dont" ends up with literally "dont"

### version of the program

3.4.15

### Android version

android 14

### Device

Google pixel 6a

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
This is too error-prone to add IMO. We have a few keyboard settings dealing with autocapitalizing, but there's no real way to find english possesives without a dictionary. 

Correcting `nt` isn't going to work for any english words that end in nt, like lint, mint, meant, etc. 

This is why the apostrophe is on the main english keyboards anyway.
