### ISSUE TITLE
Add interpunct and ellipsis to french layout

### ISSUE THREAD

**Issue by Raghnarok** [dessalines/thumb-key#1128]
### Language

French

### Variant

MessagEase

### Kind of request

Changes on an existing layout

### More details

Would it be possible to add · and … to the MessagEase (or the ThumbKey) keyboard ? I use it almost everyday and I feel always blocked in my messages by not having it.
It could be put on free space or maybe better on drag-on-return on the . key for the … and on the , for the ·.

Thank you for the job.
I can maybe help if needed.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't maintain the french layouts, so you'll have to ping whoever created them, or add it yourself.

**Comment by Raghnarok** [comment]
> I don't maintain the french layouts, so you'll have to ping whoever created them, or add it yourself.

I think I can add them.
I’m ok with code edition but I don’t know how I can test my modifications, could you explain it to me?

**Comment by dessalines** [comment]
You'd need to use https://developer.android.com/studio to deploy it either to your device directly, or use one of the images.

**Comment by Raghnarok** [comment]
MMmmhhh, this seems so complicated to build an android app, I’d need to install a lot of shitty Google stuff or I don’t understand it all…

**Comment by Raghnarok** [comment]
MMmmhhh, this seems so complicated to build an android app, I’d need to install a lot of shitty Google stuff or I don’t understand it all…
I’m pretty certain that the changes on FRMessagEase.kt (186-198) are :
                KeyItemC(
                    center = KeyC("s", size = LARGE),
                    topLeft =
                        KeyC(
                            CommitText("f"),
                        ),
                    top = KeyC("&", color = MUTED),
                    topRight = KeyC("°", color = MUTED),
                    left = KeyC("#", color = MUTED),
                    right = KeyC(">", color = MUTED),
                    bottomLeft = KeyC(";", color = MUTED),
                    bottom = KeyC("\u0308", displayText = "¨", color = MUTED),
                    bottomRight = KeyC("…", color = MUTED),
                ),
And on lines 48-57 : 
                KeyItemC(
                    center = KeyC("i", size = LARGE),
                    left = KeyC("?", color = MUTED),
                    bottomLeft =
                        KeyC(
                            CommitText("x"),
                        ),
                    topRight = KeyC("·", color = MUTED),
                    bottom = KeyC("=", color = MUTED),
                    bottomRight = KeyC("€", color = MUTED),
                ),

Maybe @soupirs, @glm4610 or @gitterrost4 can help me on this?

**Comment by dessalines** [comment]
Seems you're on your own adding these. I'd follow the instructions in contributing.md if you'd like to create your own layout. You could copy-paste one of the existing french ones as a template.

**Comment by gitterrost4** [comment]
I would volunteer to provide some support to @Raghnarok but I wouldn't want to spam this issue. I haven't found a github feature that allows me to contact you outside this issue though. I am reachable on discord under this username. Maybe I can help you there?

**Comment by Raghnarok** [comment]
> I would volunteer to provide some support to @Raghnarok but I wouldn't want to spam this issue. I haven't found a github feature that allows me to contact you outside this issue though. I am reachable on discord under this username. Maybe I can help you there?

Meh, I had a Discord account but seems it’s not the case…
I also don’t want to spam here, could you contact me on raghnarok@vulgarisons.info @gitterrost4 ?

Thank you!
