### ISSUE TITLE
 Hindi Layout

### ISSUE THREAD

**Issue by NripPrajapat** [dessalines/thumb-key#1130]
### Language

Hindi

### Kind of request

New Layout

### More details

It is used by more than half of India.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't speak hindi, so you'll need to add this yourself. Follow the instructions [here](https://github.com/dessalines/thumb-key/blob/main/CONTRIBUTING.md).

**Comment by NripPrajapat** [comment]
I dont know nothing about coding.

**Comment by NripPrajapat** [comment]
[HI.txt](https://github.com/user-attachments/files/17574534/HI.txt)
 Some important characters still need to he added. I don't know how to, show me how. Thanks.

**Comment by dessalines** [comment]
I don't know where you need them, or where they should go. It'd really be helpful if you could find someone who speaks hindi in the [thumb-key matrix chat](https://matrix.to/#/!lQadiyhvxXsBmqqEEr:matrix.org?via=matrix.org) that can help you.

**Comment by NripPrajapat** [comment]
I guess I found a way, so I am working on it, I'll send that after some time.

**Comment by NripPrajapat** [comment]
[Hi.txt](https://github.com/user-attachments/files/17575893/Hi.txt)


This is final draft, I guessed that just adding 'TopLeft' and stuff adds the key. So I tried and you tell me, if it will work or not.

**Comment by NripPrajapat** [comment]
![ResizedImage_2024-10-30_21-46-49_1](https://github.com/user-attachments/assets/0f91fc0a-a4a0-48ce-a925-97b0154703df)
!

This is the blueprint, I tried to add the BOXED letters.

**Comment by NripPrajapat** [comment]
I wanted to add an extensive keyboard, where could I apply for it?

**Comment by dessalines** [comment]
I don't know what that means.

**Comment by NripPrajapat** [comment]
I wanted to know, if any one wants to directly apply the layout for submission, is there any option or way?

**Comment by NripPrajapat** [comment]
if I one could simply wanted to test is out and then apply, is there any option?

**Comment by dessalines** [comment]
Install android studio if you want to test them out.

**Comment by NripPrajapat** [comment]
Is there any way to directly submit or I'll have to add it here, upload file and then you'll add that to the app or commit?

**Comment by dessalines** [comment]
If you don't want to test them yourself, then you'll have to keep uploading them as files in separate issues.

**Comment by NripPrajapat** [comment]
https://github.com/dessalines/thumb-key/issues/1132

Why don't you address this issue?
