### ISSUE TITLE
Vietnamese thumb key mark being broken

### ISSUE THREAD

**Issue by mieyuu** [dessalines/thumb-key#1140]
### Steps to reproduce

1. change into vietnamese keyboard
2. type

### Expected behavior

For example in Vietnamese when typing you have "ả" "ạ" 

### Actual behavior

but in thumb key it shows up like "å","æ"

### version of the program

4.0.2

### Android version

Android 14

### Device

OPPO Reno8 T 5G

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I didn't create that keyboard so I don't know what changes should be made. Go to that keyboard then click the edit button to make changes.
