### ISSUE TITLE
New Vlider RU/EN t9 layout

### ISSUE THREAD

**Issue by TonySmol** [dessalines/thumb-key#1143]
### Describe your suggested feature

Hello everyone. I'm new here, and I’m not familiar with the rules yet. Also, my English isn't perfect, so please forgive any mistakes. I'd like to share a design for a new keyboard layout based on central sliding gestures.

Here's some context: For a long time, I've been searching for a comfortable phone keyboard. A while back, I discovered MessagEasy, but I couldn’t use it due to the large number of characters per key. Later, I stumbled upon Hlider Keyboard, which was amazing— I learned how to use it within an evening and now can't live without it. However, it’s no longer being updated and isn’t open-source. It has more keys, but the crucial part is the letter placement: they're centered with two on either side. This works great, but it doesn’t feel natural. Personally, I think sliding gestures should be more intuitive, moving either up or down.

I attempted to create a design based on the frequency of Russian and English letters. Unfortunately, I won't be able to implement this for Thumb Key myself, so I humbly ask for help. Maybe others will find it useful too. I used T9 from another app as a starting point and created this layout based on that foundation.
![thumb 1](https://github.com/user-attachments/assets/800d9963-e6ab-474a-916b-edfb63635874)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
No one is going to do this for you, so you'll need to follow the instructions to add it yourself. All you need is a text editor.

https://github.com/dessalines/thumb-key/blob/main/CONTRIBUTING.md#how-do-i-add-my-language-or-layout
