### ISSUE TITLE
Requesting a language (Arabic)

### ISSUE THREAD

**Issue by Ali8101** [dessalines/thumb-key#1145]
### Language

Arabic

### Variant

MessagEase

### Kind of request

New Layout

### More details

Can u import the Arabic language with the symbols & numbers from messagease?

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't speak Arabic so you'll need to add this yourself.

See here for instructions: https://github.com/dessalines/thumb-key/blob/main/CONTRIBUTING.md#how-do-i-add-my-language-or-layout
