### ISSUE TITLE
Technical & aesthetics ideas

### ISSUE THREAD

**Issue by Der-Meister-von-codes** [dessalines/thumb-key#115]
Add the ability to set custom key colors and background images of keyboards, as well as perhaps several options for key styles to choose from, such as retro/cyberpunk/whatever.  Of the functional improvements, I would like to see the removal by clamping the backspace by the type of the first 5 characters - 1 per second, the second 10 - 2 per second, and so on, moving the cursor to the space is not character-by-character, but depending on the length of the swipe, for example, 5 pixels per  symbol, as well as changing the icon with a capslock, for example, its highlighting or other selection, otherwise it will be very easy to get confused.  I'm not asking for this in the next release, but as an idea for aesthetic and technical improvements, please take note.  Thank you) 

UPD: while writing this text, I discovered a bug that if you select uppercase inside a word, it will be set as a capslock, please fix this as well.

**Comment by dessalines** [comment]
Please write these as specific issues.
