### ISSUE TITLE
Emojis need to press backspace twice to remove

### ISSUE THREAD

**Issue by pxeemo** [dessalines/thumb-key#1168]
### Steps to reproduce

1. Type a emoji
2. Press the backspace key

### Expected behavior

Emojis should remove completely when backspace is pressed

### Actual behavior

You'll see emojis become like this when you press backspace key: ���

### version of the program

4.0.6

### Android version

Android 14

### Device

POCO M3

### Other details

This commit #1162 changes the backspace behavior to remove only one unicode character, since emojis are two-width unicode character they won't be removed as normal

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by gitterrost4** [comment]
I will take a look at it and get it fixed asap

Dessalines ***@***.***> schrieb am Sa., 30. Nov. 2024, 19:43:

**Comment by gitterrost4** [comment]
I have it fixed. My bad. I didn't think about emoji. In later API-Versions this code could be simplified by using `deleteSurroundingTextInCodePoints`, but in the minimum required API, this is not yet present.

**Comment by KraXen72** [comment]
experiencing the same issue. hopefully a fix can be pushed soon. thanks!
