### ISSUE TITLE
make "swipe up on A for capital" more obvious in the UI itself

### ISSUE THREAD

**Issue by mc776** [dessalines/thumb-key#1177]
### Describe your suggested feature

After months of frustration trying to get circular drag to work (I guess it assumes a minimum swipe length of much more than I'm comfortable with) I looked it up on the Internet on my computer, found #320 as I had before, and *almost* gave up until I saw the link to #322 and checked the files.

I had never thought to swipe up on A because that symbol over the A just looks like it should type some weird international variant of "^" that I'd never use.

Could it be changed to say "ABC" (and its corresponding swipe-down "abc") instead?

### Other details

yes I know it's in the documentation, but some of us are immediately completely demoralized when we tap on the help function and are taken to a GitHub page *on our phone*...

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
It's the 2nd line of the user guide, I don't know how to make it more obvious.

I'd rather not use the three letter caps for aesthetic reasons.

**Comment by mruncreative** [comment]
It's pretty fucking obvious. Especially with the default layouts where you only have a few symbols on the screen. Like how many things are there to swipe on? It's a you issue.

**Comment by dessalines** [comment]
@mruncreative do not engage with people in a rude or disrespectful way, or I won't hesitate to ban you from this repo.

**Comment by mc776** [comment]
> It's the 2nd line of the user guide, on the front page of the app. I don't know how to make it more obvious.

> yes I know it's in the documentation, but some of us are immediately completely demoralized when we tap on the help function and are taken to a GitHub page on our phone...


> I'd rather not use the three letter caps for aesthetic reasons.

Please don't Steve Jobs this. It's an accessibility issue.

**Comment by dessalines** [comment]
When you open the app, you click user guide, and it auto-scrolls to that section.
