### ISSUE TITLE
Backspace won't work in Termux

### ISSUE THREAD

**Issue by pxeemo** [dessalines/thumb-key#1178]
### Steps to reproduce

1. Type some words
2. Press backspace to delete letters

### Expected behavior

Letters should be removed normally

### Actual behavior

Nothing happens after pressing backspace key

### version of the program

4.0.7

### Android version

Android 14

### Device

POCO M3

### Other details

I guess this was working fine on v4.0.6 with the new backspace implementation

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
@gitterrost4 the backspace hack is failing in more apps.

**Comment by gitterrost4** [comment]
Is this only in a specific app or in general on that device?

Anyway, I am fine (though a bit saddened because of google chat) with reverting it if it causes too much trouble.

**Comment by gitterrost4** [comment]
One thing I noticed in Florisboard is that they fall back on "emulating a hardware backspace" in certain cases. There seem to be two kinds of editors on android: Rich editors and raw editors. The latter seem to need the hardware key emulation. But I can understand if you don't want to go through another loop of fixes and yet more cases here.

**Comment by pxeemo** [comment]
As I mentioned earlier, it was working after removing the DEL event method in the previous version. 

I haven't tested other apps, but I suspect it may fail in apps with a null type keyboard mode. 

Perhaps you could consider adding DEL event sending when the thumb-key cannot retrieve text or something similar.

**Comment by dessalines** [comment]
Could anyone please open, create, or link the issue for the google chat app hijacking backspace? Because IMO this is an app-specific issue. Every keyboard should not have to build hacks for a few broken apps.

**Comment by gitterrost4** [comment]
To be fair, the [android developer reference](https://developer.android.com/reference/android/view/KeyEvent) discourages sending keyevents:

>As soft input methods can use multiple and inventive ways of inputting text, there is no guarantee that any key press on a soft keyboard will generate a key event: this is left to the IME's discretion, and ***in fact sending such events is discouraged***. You should never rely on receiving KeyEvents for any key on a soft input method. In particular, the default software keyboard will never send any key event to any application targetting Jelly Bean or later, and will only send events for some presses of the delete and return keys to applications targetting Ice Cream Sandwich or earlier. Be aware that other software input methods may never send key events regardless of the version. Consider using editor actions like [EditorInfo.IME_ACTION_DONE](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_ACTION_DONE) if you need specific interaction with the software keyboard, as it gives more visibility to the user as to how your application will react to key presses.

(This is written from the perspective of the receiving side of these events, but the discouragement still stands)

> Could anyone please open, create, or link the issue for the google chat app hijacking backspace?

I cannot find a public issue tracker for issues with google chat. Is there such a thing?

**Comment by dessalines** [comment]
I think that's for app development, *not IMEs*, which makes sense, only the IME should be sending key events. Really its google chat not following that guideline and hijacking these that's causing problems.

I found this: https://issuetracker.google.com/issues/new , you can filter by component and it will take you to that app. I don't think google chat exists anymore tho, its called google meet now? No idea.

**Comment by dessalines** [comment]
For now, I'm going to revert the backspace hack, bc it might be causing problems with a lot more apps than we know about. ppl can use an earlier version for now if they're having issues with broken apps like google chat, until they link issues and get them solved in those apps themselves.

**Comment by dessalines** [comment]
I tested the PR I just merged, and it does fix it for termux, so I guess I'll close this one, and re-open #1065
