### ISSUE TITLE
Polish layout

### ISSUE THREAD

**Issue by Zireael07** [dessalines/thumb-key#118]
I can't compile Java/Kotlin here, so here are some notes:
The most common vowels are A-I-E-O, all over 7%. U is by far the rarest at 2,5, so it could go somewhere less comfy such as the bottom middle. 
The most common consonants are N-R-Z-S-W-T-C-Y, so that's the basic grid taken care of (and I think we already went over 3x3 buttons?)

I'd prefer accented letters to be on the related letter, so ą would be a swipe down from A, and ę a swipe down from E, and Ó a swipe up from O (mnemonics <3). Ś, Ń, Ć would all be a swipe up from their basic letter, and Ł a swipe horizontally (either left or right) from L. Z has two "variants" so Ż would be a swipe up and Ź a swipe up right.

That's all I can think of - I can't think of where to stick the remaining letters.

Source for letter frequency: http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/polish-letter-frequencies/ but it roughly matches other source I saw too

**Comment by dessalines** [comment]
There's no need to compile the kotlin language file btw. Copy-paste it, replace the letters however you see fit, then attach it here, and I'll do the compiling / adding.

https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout
