### ISSUE TITLE
Flat number mode

### ISSUE THREAD

**Issue by mruncreative** [dessalines/thumb-key#1180]
### Describe your suggested feature

Flat number mode:
An option you can toggle on in the settings for all 3x3 grid keyboard layouts because it only affects the control keys.
If enabled the spacebar becomes two keys wide and on the left there is a key that has 1-9 on it
1 2 3
4 5 6
7 8 9
5 is the no swipe action.
To accomodate 0, enter and backspace is moved up one unit, space is all the way on the right and on the bottom left there is the numpad key and the insert-copy-etc-key which now has a 0 in the middle.

Reasoning: Switching between modes for commonly used letters is very cumbersome because often you have a mixed text like 1a 2b 3c a=1 and then you constantly have to readjust yourself because everything shifts.
The separate layers bring the awfulness of the desktop numpad to mobile.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I'm not interested in anything this complicated. You could add this custom number layout as a *language* if you like, and switch to it quickly.

**Comment by mruncreative** [comment]
Maybe not how I proposed it but you should think about a way to access the numbers without switching. As a daily user I have to say that a number layer feels impractical

**Comment by mruncreative** [comment]
Maybe you could make a mode, so that the 3x3 grid acts as numbers and the space as 0 if you hold down the key for longer.

**Comment by dessalines** [comment]
There's no guarantee of a 3x3 grid on any keyboards. I'm not going to work on this, you can tho.

**Comment by mruncreative** [comment]
Well think about what I said about the numbers having to be more accessible. Maybe you'll come up with something. Anyway, good app. Thanks man.

**Comment by dessalines** [comment]
No probs. There's also the circle swipe gestures, which can do numbers, if switching to a numeric layout is too time-consuming.
