### ISSUE TITLE
Proposed layout addition: Thumbkey German symnum layout

### ISSUE THREAD

**Issue by mruncreative** [dessalines/thumb-key#1181]
### Language

German

### Variant

Thumbkey German symnum layout

### Kind of request

New Layout

### More details

I figured out how I could free the topLeft top topRight of the upper row to make room for the digits.
So I made this fresh layout. It has access to the entire ascii set and all German characters. I really used up every slot.
Sorry for making so many proposals ☺

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by mruncreative** [comment]
[DEThumbkeySymnum.txt](https://github.com/user-attachments/files/18052973/DEThumbkeySymnum.txt)
Updated

**Comment by dessalines** [comment]
Thx, I'll add this shortly.

**Comment by mruncreative** [comment]
Thank you. I hope typed everything in correctly and don't have to get back on this.

**Comment by dessalines** [comment]
No probs. If you do need to make changes to it, then click the edit button on github.

**Comment by Ingegneus** [comment]
really good one! writing this very message with it. glad you kept the sch and ch buttons. it is definitely an improved version over the deutsch thumb-key symbols kb. i wanted to fix a few things there, but i think i might daily this one. what exactly is this ſ key for? you mentioned fraktur? whats that?

**Comment by mruncreative** [comment]
ſ looks funny in Antiqua but it's the long s in Fraktur. It's used in place of s for everything except ends of a syllable or word part. Fraktur is the traditional writing system of German that has been used until the end of the second world war and was then banned within various occupation zones and schools leading to its disappearance.

**Comment by mruncreative** [comment]
Dead keys don't seem to be a good idea because it seems they don't allow for lone `´^ which are used for various technical things.

I have another idea. What if we put some smart „“ in place of ¿¡ that makes „ but after a punctuation or unicode "letter" character it makes “ ? Is that possible with the current system?
Then you'd have full word processing capabilities.
