### ISSUE TITLE
Numbers on long Letter press

### ISSUE THREAD

**Issue by Antismatter** [dessalines/thumb-key#1184]
### Describe your suggested feature

Long-press on a main letter should insert the matching number from the Symbols pane.

> 

### Other details

This was a feature in Messagease which was quite handy. I have not seen it mentioned anywhere on here, hence this request.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by Antismatter** [comment]
Thanks for the answer, and sorry for the dupe.
To clarify, it is not that circle swipe doesn't work on my device. It's more that from the UX perspective, it is a world apart from a simple long-press.
Whirling and twirling my thumbs around, VS just resting on a letter.
I know it is a tiny operation. It would simply feel more comfortable that way. It's pretty much the only thing I could ask of Thumb-Key, the rest being pretty close to ideal.

**Comment by Toldry** [comment]
@Antismatter FYI with the new key modification feature, you can customize this your keyboard to do this.

https://github.com/dessalines/thumb-key?tab=readme-ov-file#example-4
