### ISSUE TITLE
Smart quotes for Thumbkey German symnum

### ISSUE THREAD

**Issue by mruncreative** [dessalines/thumb-key#1185]
### Language

German

### Variant

Thumbkey German symnum

### Kind of request

Changes on an existing layout

### More details

I have another idea. ¡¿ aren't used in German or languages of surrounding countries. What if we put some smart „“ in place of ¿¡ that makes „ but after a non-whitespace grapheme (including äöüß and other unicode graphemes) it makes “ ? **Is that possible with the current system?** If yes, could you please put it in in place of ¿¡ with the same behavior for both upper and lowercase? The English writer layouts have “ and ” but on separate keys. I don't really have a point of reference on how to do it.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You'll need to add those specific quotes on different keys, there's no smart guessing. I mean you're free to try coding something, but it'd probably be a complicated mess and overall a waste of time.

**Comment by mruncreative** [comment]
I think a smart quotes feature would be an improvement for most languages. You don't have to hardcode „“. With the exception of East Asian CJK languages that don't use spaces many languages could make use of this.
https://symbl.cc/en/collections/quotation-marks/

**Comment by mruncreative** [comment]
\S matches the non-whitespace character.
```
var str = "!"
var qstart = "„"
var qend = "“"
println( if(str.matches(Regex("\\S"))) qend else qstart )
```

**Comment by mruncreative** [comment]
But why not consider smart quotes?

**Comment by mruncreative** [comment]
I think this should work
```
= SmartQuotes("„", "“")

app/src/main/java/com/dessalines/thumbkey/utils/Types.kt

class SmartQuotes(
	val start: String,
	val end: String,
) : KeyAction()

app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt

import java.text.BreakIterator

when (action) {
	is KeyAction.SmartQuotes -> {
		if (ime.currentInputConnection.getTextBeforeCursor(1, 0).matches(Regex("\\S"))) action.end else action.start
	}
}
```

Stuff composed of multiple code points still have their parts matched by \S I believe, so fetching just 1 of those 16-bit units should be enough.

I don't know Kotlin and I don't have anything set up to Kotlin. Never wrote anything in it. Would you kindly test and fix this?
Logically something like this should work with not too much code.

**Comment by mruncreative** [comment]
Turns out there already is a way to make English quotes with one button. ¿¡ tuns " inti  “ and ' into ”. I think other languages deserve their own quotes and that the current system is not intuitive.

**Comment by dessalines** [comment]
I can't test this for you, you'll have to do a PR yourself.

**Comment by mruncreative** [comment]
Please. I'd have to figure out how to set all this up. It would be a huge pain while you can probably get it working in 10 minutes. Just do it once you got some spare time, okay?
