### ISSUE TITLE
Missing emojis?

### ISSUE THREAD

**Issue by sphh** [dessalines/thumb-key#1199]
### Steps to reproduce

1. Open the emoji keyboard.
2. Insert the :face_with_peeking_eye: (`face with peeking eye`) into a text field.

### Expected behavior

The :face_with_peeking_eye: emoji should be in the emoji keyboard.

### Actual behavior

The :face_with_peeking_eye: is not in the emoji keyboard

### version of the program

4.0.9

### Android version

Android 8.1

### Device

Unihertz Jelly Pro

### Other details

Maybe it is just me, that I cannot find it in thumb-key's emoji keyboard!

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
We don't control what emojis are shown, we use `androidx.emoji2:emoji2-emojipicker` . You'll have to open up an issue on that repo.
