### ISSUE TITLE
Emoji keys are very small

### ISSUE THREAD

**Issue by sphh** [dessalines/thumb-key#1200]
### Describe your suggested feature

On my tiny phone, there are 9 rows with 9 emojis each, making them very, very tiny:
![Screenshot_20241218-200953](https://github.com/user-attachments/assets/71c7e3a9-ea8c-4f80-96fa-4e34017d8496)

It would be great, if the number of emojis could be adjusted in the settings – as can be done with the size of common keys.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
This isn't something we control unfortunately, since we're only inflating android's emojipicker view. You'll have to open up an issue over there to make it more configurable.

**Comment by sphh** [comment]
Ah, that's the reason, why the emojis in the picker are somewhat blurred …

Sorry, but since I don't know, how thumb-key interacts with `emoji2-emojipicker`, I believe that I am not the right person to do so.
