### ISSUE TITLE
Allow character input from letter keyboard

### ISSUE THREAD

**Issue by OwenPiacsek** [dessalines/thumb-key#124]
The MessagEase app would let you input special charaters even when typing letters, which saved a lot of time. Is there any way this could be added to this app too?

**Comment by allaboutevesn1987a** [comment]
Oh it could,  particulary as an optional language layout but this issue is a duplicate of  #106

**Comment by dessalines** [comment]
Dupe of #106 . Symbols should go on the numeric keyboard or spacebar multitaps.

If someone wants to add their own custom layout with a lot of symbols on there, I'd add it tho.

**Comment by allaboutevesn1987a** [comment]
Sorry to be a pest, but isnt that what was provided in [the zip](https://github.com/dessalines/thumb-key/files/11109099/MessageEaseSymbolPassthrough.zip) of #106?

**Comment by dessalines** [comment]
I've added that now.
