### ISSUE TITLE
French layout improvement suggestion

### ISSUE THREAD

**Issue by breversa** [dessalines/thumb-key#125]
Hi!
Following @CastelJeremy 's work here: https://github.com/dessalines/thumb-key/issues/26#issuecomment-1492918045, I've tested this design and think I may be able to provide some improvements. :)

Here it is:
```
 "’  ü   ï
 L^  Uû  Iî
 kq  pù y  

    wjg   @
 Rv zNb dAâ
    xhf æ à

  m çc! oëé
*T- :S? ôEê
/=+ ,.; œ è
```
(Make sure you see this in a fixed-width font)

Following this order of frequency (`ESAITNRUL odcpmvqf bghjxyzw k`) and these guidelines from https://github.com/dessalines/thumb-key:

- First 9 letters by frequency are the 9 center key taps. The next 8 are swipes **to** the center. The next 8 are swipes **on** the center hub key. Z is last.
- Alternate thumbs for vowels and consonants (Vowels on right side of keyboard, consonants on left). This naturally results in fast digram speeds.
- Prioritize bottom, and right side of keyboard. So EAO should be on the right side, and bottom to top, while TNS is on the left side.

I made up this order of priority:
```
9 6 3
8 5 2
7 4 1
```

I then proceeded like this:
1. Lay out the 9 most frequent letters (`ESAITNRUL`), from bottom-to-top, right-to-left, vowels on the right
2. Lay out the next 8 most frequent letters (`odcpmvq`) and `y` as swipes **to** the center (I didn’t want to move `y` to step 3 and wanted to keep it as much to the right column as possible, although I could study moving it to the bottom-right of the center square, instead of the current `f`)
3. Lay out the next 8 most frequent letters (`fbghjxzw`) as swipes **from** the center
-- _This is where things get less and less objective_ --
4. Lay out the last letter (`k`)… where I could (it ended up in the`l` square, which is alphabetically close, and next to the `q` which sounds similar)
5. Keep the top and bottom position of the right square (`A`) for upper- and lower-case control
6. Lay out the accentuated letters in the same square as the non-accentuated letter, trying to keep as much consistency between `e`, `a`, `i`, `u`, `o` **and** mimicking the drawing logic (e.g. acute accent to the top-right, grave accent to the bottom-right, circumflexes and diaeresis as high as possible)
7. Lay out `ç` in the same square as `c`
8. Add `æ` and `œ` where in the same squares as `A` and `o`
9. Add the most common punctuation (`.,;:!?`) in the same square, trying to mimic the drawing logic (e.g. `,` and `;` at the bottom, `!` and `?` as high as possible
10. Add mathematical symbols (`+-/*=`)
11. Add extra symbols that I use frequently enough (`@^`) that I want them on the main layout (and not in the shifted one), where they made the most sense
12. Add `’` and `"` to a non-cluttered square (this should have been a higher priority but I overlooked it)

**Comment by breversa** [comment]
(I'll try and provide a https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyENv4.kt file for that suggestion)

**Comment by breversa** [comment]
In order to decrease the visual clutter, accentuated letters will be displayed in muted color (I haven't tested it yet though).

**Comment by CastelJeremy** [comment]
I agree with the new letter layout, but I think the letter `k` should stay in it's current position.

I'm also not sure about your points **9 through 12**.
In a previous [comment](https://github.com/dessalines/thumb-key/issues/26#issuecomment-1481670832), @dessalines said that we should avoid using symbols in the language keyboard and we should keep them in the numeric keyboard.

Although it is not formally written in the guidelines, I think it would help with the visual clutter if we follow this rule.

I'm not a fan of having to use the muted color for accent letters but since the português layout uses it, I guess it's not really a problem.

**Comment by breversa** [comment]
Thanks for your comments!

Indeed, I may have gone a bit overboard with punctuation, but I don't like having to switch between alphabetic/numeric keyboards.

In particular, if the mulitap punctuation marks could be displayed on the space bar, it would remove the need to have them on another key.
However, the (French) apostrophe *needs* to be on the alphabetic keyboard, as it has an orthographic value in many very common words.

**Comment by breversa** [comment]
Regarding 'k', I'm still hesitating:
- to follow the drawing logic, I would place it on a bottom, or bottom-right, or top-right, maybe top position, but in no way on a right, or any left position.
- since it's the least used letter in French, I would not look for it in a high-priority (= bottom, right) square, but in the least-priority (top, left) one. It feels more in line with the letter placement logic this way.

**Comment by breversa** [comment]
Muted colors for accents:
Since I managed to keep all accents on the same square as the "parent" letter, I feel there's no need to highlight them any further. Decreasing the visual clutter may be a higher priority in that case.

**Comment by GrimPixel** [comment]
Also, the word « Français » shouldn't be capitalised.

**Comment by CastelJeremy** [comment]
> However, the (French) apostrophe _needs_ to be on the alphabetic keyboard, as it has an orthographic value in many very common words.

_Wow!_ I didn't know there was a difference between the (French) apostrophe and the quotation mark.
I agree, it should stay on the alphabetic keyboard.

For 'k', we can follow the english layout and put 'z' in the bottom square, right position.
'w' would then be on the left position of the center hub and 'k' on the top-left.

What do you think ?

**Comment by breversa** [comment]
> /Wow!/ I didn't know there was a difference between the (French) apostrophe and the quotation mark. I agree, it should stay on the alphabetic keyboard.

Now that you speak of it, the double quote symbol """ is also incorrect in French. "<<" and ">>" (I'm currently typing from my smartphone so I don't have the proper symbols 😅) should be used instead.

> For 'k', we can follow the english layout and put 'z' in the bottom square, right position. 'w' would then be on the left position of the center hub and 'k' on the top-left.
>
> What do you think ?

'k' being the least frequent letter in French, it makes sense to *not* use the position of a more-frequent one.
I suggest (to French users) to give my suggestion a try for a few days/week (I will to since I haven't tried it myself!!) and provide feedback afterwards. 😇

Also, in French, some punction marks *require* a space before (some times after) them. How can we implement that?

Mandatory space before:
!?;:>>([{

Mandatory space after:
.,<<...)]}

**Comment by breversa** [comment]
Updated suggestion with `«` and `»`
```
«»’  ü   ï
 L^  Uû  Iî
 kq  pù y  

    wjg   @
 Rv zNb dAâ
    xhf æ à

  m çc! oëé
*T- :S? ôEê
/=+ ,.; œ è
```

**Comment by GrimPixel** [comment]
«»‹› are required also in other languages. If they are added, then “”„‘’‚ need to be added to other keyboards as well.

**Comment by CastelJeremy** [comment]
I'm willing to test your letter layout but i think mathematical symbols should stay on the numeric layout since you would have to switch to it to type numbers.

Regarding space before and after punctuation, i don't know how this can be implemented.
It might require a new feature request.

**Comment by breversa** [comment]
> I'm willing to test your letter layout but i think mathematical symbols should stay on the numeric layout since you would have to switch to it to type numbers.

The reason why I like mathematical symbols on the main keyboard is because I use them a lot for passwords (not that much to type calculations). :)

**Comment by dessalines** [comment]
Keep math symbols on the symbol keyboard. You shouldn't be manually typing passwords anyway, you should use a password manager that has its own keyboard or lets you copy it.

**Comment by breversa** [comment]
Of course that’s a best practice, but I routinely prepare smartphones for other users who are more likely to type passwords than use a password safe, and I’d rather raise awareness of Thumb-Key than force their behaviour.
