### ISSUE TITLE
Intuitive mapping

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#128]
I saw that layout in https://github.com/dessalines/thumb-key/issues/125. I think every layouts should be defined like this: a string variable containing such information, defined by codes like the one below.
```
┏━━━┳━━━┳━━━┓
┃   ┃   ┃   ┃
┃ s ┃ r ┃ o ┃
┃  w┃ g ┃u  ┃
┣━━━╋━━━╋━━━┫
┃   ┃jqb┃   ┃
┃ nm┃khp┃la ┃
┃   ┃vxy┃   ┃
┣━━━╋━━━╋━━━┫
┃  c┃ f'┃d  ┃
┃ t ┃ iz┃ e ┃
┃   ┃,.*┃   ┃
┗━━━┻━━━┻━━━┛
```
All codes below it are all the same in all layout files, where the original code of key definition will be replaced by the character index in that string. This will make creation of layouts much easier.
Or even more: layouts are all in one file; the name of the layout is the name of the variable.

**Comment by dessalines** [comment]
No, I don't want to move it to an untyped data structure. Copy pasting a kotlin file hasn't proved difficult for anyone else adding a keyboard.

**Comment by breversa** [comment]
What *could* be done though is a script to convert @GrimPixel 's format idea into @dessalines' Kotlin format. :)

**Comment by dessalines** [comment]
That would be much more difficult than copying a file, and I wouldn't do any work to support new changes I need to make to the typed kotlin file.

**Comment by breversa** [comment]
Indeed, the cost/benefit ratio may not warrant such a development. Just saying that it *could* be possible.

**Comment by GrimPixel** [comment]
What are the difficulties in doing so? If there is no key assigned to a position, it could be simply treated as a space.
