### ISSUE TITLE
Move caps lock to lower-left corner

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#129]
Caps lock is a functional key, just like backspace and enter/newline. It is currently the only such key taking up room in the 9x9 area.

**Comment by dessalines** [comment]
Torn on this, mainly because not all languages have caps lock, so it makes sense to keep it on the letter grid. I have it in the same place it was in messageease.

**Comment by GrimPixel** [comment]
Not all writing systems have different cases. All keyboards don't need to be the same. The space key can be three or two units in length.

**Comment by dessalines** [comment]
> Not all writing systems have different cases.

That's exactly what I just said, which is the main case for keeping it on the 9 letter keys.
