### ISSUE TITLE
Issues with caps

### ISSUE THREAD

**Issue by mizzunet** [dessalines/thumb-key#132]
Here's few scenarios capitalisation works improperly
1. After a dot and space, shift turns on itself, which is fine. But not when the dot was added from numeric area.

2. When keyboard opens by tapping a text field, shift is on irrespective of cursor is on beginning, middle or end of word. This shouldn't happen. 
2a. If the cursor is at beginning of a line, shift should on
2b. If the cursor is at after a dot and space (. ), shift should on
2b. In all other cases, shift should be off

3. While keyboard is displaying, moving cursor to,
3a. beginning of a line, shift should be on by itself
3b. after a dot and space, shift should be off
3c. any other position, shift should turn off if it was on

4. The QWERTY keyboard open as shift off on some text fields. Like in Termux, search in Settings app etc. But Thumbs key doesn't respect that as I mentioned in point (2).

If you're not getting the points, let me know, I will share a video recoding.
Thanks.

**Comment by marcdw1289** [comment]
Not sure if this should be a new issue or not but...
Thumbs is not really ideal for terminal but just noticed with 0.0.11 in Termux it shifts to uppercase after every letter is typed.
Normally I'd switch to a different keyboard so caught this by happenstance.

**Comment by dessalines** [comment]
What's the text field you're typing into?

**Comment by dessalines** [comment]
What terminal app, termux?

**Comment by dessalines** [comment]
That appears to be an issue with auto-capitalize, I recommend just turning that off for now.

**Comment by skorokithakis** [comment]
Should this ticket be split into multiple ones? I'm liking thumb-key a lot so far, but auto capitalization has been very hit and miss.

**Comment by skorokithakis** [comment]
Even as I write this, it doesn't capitalize the first word in this sentence. It did in this one, though.

**Comment by dessalines** [comment]
It depends on the text field. This probably should be split into multiple issues. I'm thinking of just canceling auto-capitalize altogether because of its complexities that I don't wanna spend time to support.

**Comment by skorokithakis** [comment]
Ah, that's a shame... Not having auto-capitalization would basically make the keyboard unusable for me.
