### ISSUE TITLE
List layout principles and approaches

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#133]
Looking at keyboard layout on PC, there is no silver bullet. They are based on different priorities. The guideline of the official one doesn't take bigrams in consideration, and the positions of keys are not based on the ease to reach the key, e.g. T placed at the lower-left corner instead of the centre. Actually, some people have longer thumbs, some people have shorter thumbs. The most comfortable key to reach can be either the lower-right or centre.

So I think, instead of having principles and approaches of what the official layout is like, there should be a list of principles. People can pick some of them and prioritise those aspects for their layouts. For the official one, it just needs to state which aspects are prioritised through which approaches.

**Comment by dessalines** [comment]
These are discussions better for https://lemmy.ml/c/thumbkey .
