### ISSUE TITLE
Danish Layout

### ISSUE THREAD

**Issue by Limfjorden** [dessalines/thumb-key#135]
This is more intented as a forum for discussing the implementation of a Danish layout.

I would like for there to be a Danish layout, and I will gladly help design it, since it is my native language.

**Comment by Limfjorden** [comment]
Here is my initial proposal. I've based it off the (in Danish), but made some small adjustments.
When designing, I had two principles:

1. Minimal changes from the english layout. Since many Danes use english words and abreviations while texting (wtf, omg, cool, nice, yes), I decided to only change what is absolutely neccessary, as well as add buttons for the three special Danish leters.
2. When changing the position of letters, exchange English letters with danish letters that are used roughly as frequently in Danish as the ones they are replacing were in English.

Initial proposal
![ThumbDK](https://user-images.githubusercontent.com/66277585/230765836-57bea707-4873-4425-bca9-2e41b3acca8a.png)

Danish letter frequency
[marts-1970-pdf.pdf](https://github.com/dessalines/thumb-key/files/11185151/marts-1970-pdf.pdf)

**Comment by dessalines** [comment]
Looks good! Once you copy the kotlin file and replace the letters, I can add it.

**Comment by Limfjorden** [comment]
One problem: There are three more letters in the Danish alphabet, so I won't be able to just switch letters. How do I go about adding extra buttons. Could I just copy from the finnish keyboard?

**Comment by Limfjorden** [comment]
I based it on the finnish keyboard and ended up with quite a different layout in the end. If you're open to translating the UI, I will make a translation of the strings in the app too.

**Comment by dessalines** [comment]
This is merged now, thanks! In the future, make sure your commit messages have `Fixes #NUMBER`
