### ISSUE TITLE
Somewhat related project: Unexpected Keyboard

### ISSUE THREAD

**Issue by denilsonsa** [dessalines/thumb-key#138]
There is another open-source keyboard with a similar user-interaction: https://github.com/Julow/Unexpected-Keyboard

This other project keeps the QWERTY layout, and adds swipes on every key. This allows quick typing of several symbols and special keys that aren't common on mobile keyboards. Both keyboards have some similarities, but also different focus/objectives.

Might be worth mentioning it on the README file. And probably they should mention your keyboard as well.

**Comment by dessalines** [comment]
Seems unecessary to use the readme to list all open-source keyboards. Who knows what other ones could be created in the future. F-droid or privacy-specific repos could list them all tho.
