### ISSUE TITLE
Configurable minimum swipe length

### ISSUE THREAD

**Issue by Zireael07** [dessalines/thumb-key#14]
I'm finding swipes have trouble registering with my left thumb. (My swipes are bad in general due to limited finger dexterity, they often go in the wrong direction so I often upped minimum swipe length in MessagEase which helped)

I suspect having this configurable will help alleviate the problem just as it did in MessagEase.

**Comment by dessalines** [comment]
Makes sense... I'll add this shortly.

**Comment by dessalines** [comment]
Trying to figure out a sane default took some trial and error, but from about 30-60, with a sweet spot of 40 seemed to be the best for my hands at least.
