### ISSUE TITLE
Spanish Layout

### ISSUE THREAD

**Issue by racunaATneuronet** [dessalines/thumb-key#142]
It would be cool if you add spanish layout. I did it with Multiling O here: https://github.com/racuna/multiling-o-esbr in particular the file messagease-esbr-nocur-right.json

But Multiling O and Messagease are abandoned.

Another thing. I found it more comfy to have non-char keys (settings, back, numeric, enter) in the left of the screen when typing with the right thumb. But it is just a thing of practice.

**Comment by Limfjorden** [comment]
You can do it easily yourself! See: https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout

**Comment by GrimPixel** [comment]
Hey, why don't we use JSON to define keyboards like this? I found the current solution easy to confuse people. I tried to create one and finally found myself lost. Even XKB is more intuitive than this.

**Comment by dessalines** [comment]
Because untyped data strucures are more difficult to deal with in code.

Why is copying a kotlin file and replacing letters difficult?

**Comment by GrimPixel** [comment]
I need to copy and paste the original code, move my cursor to the letter and edit it. I have to keep in mind where I am — the row and the column, then take care of the directionsIf I scroll the page, I can easily get lost. 
What is the benefit of keeping the current solution then?
