### ISSUE TITLE
Special keys for fast navigation inspired by Neo kbd layout

### ISSUE THREAD

**Issue by erik55** [dessalines/thumb-key#147]
Like many others here I also come from multiling-o-keyboard. Your (open source!) keyboard is great (I didn't know or use the keyboard app you've based your work on). 

I co-developed the ergonomic [Neo touchtyping keyboard layout](https://neo-layout.org/) (similar to dvorak but modern and advanced).

From your keyboard I am missing some special keys for way faster navigation using only the keyboard (not having to hit -- and miss -- small form fields with your fat fingers) that Neo has (called Level 4 in Neo), and which its users love and I also used a lot with the multiling-o neo adaption. 

* del key: could be slide to the right on the backspace key, as it deletes to the right. This is very important! 
* cursor up and cursor down: why not on the space bar sliding up and down, that would be consistent. 
* tab key: could be on the 1 of the numpad sliding to the upper left corner. Used for rapidly filling forms and on the terminal of course. 
* space key that only produces spaces: could be the space on the numpad. 
* undo key: sliding up on the backspace key (very useful)
* esc key: could be on the 3 of the numpad sliding to the upper right corner
* ctrl key: could be on the 9 of the numpad sliding to the lower right corner
* nbsp and nnbsp: could be on the numpad space up and down (used for things that should stay toghether like: Mr. President or 3.4 kW/h) 

Btw: I've started to use your keyboard only 2 hours ago and am noticing already satisfying speed improvements! I've written this whole text with your keyboard (except for the non-breaking spaces). Thanks for your work!

**Comment by dessalines** [comment]
How would you feel about designing a *function* keyboard, that lives alongside the numeric keyboard(and the future emoji one)? Seems like there are enough special functions to fill a grid.

**Comment by dessalines** [comment]
del forward and the space up /down navigation I could add tho, apart from that.

**Comment by dessalines** [comment]
Either that, or a specialized programmers keyboard layout.

**Comment by erik55** [comment]
And what about the space key on the numpad? Can’t this be a normal space? Why? Is there a use case for having it also create punctuation there?

**Comment by erik55** [comment]
Could you please release soon a version with the del and the up and down cursors?

**Comment by dessalines** [comment]
These all need to be written up as separate issues, but yes, there should be a way to disable the spacebar multitap functionality. Open up an issue for that if you would.

**Comment by erik55** [comment]
Ok, I'll do that. You can close this one as soon as you've implemented cursor up/down an del key.

**Comment by domportera** [comment]
oh hey i did the cursor up/down and the del key in my latest PR with a programmer keyboard layout... small world!

**Comment by DeflateAwning** [comment]
I'll second the request for the cursor navigation tool(s)

**Comment by dessalines** [comment]
The cursor navigation and forward del is added now. If there are other specific requests, open up new issues.
