### ISSUE TITLE
thoughts / suggestions

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#152]
this is a great software keyboard - i really like it and look forward to getting used to it. here are some suggestions for the app, implement which ones you want.
## stuff i'm hopeful to see
- emoji key & emoji picker - just a catalog of emoji, sorted into categories like other keyboards have
    - search bar for specific emoji - there are now so many emoji's that you sometimes don't know the name, it's good to be able to search for them.
    - recently used emojis (like in gboard/other keyboards)
- an optional punctuation key, with these options: . in the middle, and other punctuation like !?, around it
    - or atleast, a way to type ? and ! without going to symbol layer more conveniently - tapping space like 4 times works but its time consuming.
- slovak layout, #151  
- more consistency for letter placement across different layouts - i type in 2-3 languages (english, german & slovak), and for example, in german layout, the middle key's left is different than english's - i'd love if layouts were as consistent as possible, with extra letters added into empty space, even at at the cost of some unoptimal placements (these "consistent" layouts could be a separate option from the primary ones)
- scrolling in language list, it currently uses a pop-up, which is a bit wacky, but i understand this is alpha software.
- cursor navigation by dragging on the spacebar - currently it moves one character/swipe, but i think it would be better if it would move depending on how much you move your finger on the space key (even allowing to swipe outside of the key) - more direct control
- swiping right on backspace could delete the whole word to the right, and (for example) swiping up could delete 1 character
- proper center layout, where the 3-wide matrix is in the center of the screen - currently i had to select right layout and set the size to 82 to achieve this.
- gboard-like sounds, the current ones are quite wierd
- text shortcuts - you could set up some longer text to be suggested/replaced after typing a shortcut. it could be useful when typing 1 thing a lot, for example your e-mail.
 ## would be cool
- word prediction based on current word - i understand this is probably hard to add & would go against the keyboard's philosophy a bit, but i am often not quite sure of a spelling of a specific word, and the 3 suggestions at the top show me how it's spelled.
- emoji suggestions - basically the same thing as emoji search, however in real time - if the current word represents/matches an emoji's name (for example "pensive", "joy", "sobbing" etc) it would suggest an emoji in a suggestion bar, which would replace the current word after being clicked.

**Comment by dessalines** [comment]
Open these as individual issues.
