### ISSUE TITLE
Add comma in place of star (*) on the letter keyboard

### ISSUE THREAD

**Issue by Limfjorden** [dessalines/thumb-key#154]
On the numeric keyboard (and also the main letter keyboard), I think the star (*) should be switched with comma (,). In my experience comma is much more useful than the star so it should be available without switching to the numeric keyboard. The positions on the numeric keyboard should then be switched so they are not in two different places.

**Comment by KraXen72** [comment]
how about both a comma and a star? star is also useful. but i agree a comma is more useful

**Comment by dessalines** [comment]
Do you know about the comma spacebar multitap?

**Comment by KraXen72** [comment]
yes, however this then prevents me from entering consecutive spaces, which i used to do quite often, and also consecutive commas (they can be entered through symlayer but still)

**Comment by dessalines** [comment]
That seems like a really odd use case, that's better suited for the symbols keyboard. Why do you need to type `,,` , or `  `

#163 is a better solution for that problem.

I think clause-enders should mostly be on the spacebar, and symbols keyboard. I *really* want to keep clutter off the main keyboard.

**Comment by DeflateAwning** [comment]
That's weird that double-tapping the spacebar inserts a comma. Normally it inserts a period in other layouts. Seems like a hidden secret as well. The normal install path doesn't mencion the double spacebar trick at all

**Comment by dessalines** [comment]
It's in the user guide, shown right after you install and set up thumbkey, as well as on the readme.

**Comment by dessalines** [comment]
I'm editing the programmers keyboard to remove the multitaps... seems undesirable there.

**Comment by domportera** [comment]
yeah I was wondering about that too, i say go for it. I can see a possibility for the multi-taps to be really convenient if they don't add a space afterwards, but then space-based-tabbers would just get frustrated so fuck it

**Comment by dessalines** [comment]
As comments are "clause-enders", its on the spacebar multitaps, and on the symbols keyboard.
