### ISSUE TITLE
Full-width layout

### ISSUE THREAD

**Issue by SamuXzX** [dessalines/thumb-key#155]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I start by say "Thank you!": finally someone got back the idea of not using a QWERTY layout on mobile.

** Describe the feature request below **
Right now the keyboard only takes a portion of the horizontal width of the screen:
![senza titolo-f000256](https://user-images.githubusercontent.com/30182251/232306984-d592ebd4-ddcd-4d3f-8451-8e319bc7bdb3.png)

I'm thinking about how you could better manage the space to make typing easier keeping this style of tap+slide writing. I think we could add an option to the "Position" section to fill all the horizontal space with the keyboard.

I have two proposals:

1) Moving the right column to the side and extending the other keys to fill all the space: this will make typing easier (therefore faster) because of the bigger buttons, and it means it would be easier to type without looking at the keyboard.
![proposal1](https://user-images.githubusercontent.com/30182251/232304898-799c6a83-d372-4cc2-a359-7aadfaa7e1f9.png)

In this way it could be needed to relocate the right-to-left swipes of the leftmost keys, but I see lots of other places where they could be placed in any language layout. But the buttons are bigger! So the action could be performed anyway starting from the top or the center of such keys.

2) Moving the right column to the side, placing the spacebar in a left column and enlarge they actual keys to be a bigger square. Again, this would make typing easier and faster. We may need to relocate the top-to-bottom swipes of the bottom keys, but I think it would be a great trade. Again: the buttons are bigger, so the swipe could be performed anyway inside the keys themselves.
![proposal2](https://user-images.githubusercontent.com/30182251/232305744-cdf8f209-bad0-467e-bb9c-261bb18eae4d.png)

I prefer this second proposal and I think we could mix this with another change: removing the "Settings" button from the keyboard, because ideally it should never be needed from the moment the user chooses a final layout:
![proposal2 1](https://user-images.githubusercontent.com/30182251/232305870-c928768d-1ed0-4489-8c0e-a38455467359.png)
Or we could simply use that position for another function.

The last one is the layout I would prefer, but it could clash with the sliding pointer function of the spacebar (#59), unless we think it could work anyway while being used vertically.

**Comment by dessalines** [comment]
You can already do a full width layout currently, by simply increasing the key size in the settings. If your key grid size overflows your screen size, the columns on the right should be minimized.

Your proposals above all require non-square, and relative key sizing. Outside of the complication of having to hard-code these specific relative sizes, I doubt doing so would actually increase tapping speed in any way. Having keyboards fill screen widths doesn't seem like a parameter that would be beneficial in any way to tapping speed.

**Comment by SamuXzX** [comment]
I understand. My point was more about not wasting space than actually fill the horizontal width, but now that you showed to me that I can make all the keys bigger it is a little better.

Maybe I can still propose one of the layouts to have the letters centered (which would make it more comfortable because they are the most used keys) and to hide the "Settings" button or take its place for something more useful:
![proposal2 1](https://user-images.githubusercontent.com/30182251/232305870-c928768d-1ed0-4489-8c0e-a38455467359.png)

**Comment by Limfjorden** [comment]
I think this should be an option since the current keyboard does take up a lot of the screen. For example, sometimes I can't see the input field on Duolingo because the green Check button has been pushed up and now covers it.

**Comment by SamuXzX** [comment]
I think that if we could have it had a more rectangular shape it would be more comfortable. I also think that we can find a layout which has the spacebar at the center.
I was thinking about having a central button like Typewise has: it permits taps and gestures and can be placed anywhere without occupying three whole blocks.

**Comment by dessalines** [comment]
You can create these layouts, the only requirement is that its a grid, and that the key sizes are square.

**Comment by SamuXzX** [comment]
Thank you. Then I will give it a try. Can we keep this thread open for when I'll come back with a draft?

**Comment by dessalines** [comment]
Sure.

**Comment by UnchartedSystems** [comment]
I was going to comment the same thing! Messagease is only comfortable for me at full width, as the width of the kb matches my muscle memory for the width of the screen. Currently the height of keys at a full width size takes up more the half my screen!
[Screenshot_20230426-144111_GitHub.jpg](https://user-images.githubusercontent.com/20145459/234697299-875f1ca4-eee1-4046-bea0-2bb9ce1c0f8e.jpg)

![Screenshot_20230426-144101_GitHub.jpg](https://user-images.githubusercontent.com/20145459/234697298-4e2f5a32-b5a0-484c-bd39-36934c58ed35.jpg)
