### ISSUE TITLE
better directional animation

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#159]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

** Describe the feature request below **
currently all letters come from the top, even when swiping, this is slightly confusing.
i suggest tapping just shows the new letter, no movement.  
swiping should bring the letter from the opposite side of the swipe -> left swipe from 'a' should animate 'l' coming from right to center

**Comment by dessalines** [comment]
I tried many different jetpack animations when creating this, and the top slide was the best of all of them? Could you fork this and test different animations, so I can see what you mean? Thanks.

**Comment by dessalines** [comment]
I'll re-open if you decide to work on this.
