### ISSUE TITLE
custom binds in-app

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#160]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

** Describe the feature request below **

i think it would be really good to add a way for users to create layouts inside the app
- i would be really interested in a layout thats based on the english one, but has slovak and german accent characters also, 
however i fully understand you not wanting these types of layouts in the app by default, since they're just way too specific
    - this would also allow multi-lingual people to do the same thing - pick a layout they use the most and then just add specific accent characters they require for typing only sometimes
- i center the keyboard anyway, (82 height and right align) so i could really use the extra space for 4 more keys to avoid layer switching/put some more frequent symbols on the home layer
- it could lay foundation for users to create & share their custom layouts easily
- i could add text navigation keys to the right like in the neo2 layout (similar)
  
overall i think it would be a really good idea to allow making custom layouts (with option to base them on existing ones) right in the app, as it would allow for a greater amount of customization and also due to the above reasons

### bonus things in the future if this gets added:
- a way to import & export layouts, so they can be shared on reddit/discord/etc & backed up for personal use

**Comment by dessalines** [comment]
> i think it would be really good to add a way for users to create layouts inside the app

I understand the desire to add this, but because it requires untyped data structures (thus creating 2 separate ways to define a keyboard), as well as lots of complication with saving, storing, and not being able to compile-time check layouts, I'm not going to add this. 

If someone wanted to fork thumb-key to add this, they're welcome to do so, but I don't want to maintain two keyboard definition languages.

**Comment by KraXen72** [comment]
okay, and would you be willing to merge a specific layout like the one i mentioned? i saw someone else also wanted a polish/french? layout with the same layer positions as english, to avoid context switching/muscsle memory confusion.

**Comment by dessalines** [comment]
Yes of course, I'll merge pretty much any layout people request.

**Comment by dessalines** [comment]
I do want to stress tho, its **much better* to make specific language layouts, made with letter frequencies in mind, and use the keyboard switcher to switch between them if you speak multiple languages. I'll merge them, but I'm not a fan of these anglo-centric universal layouts.

**Comment by KraXen72** [comment]
i understand it is much better due to letter frequency, bi-grams etc. however, for me its much better to build one muscle-memory for the main language i type in (english) and then re-use it for other languages i type in less (slovak like 35-40%, german 10%)
i could use slovak layout as my main but it's not worth it for me to learn 2 sets of layouts, since i mix slovak and english mid-sentence usually anyway.
