### ISSUE TITLE
Setting to disable spacebar multitap

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#163]
Have a setting to disable the spacebar multitap.

**Comment by DeflateAwning** [comment]
Different proposed solution: have a "Spacebar Multitap Behavior" setting, with the following options:
1. Disable
2. Type "comma space"
3. Type "period space"

Option 3 is the default in most keyboards.

**Comment by dessalines** [comment]
No, I'd just have this a simple boolean. There's many more multitaps after the two you've mentioned, and there's an infinite number of customizations people might suggest to this. I'm not required to follow what's default in most keyboards.

**Comment by DeflateAwning** [comment]
> I'm not required to follow what's default in most keyboards.

No one said you were. It does make the transition easier though, as people try to adapt to a brand new keyboard layout.

**Comment by jeremiah-miller** [comment]
I'm not sure how the multitaps get cycled, but if it's just a static string (i.e. ",.?!:;") that gets cycled through, maybe there could be an option to create a custom cycle string? So then somebody who uses periods more than commas could change the string to ".,?!:;"? It might be more trouble than it's worth to limit the string to at most one of each of those characters

**Comment by DeflateAwning** [comment]
I really like that idea! That would be a great configuration setting
