### ISSUE TITLE
vibration not working on samsung galaxy m21

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#164]
** Thumb-Key Version **
latest, 0.0.1.1

**Describe the bug**
even after enabling vibration, no vibration occurs. only keyboard i've tried that has vibration is samsung keyboard

**To Reproduce**
1. enable vibration
2. type

**Comment by dessalines** [comment]
This is an android system issue, nothing to do with thumb-key. Make sure you have that enabled in your system settings.
