### ISSUE TITLE
improved layout picker

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#165]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

** Describe the feature request below **
here is a mockup i made for how an improved layout picker could look. since you said you'd merge almost any layout people pr, i imagine it could get cluttered in a scrolling popup list with no search pretty quickly.

![thumb-key](https://user-images.githubusercontent.com/21956756/232583391-b5c2400f-f4cb-477a-9fe3-07415687ca27.png)
## reasoning:
- bottom nav: separate settings about keyboard's behaviour from the layout
- reorder tab: once you have more than 3 layouts, you'd probably want to cycle through them in a specific order. might be overkill, but i think it's better than artificially limiting user to say 3 layouts to prevent long cycling of layouts
- select tab:
    - card view: **BIG PICTURE,, EASY CLICK**
    - list view: scroll through languages until you find your language
    - checkboxes: show which layouts are selected even from the "browse" screen
    - layout previews: probably not needed, atleast for language layouts, but could be pretty useful for custom/programmer layouts, to see what they do before applying them. but tbh, even just trying out a layout is so little work that they are probably not needed.
        - would be cool & visual tho; monkey like picture, monkey select layout
    - search bar: once people pr their personal combined layouts, you could serach for them, for example izzyDroid's programmer layout or KraXen's en-sk-de layout or whatever
  
 sorry not sorry for mspaint mockups :P

**Comment by dessalines** [comment]
There's no reason to add any of this. The current layouts popup picker works fine ( once my PR to add scrolling to alorma/compose-settings is added ).
