### ISSUE TITLE
Add subscription / paid play store version

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#17]
For clarification, the f-droid and github versions will always remain free, but I'll probably do a paid / subscription-based play store version.

**Comment by GrimPixel** [comment]
Hey, have you read GNU Affero General Public License v3.0?

**Comment by skorokithakis** [comment]
@GrimPixel that should be fine, I'd buy the Play store version to support the project. I wouldn't buy a subscription, but I'd buy a one-off.

**Comment by pshirshov** [comment]
I won't pay for a subscription but won't mind even a high price (€100+) if you are committed to maintain the project.

**Comment by dessalines** [comment]
I appreciate that, but single payments are not an effective method for funding open source. Dozens of projects tried to survive on that model (one-time payment), and failed. The monthly / yearly recurring donation model keeps creators like me incentivized to keep these going many years later.

**Comment by pshirshov** [comment]
For me personally a subscription for a non-critical tool is a complete no-go.

**Comment by dessalines** [comment]
I'm gonna go with a simple paid version for google play. It's too much of a hassle to add in app subscriptions, and maintain two separate branches.
