### ISSUE TITLE
Alternative Polish Layout based on Letter Frequency

### ISSUE THREAD

**Issue by dominmana** [dessalines/thumb-key#173]
I looked at the proposed solution and discussion in issue #148 and have decided to create a layout that is based on this [Letter Frequency](https://sjp.pwn.pl/poradnia/haslo/frekwencja-liter-w-polskich-tekstach;7072.html) that I found online. I can't tell 100% whether this statistic is the best one, but I compared it to other ones and they look similar.

Based on the above, the letter usage frequency boils down to this: `aioeznrws tcyk dpmu jlłb gęhą óżść fńqź vx`

My proposition has slight modifications, but I tried to follow @dessalines guidelines [How do I add my language or layout](https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout). I broke up the letter frequencies into sections and distributed them in accordance with the guidelines. I only switched `Y` with `U` so that I can keep similar characters and sounds on the same key. 

For all Polish diacritics I tried to use the principle of swiping towards the bottom right corner on keys where the base letters are located. The only exception is `L + Ł `which has separate swipes on the center key (due to letter frequency) and `Z + Ż + Ź`, which requires two different swipes (bottom right, and bottom left).

Here is a preview I created in gimp:
![image](https://user-images.githubusercontent.com/69216944/232820658-749a77a6-581b-479e-acfc-e071d8b99309.png)

Below is the modified file, based on #148 by @CGenie
[ThumbKeyPLv2.zip](https://github.com/dessalines/thumb-key/files/11263397/ThumbKeyPLv2.zip)

I don't know how to create a pull request, so I am adding this issue, hoping that @dessalines can sort this out and maybe add the files to the repo.

Any comments and modifications are welcome. Let's make the best layout together.

**Comment by dessalines** [comment]
Thanks! I'll get this added shortly.

**Comment by dominmana** [comment]
I'm terribly sorry, I did not notice that I messed up the Uppercase/Lowercase/Allcaps button. I just copied from someone else's solution and only now I decided to compare my layout with @dessalines original English layout. In the previous file, that I posted, the following lines are missing:
``` 
SwipeDirection.BOTTOM to KeyC(
    display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropDown),
    action = KeyAction.ToggleShiftMode(false),
    color = ColorVariant.MUTED
),
SwipeDirection.TOP to KeyC(
    display = KeyDisplay.IconDisplay(Icons.Outlined.KeyboardCapslock),
    capsModeDisplay = KeyDisplay.IconDisplay(Icons.Outlined.Copyright),
    action = KeyAction.ToggleCapsLock,
    color = ColorVariant.MUTED
),
```
I am new to this github thing so thanks for your patience. This file below should be ok:
[ThumbKeyPLv2.1.zip](https://github.com/dessalines/thumb-key/files/11265312/ThumbKeyPLv2.1.zip)

**Comment by dessalines** [comment]
Do a Pull Request / click edit on that file, now that its there.

**Comment by dominmana** [comment]
I thinks it's good. For some reason those lines are there. Not sure how that happened, maybe I was just tired.

**Comment by dominmana** [comment]
> This is great, thank you! One remark though: would it be possible to add `q`, `v`, `x`? These are useful (e.g. `"18 V"`) and switching layouts is not the best way.

But it's there! Q is on the middle Key (Swipe UP), V and X are on the Middle Bottom Key (Swipe Right and Swipe Left respectively). Try it out!

**Comment by CGenie** [comment]
I'm blind, sorry, it's there!
