### ISSUE TITLE
Two-hand design

### ISSUE THREAD

**Issue by Shura0** [dessalines/thumb-key#178]
Hi.
It would be nice to have possibility to use two hands for typing, like on Messagease
![Screenshot_20230418_222235_Firefox Beta](https://user-images.githubusercontent.com/2156669/232883606-c8d4f44a-9fe8-4a0c-99f2-56459d8fa389.png)

But after years of messagease using I can suggest some improvements for it
1. Space bar not in bottom, but between the letter blocks
2. Some layout with 2 key hight and 4 keys width (8 in two-hand mode), it will increase display area, so keyboard will be smaller than any regular qwerty one

**Comment by dessalines** [comment]
I probably won't tackle this, but someone else is free too.

**Comment by pshirshov** [comment]
Actually this particular feature (plus multitouch support) lets me type at about 300 cpm when I do it with two hands.

**Comment by dessalines** [comment]
These can be added as custom keyboards.
