### ISSUE TITLE
Inconsistency in taping space bar for punctuation while auto-capitalize is On

### ISSUE THREAD

**Issue by somehare** [dessalines/thumb-key#18]
If you keep taping space bar, the results are different depending if the auto-capitalize is On or Off.

While Off: Double space will create a period. If you press it again, it will change the period for a comma, again for question mark, again for exclamation mark, again for colon. ( '.' → ',' → '?' → '!' → ':' )

While On: Double space will create a period. If you press it again, it will just create another space.

**Comment by dessalines** [comment]
Yep, this one is a complicated bug that I'm not exactly sure the best way to fix. 

When auto-capitalize is on, punctuation follow by a space means it has to switch to a totally different, shifted keyboard. And I currently have the multiple tap logic working only for an individual key on a specific keyboard, so the switching throws it off.

**Comment by somehare** [comment]
What if comma and period get swapped from order placement? That wouldn't fix the bug, but at least could give the user one more punctuation option.
Beside that, comma is probably more used in internet language than period, so I think it might be a good idea positioning it as the first option.

**Comment by dessalines** [comment]
It wouldn't fully fix the issue, because when you get to the next punctuation marker, it would switch to the shifted mode.

But I do agree, commas are more common than periods, so I'll change the first double-tap to that.

**Comment by dessalines** [comment]
This should be fixed now.
