### ISSUE TITLE
consistency between programmer & english v4 layouts with apostrophe

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#183]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

** Describe the feature request below **
please move the apostrophe in the programmer layout to the same space it is in english layout. why is it moved? it even has space where it was before lol.

**Comment by domportera** [comment]
I moved it took avoid accidentally typing the letters adjacent to it, and to place it near the double quotes `"` for a more logical programming placement. if you notice, there is spacing around all the swipe letters in that way too

that being said it's definitely pretty far out of the way and it wouldn't be so bad to move it back down

**Comment by KraXen72** [comment]
ah, i understand. well, currently it is quite hard to type as i keep accidentally swiping to > or ^. but i see the around letter padding, thats good.

**Comment by KraXen72** [comment]
i find it that due to how close your right thumb is to the i key, it's trivial to do a big, clear swipe to make an apostrophe, while to do it on the top, you have to go out of your way to stretch and it subconsciously results an a shorter swipe that aften sends a ^ or >

**Comment by domportera** [comment]
yeah that's definitely valid. The same thing happens to me. I wasn't able to find a better place for it, but since being reminded of the space bar it's possible we can remove the comma at the bottom and replace it with the apostrophe

**Comment by KraXen72** [comment]
well, anywhere you put it it should best be consistent with default en leyout to avoid having to do mental gynnastics when switching. but idk if you can move stuff in default en layou, since most people use it

**Comment by domportera** [comment]
yeah i think that's probably best. It's really not the end of the world to move the apostrophe back in its original position - if you or others agree that's best that's a simple swap

**Comment by KraXen72** [comment]
imo a top swipe from e or t could work (and not be consistent, but eh whatever)
