### ISSUE TITLE
hide letters also hides symbol/number layer

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#184]
** Thumb-Key Version **
0.0.12-alpha

**Describe the bug**
hide letters also hides symbol/number layer. i understand it is a good option to memorize the letters, but also hiding symbols in the symbol layers is useless imo. if its a feature feel free to close this, however it would make more sense to only hide letter in the default layer.

**To Reproduce**
1. Go to settings
2. Click on 'Hide Letters'
3. Switch to Symbol Layer
4. See that it's also blank

**Comment by dessalines** [comment]
I don't want to add the complication of having specific keys disregard that hide letter feature.

**Comment by KraXen72** [comment]
are you really supposed to also memorize the symbol layer???

**Comment by dessalines** [comment]
I'll re-open this up if you're willing to work on it, and support the complication of maintaining which specific keys are hidden.

**Comment by KraXen72** [comment]
i'd just specify it per-layer, not per key. per key-seems overkill
i don't mind the layerswitcher key being hidden on main layer, just when im going to type a symbol i wanna see them lol.
but honestly i barely use this setting, so not sure if i'll work on it. we'll see after/if i manage to implement the spacebar thingy.
