### ISSUE TITLE
Spacebar Double Tap Function Indicator

### ISSUE THREAD

**Issue by RageGamerBoi** [dessalines/thumb-key#186]
I've been trying to figure out how to quickly type a comma, and was just about to make an issue for it, when I found out that you just double tap the spacebar.
There should be some sort of indicator for this (and one that it changes to a period in the number layout).

**Comment by RageGamerBoi** [comment]
Maybe even just replace it with a swipe up gesture for the comma specifically, since there isn't a key for it on the main screen.

**Comment by dessalines** [comment]
Check the guide that's shown when you install thumb-key. I don't want to clutter up the ui too much.
