### ISSUE TITLE
Shift mode management

### ISSUE THREAD

**Issue by tartoci** [dessalines/thumb-key#187]
The shift mode doesn't appear to work the same way when auto-capitalize is on or off:
- If auto-capitalize is on: the shift mode is toggled off after the next letter like a shift key
- If auto-capitalize is off: the shift mode must be toggled off manually like a shift lock key

I'd like to have both keys in both modes:
- If I swipe up, shift lock behavior
- If I swipe down, shift behavior

Actually I turned off auto-capitalize because it doesn't work reliably with termbox as mentioned in another issue, but having to turn off manually the shift mode is irritating.

Moreover, I think a dedicated button would be welcome (when auto-capitalize is off, but also when it is on for names and acronyms).

Thanks!

**Comment by dessalines** [comment]
I'm thinking about completely removing auto-capitalize. Its a pain to maintain, and is different depending on the language.
