### ISSUE TITLE
view and manage clipboard history

### ISSUE THREAD

**Issue by priyavrat-misra** [dessalines/thumb-key#194]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

A clipboard manager similar to https://github.com/openboard-team/openboard

**Comment by dessalines** [comment]
I don't have time to add this, but if someone wants to work on it, feel free.

**Comment by kcryptonian** [comment]
We're still waiting for this feature pleaseeeeee

**Comment by dessalines** [comment]
Can re-open if someone wants to work on this, but integrating a clipboard manager would be a big task, that's probably better suited to specific apps.

**Comment by Toldry** [comment]
Adding my vote that this is an essential feature.

It is also present MessagEase, so lacking this feature is a pain for people migrating from MesssagEase.

I may implement this myself if I find the time.

**Comment by dessalines** [comment]
I'll re-open if someone wants to work on it.
