### ISSUE TITLE
Persian layout change

### ISSUE THREAD

**Issue by pexemo** [dessalines/thumb-key#197]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
After about a month of using Persian layout of Thumb-key I changed some charaters position and tweaked them a little for better typing experience.

Here is my edited file:
https://gist.github.com/pexemo/576830f61184232a74ed23b9b0a1bb93

**Comment by dessalines** [comment]
You can click edit on the existing file in github, and it will give you the option to open a pull request.
