### ISSUE TITLE
Cursor move to wrong position after inserting text longer than 1 character - with solution

### ISSUE THREAD

**Issue by sslater11** [dessalines/thumb-key#216]
When we insert text using a button that inserts a string with more than one character, the cursor ends up in the wrong place.
E.g. Thumb-Key English v4 (Programmer) can insert "https://", but the cursor moves to the wrong place after inserting.

**To Reproduce**
1. Change to Thumb-Key English v4 (Programmer)
2. type 'ooooooooooooooo'
3. Click in the middle of that text to move the cursor there
4. Swipe up on the 'A' key, then we see the 'T' key now has "https://"
5. Swipe left on the T key to insert "https://"
6. Notice the cursor is now several letters away from the text it input. It's distance is the length of inserted text - 1 place away.

**Solution**
Change line 186 in
thumb-key/app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt

change this
```
            ime.currentInputConnection.commitText(
                text,
                text.length // this is wrong
            )
```
to this
```
            ime.currentInputConnection.commitText(
                text,
                1 // This works for single characters, or any length of text we enter, including empty strings.
            )
```

Is there any point making a pull request? it's only one line that needs changing.

Setting a value to 0 will make the cursor appear before the text inserted, 1 is after the text inserted. Any other number is x places away from the inserted text, and you can even use negative numbers to move the cursor left.
I also tested this solution with a key that has an empty string, and the cursor stays where it is, which is what you would expect to happen.

**Comment by dessalines** [comment]
Sure, if you tested it already, do a PR.

**Comment by sslater11** [comment]
I've created a pull request that fixes this. I also made the animation look smoother, and made a Toast() notification for when the user switches layouts :).
[Pull Request #218 ](https://github.com/dessalines/thumb-key/pull/218)

**Comment by dessalines** [comment]
Thanks for these!
