### ISSUE TITLE
Messagease German Layout

### ISSUE THREAD

**Issue by Saturo78** [dessalines/thumb-key#219]
I´m a longtime user of messagease and I am sad that the app seems to be discontinued.

Now I have discovered thumb-key and would like to ask if it is possible to set the German messagease layout.
It looks like this:

A N I
H D R
T E S

**Comment by dessalines** [comment]
https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout

**Comment by Saturo78** [comment]
I´m really sorry but i´m not able to edit such a file. I can modify a layout in that way which provides messagease.

**Comment by dessalines** [comment]
I'll reopen this if anyone decides to add it.

**Comment by Saturo78** [comment]
A project that claims to be the follow up of messagease should also offer the german standard keyboard of messagease. I am full of thanks and appreciation for this.

**Comment by Saturo78** [comment]
I have made two little errors.
Lowercase ß and z shound have color variant primary like "w" for exaple.

Could you be so kind and change these two things?

**Comment by dessalines** [comment]
You can click edit on that file to fix these.

**Comment by Saturo78** [comment]
I´m not sure which file you mean. Should i edit my posted code above?

Thanks for your clarification.

**Comment by dessalines** [comment]
Click the edit file button on github. You can watch some videos or read tutorials on how to do this.
