### ISSUE TITLE
Norwegian layout

### ISSUE THREAD

**Issue by sotolf2** [dessalines/thumb-key#232]
I think I did this the right way, had to change the file to txt to get github to let me upload it. I'm pretty sure I got this right, but the R key might be wrong since I had to add some swiping direction to get space for our larger alpahbet. this is based on the letter frequency of the Norwegian alphabet:

ENTRAISDLOGKMVHUPFÅBJØYCWÆZXQ

I'm still a bit unsure how good it would be to type on, so it might be that it would need some later refinement, but I followed the outline made in the readme for how to allocate the placement of the different letters.

Best regards.

[thumbkey_no.txt](https://github.com/dessalines/thumb-key/files/11516832/thumbkey_no.txt)

**Comment by Limfjorden** [comment]
You can take a look at my Danish keyboard if you're unsure where to add the extra letters:)

**Comment by xdpirate** [comment]
Wikipedia suggests a different letter frequency: ERTNSIALODGKMVPFUHÅBJØYCÆWXZQ

https://no.wikipedia.org/wiki/Frekvensanalyse_(kryptografi)

**Comment by dessalines** [comment]
I'll add the keyboard as is (if it doesn't have errors), then yall can make PR changes to it based on these new frequencies.
