### ISSUE TITLE
Floating & Transparent mode

### ISSUE THREAD

**Issue by SkullGamer205** [dessalines/thumb-key#233]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
#
### **_Add floating and transparent keyboard mode._** 

 Reasons:  

 1. It is not always convenient to use the keyboard when it is in one of the three presets. There is a desire to move to another corner of the screen (Even to the top)... 
   (thus, users can set the keyboard as they please) (And yes, I use Samsung)
 
 2. When using some applications, the keyboard overlaps some of the information. (Examples below) 
![изображение](https://github.com/dessalines/thumb-key/assets/61167080/34fc0c82-cd32-4afb-94e5-91357dbddc05)
![изображение](https://github.com/dessalines/thumb-key/assets/61167080/5c7c8037-2c3f-4258-a4ad-509d278ae838)

**Comment by dessalines** [comment]
I probably won't work on this, as floating keyboards hide content that you should be seeing, and most android apps correctly push up their content so that keyboards don't hide it. 

But feel free to add a PR to add this.
