### ISSUE TITLE
Custom Layouts...

### ISSUE THREAD

**Issue by SkullGamer205** [dessalines/thumb-key#234]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

#

### **_Add the ability for users to create their own layouts without pull requests and forks_** 

 Reason: 

[This guide](https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout) is certainly good, but for ordinary users it will obviously not be convenient. Plus, you WILL have to submit your layout to github, which is not a good thing. Yes, there is such a thing as FORK, but this is not always convenient. You need to fork the repository, create your layout, compile your result, AND ONLY THEN USE, which is not very convenient. And do this every time if you want to change it (Add symbol(s), change button layout, etc...). It's easier to make your layout as a .txt, .cfg, or other type of file and store it in `/storage/emulated/0/Android/data/<application-name>/layouts` or in `/storage/emulated/0/Thumb-key/layouts`. It also allows people to create a convenient layout for themselves or their friends, or make support for a language that is not in the repositories, create "shortcuts" for abbreviations, an emoji/kaomoji keyboard. Plus, everyone can have a unique keyboard, which will have a positive effect on privacy..

**Comment by dessalines** [comment]
Definitely not going to add a 2nd untyped/ uncompiled keyboard config, for reasons mentioned in other issues.

> , you WILL have to submit your layout to github, which is not a good thing. Yes, there is such a thing as FORK, but this is not always convenient. You need to fork the repository, create your layout, compile your result, AND ONLY THEN USE, which is not very convenient

None of that's necessary, and in the guide I even explicitly state you only have to open an issue and attach / paste your keyboard file for me to add. 

You do not have to compile anything, or be a developer to add a keyboard; nearly all but maybe 2 of the keyboards were added by non-devs.

As stated elsewhere, I will add anyone's keyboard, and merge them as quickly as I can. 

If you want to fork this project, and add a 2nd, uncompiled / not-checked keyboard config, and want to maintain it, feel free to do so. But I don't have the time to maintain unchecked keyboards.

**Comment by Saturo78** [comment]
I think the opportunity to customize the keyboard is a must have feature.
If not planned, I do not predict a great future for the app. Too bad.
