### ISSUE TITLE
Swedish layout support

### ISSUE THREAD

**Issue by PVCParrot** [dessalines/thumb-key#238]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

Please add it, you should be able to copy one of the other Scandinavian layouts and replace the last three letters of the alphabet.

**Comment by dessalines** [comment]
https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout

**Comment by dessalines** [comment]
I'll reopen this should you decide to add one.
