### ISSUE TITLE
add Indonesian layout

### ISSUE THREAD

**Issue by awandepan** [dessalines/thumb-key#241]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

I try to create Indonesian ( Bahasa Indonesia ) layout based on this http://simia.net/letters/ and try to follow the guide in readme

aneirtusdkmlgpbohyjcwf10v29583467zxq

this file is based on ThumbKeyENv4Symbols.kt

[ThumbKeyIDv1Symbols.txt](https://github.com/dessalines/thumb-key/files/11554862/ThumbKeyIDv1Symbols.txt)

**Comment by awandepan** [comment]
sorry @dessalines , i forgot to change the letter at row 337 and 338 from "e" to "a"

[ThumbKeyIDv1Symbols.txt](https://github.com/dessalines/thumb-key/files/11570004/ThumbKeyIDv1Symbols.txt)

**Comment by dessalines** [comment]
Go to that file and click edit now to make changes.
