### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by ca-cl2** [dessalines/thumb-key#247]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
Using Thumb Key when the phone's in landscape mode is kind of awkward.
It uses up a lot of the vertical screen space while not using much of the horizontal screen space.
![Screenshot_20230526-072452](https://github.com/dessalines/thumb-key/assets/98461965/b1cc9623-ec41-4d41-a0dd-fb3b9480c643)
For comparison, this is how MessageEase does it...
![Screenshot_20230526-072507](https://github.com/dessalines/thumb-key/assets/98461965/c24e3f9f-2e54-471a-81fa-2740660a421b)
It squishes down the keys, while also putting the numeric keypad on the right.
It would be great if Thumb Key could do this!

**Comment by dessalines** [comment]
Dupe of #155

**Comment by gunduzc** [comment]
It would be great if the keyboard could just occupy the left/right side of the screen. Would be very useful with Termux.
