### ISSUE TITLE
How to get special chars from different language?

### ISSUE THREAD

**Issue by datenbank-projekt** [dessalines/thumb-key#249]
Hi,
not a real bug, but a huge problem if one uses different languages. If i have the german layout ,it seems  impossible to get spanish characters for example.
As much as i like to try the keyboard, as i need to write in different languages, there should be a way to access special  letters and characters like on a "normal" keyboard.
Characters like áñößâ ...

**Comment by dessalines** [comment]
Use https://lemmy.ml/c/thumbkey for questions in the future, you deleted the template where I explicitly say to do that.
