### ISSUE TITLE
Auto-update 

### ISSUE THREAD

**Issue by reejit** [dessalines/thumb-key#25]
Add auto update feature as in LibreTube and other such open source apps. As it is really ineffective to download and install all the way round.

**Comment by reejit** [comment]
Something like this.

```
val updateManager = UpdateManager.Builder(this)
    .mode(UpdateManagerConstant.IMMEDIATE)
    .url("https://github.com/dessalines/thumb-key")
    .build()

updateManager.checkForUpdate()

```
We can also use the inbuilt InAppUpdater library the dependencies are as follows:
```
dependencies {
    implementation 'com.google.android.play:core:1.10.0'
}
```

**Comment by dessalines** [comment]
I'd rather rely on android package managers to handle app updates, like every app does.

It's already on izzy, and should get added to f-droid soon.
