### ISSUE TITLE
MessagEase French layout for Thumb-Key

### ISSUE THREAD

**Issue by cosminribo** [dessalines/thumb-key#251]
Hi and many thanks for providing the keyboard and a willingness to provide alternative and contributed layouts for Thumb-Key. I changed the MessagEase EN layout file to a French one that copies the one that was provided by MessagEase with only one change:

- one of the accented "u" letters is very rarely used, so I replaced it with the more useful "ô"

I hope that the format is fine. It would be great for those, like me, who are proficient in using one of the MessagEase layouts to be able to find them in Thumb-Key.

[MessagEaseFR.txt](https://github.com/dessalines/thumb-key/files/11578410/MessagEaseFR.txt)

**Comment by dessalines** [comment]
Thanks! I should get around to adding this next week.

**Comment by cosminribo** [comment]
Fantastic. Thank you very much.

**Comment by dessalines** [comment]
Now that the keyboard is added, you can go to it directly and click edit to make changes (called pull requests).

https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/MessageEaseFR.kt

**Comment by dessalines** [comment]
I don't know what changes need to be made specifically, so it'd be helpful if any one of you would make that change.
