### ISSUE TITLE
"Vibrate on tap" does not work

### ISSUE THREAD

**Issue by IndivContrib** [dessalines/thumb-key#253]
** Thumb-Key Version **
1.2.0

**Describe the bug**
With "vibrate on tap" checked, no vibration can be sensed.

**To Reproduce**
check "vibrate on tap"

**Comment by dessalines** [comment]
You need to go into your android settings, and make sure you have vibration on touch feedback enabled.

https://support.google.com/accessibility/android/answer/9078946?hl=en
