### ISSUE TITLE
Volume changes with certain characters

### ISSUE THREAD

**Issue by IndivContrib** [dessalines/thumb-key#254]
** Thumb-Key Version **
1.2.0

**Describe the bug**
With "play sound on tap" certain characters change the volume.
Keyboard layout "Thumb-Key English v4"
**g** : lowers volume to silence
**m** : changes volume between silence and maximum
**l** : changes volume between silence and maximum
Maybe there are more, but those I could clearly identify

**To Reproduce**
1. Load Thumb-Key English v4 layout
2. Check "play sound on tap"
3. Write the above letters multiple times, about 10+
4. Hear error

**Comment by dessalines** [comment]
I tested this, and can't replicate it. 

Every single key uses an [identical audio playback](https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt#L124), there is no custom audio behavior for certain keys.
