### ISSUE TITLE
Extra white line on right side of keyboard when hiding borders

### ISSUE THREAD

**Issue by Lavin-tom** [dessalines/thumb-key#260]
** Thumb-Key Version **
1.5.0

**Describe the bug**
When hiding the borders in the settings, an additional white line appears on the right side of the keyboard. The length of this line varies based on the key size. It is unclear whether this is a bug or a problem specific to my system.

**To Reproduce**
1. Go to the settings.
2. Navigate to the "Borders" section.
3. Enable the option to hide borders.
4. Open the keyboard and observe the right side.

**Screenshot**
![keyboard-issue](https://github.com/dessalines/thumb-key/assets/53207510/c960799d-84bb-4442-a33e-bd27198fa78f)

**Comment by dessalines** [comment]
Really weird one, I can't see that on my devices. And there isn't any border there in the code.

**Comment by dessalines** [comment]
Closing as I can't replicate no matter how hard I try.
