### ISSUE TITLE
T9 keyboard

### ISSUE THREAD

**Issue by FriedGrregg** [dessalines/thumb-key#263]
I've attempted to create a T9 keyboard. It only shifts the letters and most of the punctuation or functions remain the same. Might need some refining in terms of character positioning. Please check it out and include it with the app if possible. See [file](https://drive.google.com/file/d/14KVV0YdVhmtoiFhYbvbblKmvCxJVxzeN/view?usp=sharing)

Thanks - Grregg

**Comment by dessalines** [comment]
Thanks for this!

**Comment by FriedGrregg** [comment]
I created a spreadsheet to build the keyboard at https://docs.google.com/spreadsheets/d/1i6scYO3PHnyvA_JwB09WMA_8ynCeZiDZ/edit?usp=drivesdk&ouid=104537806631073015802&rtpof=true&sd=true

A few "hacks" used to introduce additional code e.g. for multi-space function.

**Comment by dessalines** [comment]
Sweet. If you wanna add any changes to the keyboard later, click edit on that keyboard file in this repo.

**Comment by FriedGrregg** [comment]
Sorry for the repeat changes. Made a couple of mistakes.
