### ISSUE TITLE
Add useful shortcuts to Italian keyboard

### ISSUE THREAD

**Issue by flauta** [dessalines/thumb-key#279]
In the italian words, letter Q is always followed by U (except for 1 word in the whole dictionary). 
Frequent digrams are also CH and GH. 
I propose to add these shortcuts to the keyboard, using the empty slots in the same keys: 
key R --> bottom_left QU (can be also O bottom_left - I choose both)
key A --> bottom_left CH
key E --> bottom_left GH
I submit the modified KT file.
[ThumbKeyITv2_FL.kt.zip](https://github.com/dessalines/thumb-key/files/11692281/ThumbKeyITv2_FL.kt.zip)

**Comment by dessalines** [comment]
You can do a PR / click edit on that file directly.

**Comment by racuna** [comment]
In Spanish is very common "qu", the thing is how to make it compatible with the Caps "lock" when the kt file only have two modes:

- lowercase: qu
- Uppercase: Qu
- UPPERCASE: QU

**Comment by flauta** [comment]
I don't know if in Spanish language you often find the "QU" digram. In Italian that combination only appears if the sentence is "all uppercase". 
So in the italian layout I have put Qu (in the uppercase layout) and qu (in lowercase), leaving out QU - that you can always write combining the single letters Q and U.
