### ISSUE TITLE
Undo / redo buttons

### ISSUE THREAD

**Issue by bammerlaan** [dessalines/thumb-key#284]
- [x ] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey
** Describe the feature request below **

I'd be really interested in starting to work with this keyboard, but what my current keyboard (Multiling O, a rather obscure older keyboard) offers is an undo and a redo button which I would really miss in another keyboard. 

I'm not sure if this would fit anywhere in a practical manner, but it might be something to consider at least. Keep up the good work!

**Comment by sslater11** [comment]
This has now been implemented @dessalines could you please close this :D.
You can now swipe leet/right on the numberpad switcher to undo/redo.
