### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by AliAsgerSaify** [dessalines/thumb-key#288]
- [ ] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
I am using this as my daily keyboard from last few days and learning it along the way. **I want a feature for emoji keyboard ** integrated into this keyboard

**Comment by dessalines** [comment]
#43

**Comment by AliAsgerSaify** [comment]
> #43 

Sorry but I didn't actually got what #43 means.

**Comment by aerkiaga** [comment]
@AliAsgerSaify it means this issue is asking for the same feature as issue #43, so it has been closed. You can subscribe to #43 if you want.
