### ISSUE TITLE
Option to move the settings, layout, backspace, and enter keys to the other side

### ISSUE THREAD

**Issue by clayote** [dessalines/thumb-key#293]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

MessagEase had a nice gesture where if I drew a circle on the settings key, it would move that whole column to the other side of the keyboard. It was convenient when I wanted to switch which hand I was typing with.

I'd like this option in Thumb-Key as well. I'm not wedded to that specific gesture; if it's more convenient to implement this as more layouts, that's fine.

**Comment by dessalines** [comment]
You can create custom layouts that do this, because the setting your talking about would be impossible for the diversity of layouts we have.
