### ISSUE TITLE
hide letters quick toggle/hide letters only on primary layer

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#299]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Problem**  
currently, i really enjoy using hide letters, because it forces me to type from muscle memory and look at the text i'm typing instead of look at the keyboard. However, i still do not have all the symbols on symbol layer memorized, and i am not sure i want to - i don't type them nearly as much as regular text.

**Describe the feature request below**
there are a few ways to solve this problem:
- manually toggle hide letters each time i want to type a symbol (what i've been doing currently, very cumbersome)
- add a toggle to only hide letters on primary layer / add separate hide letters toggles for primary and symlayer
- add a toggle to replace the position swipe on the symlayer with an eye icon to quickly toggle global hide letters - i personally don't really use the positional swipe anyway (optionally, add it as a swipe from the settings key? but i'm not a huge fan of that)

thanks for considering!

**Comment by mockballed** [comment]
Pressing and holding any letter key could reveal/fade-in the symbols (and other secondary keys) on the whole keyboard. I think all symbols are produced by a swipe, then if you happened to be holding the correct key, you could finish the swipe in the direction of the now displayed character.

The obvious problem is that your thumb would most likely be covering the whole key. Maybe the secondary characters on the pressed letter could "expand" outwards to be seen.

The hide letters feature is such a "flex" for Thumb-Key. It showcases that you can effectively touch-type with it - and without predictive text!

The characters we use most often we can type without seeing. On the other side it doesn't make much sense to be displaying all the time the characters we rarely use.

**Comment by KraXen72** [comment]
> The obvious problem is that your thumb would most likely be covering the whole key. Maybe the secondary characters on the pressed letter could "expand" outwards to be seen.
i personally think this would be much harder to implement than just a secondary toggle to show/hide the symbol layer, but it could be pretty cool.

**Comment by KraXen72** [comment]
tangentally related, here's me typing on thumb-key with hidden letters. i would post on lemmy but i don't have an acc.

https://github.com/dessalines/thumb-key/assets/21956756/a813d1f8-0c99-468c-b3db-6bef5dd489f9

**Comment by dessalines** [comment]
You're free to add this if you like.

**Comment by nejni-marji** [comment]
I have implemented this but haven't published it yet.
![Screenshot_20230830-110611_Fennec](https://github.com/dessalines/thumb-key/assets/10968473/8c926a88-0302-432b-a4dd-6ef7a41834c1)
![Screenshot_20230830-110613_Fennec](https://github.com/dessalines/thumb-key/assets/10968473/5ddcc911-d67f-43cc-a51a-d4f4196df21a)

**Comment by nejni-marji** [comment]
I personally enjoy this feature (as implemented on my own local build), but I feel like there might be people who really do want to hide all key labels. The reason I waited to publish a PR is because I haven't looked into how to configure settings or add new settings to the app, and I'm not sure how best to implement all 3 modes:

- show all key labels
- hide just letter key labels
- hide all key labels

**Comment by nejni-marji** [comment]
Maybe there could be two checkboxes, for toggling hiding letters, and hiding non-letters separately?

**Comment by dessalines** [comment]
To add this, you'll need to go into every keyboard definition file, and add types to every key. IE some are "letters" and some are "puncuation". Then you could hide them based on that type.

**Comment by KraXen72** [comment]
arent there multiple separately exported layers for each keymap? pretty sure that most keymaps reuse the same symbol/numeric layer, at least.

**Comment by dessalines** [comment]
That can't work unfortunately, because some keys do multiple letters, and `isLetter()` would fail them.
