### ISSUE TITLE
Auto switching to capital letters only happens after a period

### ISSUE THREAD

**Issue by rmacklin** [dessalines/thumb-key#30]
Just tried this out, and something I noticed immediately was that it automatically switches to capital letters only after typing a period. Entering a question mark or exclamation point does not automatically transition the next key to an uppercase letter, even though those punctuations also end a sentence. (As an aside: it is also noticeably more work to type an exclamation point or question mark compared to a period, which felt inconvenient.)

Additionally, if you type one capital letter and then immediately delete it, it doesn't remember that you wanted to type a capital letter (after typing the capital letter, it switches to lowercase, but doesn't switch back to uppercase if you delete the letter because you want to type a different capital letter instead).

Lastly, it seems to start with a capital letter the first time you switch to the keyboard, but if you switch to another application without switching the keyboard, it doesn't default to a capital letter when focusing on a text field in that other application.

Just wanted to share some feedback, but overall I'm intrigued by the keyboard. I'm not sure how long it would take to get used to, yet, but improving the logic around automatic switching to uppercase would certainly make it easier for me to adopt even before the layout becomes familiar.

**Comment by dessalines** [comment]
> Entering a question mark or exclamation point does not automatically transition the next key to an uppercase letter, even though those punctuations also end a sentence.

I just tested this, and it does work, but only if you switch back from numeric mode to the non-shifted keyboard first. I have it currently never switch away from numeric mode based on auto-capitalization, and the auto-cap rules only run when you input text in either the shifted or non-shifted modes.

> Additionally, if you type one capital letter and then immediately delete it, it doesn't remember that you wanted to type a capital letter (after typing the capital letter, it switches to lowercase, but doesn't switch back to uppercase if you delete the letter because you want to type a different capital letter instead).

Not sure if that should be intended or not, I'll test it out some.

> Lastly, it seems to start with a capital letter the first time you switch to the keyboard, but if you switch to another application without switching the keyboard, it doesn't default to a capital letter when focusing on a text field in that other application.

Should be fixed by #24 , which now should run the startup logic for every new input.

**Comment by dessalines** [comment]
This is fixed now, since the spacebar key is shared.

**Comment by rmacklin** [comment]
Thanks!
