### ISSUE TITLE
Long press letter to type corresponding number

### ISSUE THREAD

**Issue by NODRT** [dessalines/thumb-key#310]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
I'm requesting a feature that I really liked on message ease. This feature allows you type a number by pressing and holding the letter-key that corresponds with the position of the number.

In other words, the top letters on the keypad are "s r o", which would be "1 2 3" on a number keypad, so long-pressing "s" would send a "1", "r" would send a "2", and "o" would send a "3".

The benefit to this is just speed and ease of use. Currently, to type a number, you must press the "#" key, press the number, and then press the "#" key again to return to letters (3 key presses). My request would reduce that to a single key press. It makes for a nice flow. 😎 

Thanks.

**Comment by dessalines** [comment]
I don't want to add tap-to-hold numbers, swipes are the non-tap action I'd like to support. If you want really fast numbers, feel free to add a number-centric layout, and I'll add it.
