### ISSUE TITLE
Minor modifications to the "MessagEase English" layout that could make it better match the original

### ISSUE THREAD

**Issue by random-integer** [dessalines/thumb-key#314]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

As a long time MessagEase user that was getting tired of the bugs it had, I tried out Thumb-Key. The MessagEase layout this app provides really feels like MessagEase! It makes me feel at home.

A screenshot of the MessagEase English with symbols layout for your convenience:

![screenshot of MessagEase English layout on Thumb-Key](https://github.com/dessalines/thumb-key/assets/44129226/385150c5-8f6f-4b54-8fdb-bd1102a30412)

I found some really, really minor modifications that could be made to make this experience more MessagEase-y.

1. An up-swipe from `I` should be `Up` (arrow key).
2. A down-swipe from `S` should be `Down`.
3. A down-right-swipe from `T` should not be `:`. It should be `Tab`. (A down-right-swipe from `E` is already `:`.)
4. The symbols on the numerical keyboard should match the MessagEase version, not the Thumb-Key modified version.

According to my half-baked knowledge of programming, hopefully, none of these individual modifications should be a lot of work. Probably just a quick edit of the layout file? Also, please do also make these changes to the MessagEase layouts of different languages.

Thanks dessalines for maintaining this keyboard. Really appreciate it!

(ps. it's spelled *MessagEase* (3 *E*s), not *MessageEase* (4 *E*s). The layout list uses 4 *E*s.)

**Comment by dessalines** [comment]
1 and 2 already exist as spacebar swipes.

The other ones, feel free to do a PR to the MessageEase layout, or make a new one, as your changes might not be standard.
