### ISSUE TITLE
Implement "u-turn-swipe" gestures

### ISSUE THREAD

**Issue by random-integer** [dessalines/thumb-key#315]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

By u-turn-swipe, I mean swiping in one direction, then u-turning to swipe in the opposite direction without lifting one's finger. Now that I think about it, it's more like a v-turn, but whatever.

On Thumb-Key, you could do a left-swipe on `Space` for `Left` (cursor key), which is good. However, on MessagEase, you could do a left-u-turn-swipe on `Space` to move left a whole word, equivalent to the motion of `Ctrl`+`Left` on desktop. (Try the `Ctrl`+`Left` now if you never have. I'll wait.) On MessagEase, you could also do a u-turn-swipe on any symbol, and it would type out some kind of "associated symbol" to the original. For example, a left-swipe on `2` types `+`, and a left-u-turn on `2` back on MessagEase would type `×`. A left-swipe on `3` types `?`, and a left-u-turn on `3` would type `¿`. This is really useful in my opinion.

I understand that modifying the code to recognize u-turn-swipes might be difficult, so it would be more than great if the dev is willing to implement this. Thanks!

**Comment by dessalines** [comment]
Yep, I really only want to support simple swipes, not multiple direction turns.
