### ISSUE TITLE
Drag-and-return and circle-drag

### ISSUE THREAD

**Issue by Atn-D** [dessalines/thumb-key#317]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

I take up point 2 of this Lemmy post : https://lemmy.ml/post/1072419

One of the features I miss, and which is making me go back to MessagEase, is the ability to capitalize with a Drag-and-return. Or via a circle-drag when it's the central letter.

Combined with request #310, typing speed is considerably increased.

A slightly extreme example is if you need to write "The droid R2-D2 and C-3PO".

**Comment by dessalines** [comment]
I don't want to support complicated drags. Simple swipes only.
