### ISSUE TITLE
Use layer # characters when there's nothing in layer ABC

### ISSUE THREAD

**Issue by Atn-D** [dessalines/thumb-key#318]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

One of the features I miss, and which brings me back to MessagEase, is the ability to use layer # characters when the location is empty for an ABC layer direction.

I'd also love to be able to see these famous characters usable by dragging up the space bar.

Demo video : 

https://github.com/dessalines/thumb-key/assets/1497894/43ce7648-e6ee-42b8-9b0a-b5fedebee5ff

**Comment by KraXen72** [comment]
give the layout 'thumb key english v4 with symbols' a try

**Comment by dessalines** [comment]
Correct, this is done via alternate keyboards.
