### ISSUE TITLE
space+comma in passwords

### ISSUE THREAD

**Issue by niccokunzmann** [dessalines/thumb-key#321]
** Thumb-Key Version **
Type the version from the settings here.

1.8.0

**Describe the bug**

I have a password with two spaces next to each other. I would like the space  key to not make it `, ` when I am typing a password.  

**To Reproduce**
1. Go to a password field
2. Click space twice
3. see a ,

**Comment by KraXen72** [comment]
turn off spacebar multi-taps in settings

**Comment by dessalines** [comment]
I'm not sure if its worth it to detect password fields, especially since no one should be typing in passwords anyway, but using a password manager, and copy-paste.

**Comment by gmartineza** [comment]
If you don't want to disable spacebar multi-taps you can type space, move the cursor left (via swiping the spacebar), and press space again. This ensures a space is output and not any of the multi-tap characters.

**Comment by niccokunzmann** [comment]
Thanks for all the sungestions! My closing criterium for this issue would be that spacebar multitab is automatically disabled for vassword fields.

**Comment by dessalines** [comment]
I can re-open should you decide to implement this.
