### ISSUE TITLE
swipe to delete from backspace key

### ISSUE THREAD

**Issue by Kommynct** [dessalines/thumb-key#329]
This exists in both florisboard and Gboard and is a must have feature for me.

**Comment by dessalines** [comment]
Already exists.

**Comment by Kommynct** [comment]
I didn't see it in the settings and am currently trying to do it and it doesn't work. You can do one word at a time, but not many words

**Comment by Kommynct** [comment]
No, I'm talking about continuing the swipe for fine deletion, similar to how Gboard let's you swipe on the spacebar to move the cursor, these are different things but I'm not in a position to provide a video. That issue is about leaving your key swiped for multiple repetitions, https://github.com/dessalines/thumb-key/issues/48 if you're talking about this it's completely different and he mentions swipe to delete isn't his thing. 

Otherwise I do not see an issue tracker for this.
