### ISSUE TITLE
Either default or toggle option for different color letters

### ISSUE THREAD

**Issue by urmomseksy** [dessalines/thumb-key#34]
It would be nice, especially while learning this keyboard, to have different colored letters around the H-key and also the smaller letters around the other main keys.

So: J,Q,B,K,P,V,X,Y a different color from the main keys 
And: W,G,U,M,L,C,F,D either the same color as the J,Q... set or another different color.

This would provide some additional contrast to make it easier when identifying the letters while learning the keyboard.

I figured you could either make this a default option, or allow a toggle switch to change the colors on those letters.

Thanks!

**Comment by dessalines** [comment]
They are a different color already, they're using android material setondary, while the center keys are primary.

**Comment by urmomseksy** [comment]
> They are a different color already, they're using android material secondary, while the center keys are primary.

Okay, I have a hard time seeing the difference but I can kind of tell that they are slightly different. I was thinking more like way different colors, like yellow or red or green to contrast whatever the base color is.

My current setup is dark dynamic and I also tried light dynamic.

**Comment by urmomseksy** [comment]
Sorry, I was confused. I realized I had to change the color settings on my Android device for the colors to be more divergent.

I will close this issue unless you want to keep it open to possibly enable a setting that overrides system color

**Comment by dessalines** [comment]
No problem... I'd definitely be up for people adding more themes besides the current green and pink. Those are defined [here](https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/ui/theme/Color.kt), and auto-generated from https://m3.material.io/theme-builder#/dynamic
