### ISSUE TITLE
Fdroid build does not verify

### ISSUE THREAD

**Issue by penn5** [dessalines/thumb-key#341]
** Thumb-Key Version **
1.11.0

**Describe the bug**
the apk built by fdroid does not match the one on github

**To Reproduce**
https://monitor.f-droid.org/builds/log/com.dessalines.thumbkey/28

**Comment by jstetten** [comment]
Does this have anything to do with why the apk fails to download on the F-droid app?

**Comment by penn5** [comment]
No

**Comment by dessalines** [comment]
Of course it shouldn't, the one on f-droid is built by them, the one on github / izzy is built on my machine.

**Comment by penn5** [comment]
Yes it should.

**Comment by dessalines** [comment]
> the apk built by fdroid does not match the one on github

What you really mean to say, is that f-droid builds are broken, not that their builds don't match mine. You'll have to open up an issue there, as you can see from my CI, builds are passing fine, its something wrong with f-droid's build system.

**Comment by penn5** [comment]
@dessalines please reopen this, as it is not fixed

You need to either change the f-droid build process so that it results in the same output as on your computer, or change your computer so that it results in the same output as f-droid's build.

Otherwise, updates will not be processed by f-droid.

**Comment by dessalines** [comment]
It's been building fine since 1.12.0, and I changed nothing about the build process in months. F-droid builds suceeded also, you just have to wait a week or two for them to show up.

https://f-droid.org/repo/com.dessalines.thumbkey_29.log.gz

**Comment by penn5** [comment]
My apologies, you're right it's fixed in 1.12.0

I didn't notice this when I looked :sweat_smile:

It was broken in the previous build though…
