### ISSUE TITLE
Enter on shited layer does not behave as Shift+Enter

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#345]
**Thumb-Key Version**
1.11.0

**Describe the bug**
On the normal layer, I would expect the enter key to submit, e.g. send a message in a messaging app. However, many messaging apps support multi-line messages, which are currently impossible to do with ENv4 layout (from my testing). I would expect atleast the enter on shifted layer to behave as Shift+Enter.

**To Reproduce**
1. Go to a messaging app
2. write first line of message
3. Hit shift
4. Hit enter
5. See message submit instead of a new line

**Comment by flauta** [comment]
Speaking about Signal and Telegram that I mostly use:
I find "Send message when pressing Enter" as an option in the messaging app settings. 
If you disable this (as I usually do) you can press Enter to go newline, without actually sending the message.

**Comment by dessalines** [comment]
I don't think we should have a different enter key (or hijack it to hold shift), for the shifted mode, just for this use-case. Enter should be consistent everywhere IMO, and @flauta is correct that chat apps should be responsible for this one.

**Comment by nejni-marji** [comment]
I'm entirely unable to send multi-line messages in Discord with the keyboard as it is. I don't know if this is the same issue or not, but it is _an_ issue. Discord offers no relevant settings, but is works with other keyboards, so something must be different.

**Comment by nejni-marji** [comment]
I started working on a fix, and now I'm seeing how broken Discord's app is, so I understand what you mean by chat apps should be responsible for it. I might add a workaround just for myself, but I don't know if it's worth a PR.

**Comment by alerque** [comment]
Being on a shifted layer should not affect the enter key. While it *is* possible to send modifiers along with Enter that is not an expected result of a shifted *layer* on a keyboard. There could be a separate mechanism (such as MessagEase has) for sending CTRL/AlT/SHIFT as modifiers for chord key combinations separate from sending upper case letters or alternate symbols from keys.

**Comment by nejni-marji** [comment]
My workaround is this:
https://github.com/nejni-marji/thumb-key/commit/86e8fa8ef900cb42415fc13f5a7e552464f6df31
but I don't expect you to want ths upstream.
