### ISSUE TITLE
Brainstorming idea regarding bigrams/digraphs

### ISSUE THREAD

**Issue by urmomseksy** [dessalines/thumb-key#35]
According to this wiki:

https://en.m.wikipedia.org/wiki/Frequency_analysis

"Likewise, TH, ER, ON, and AN are the most common pairs of letters (termed bigrams or digraphs), and SS, EE, TT, and FF are the most common repeats."

Since you have extra space on some of the keys like T, E, A, and O, this would provide space to put bigrams and repeats in the corners of those letters if you wanted.

This non-FOSS keyboard does something similar, although some of the options are hidden until you actually slide the key, so I don't know if you can actually see it based off the play store description:
https://play.google.com/store/apps/details?id=com.combokey.plus

Thank you.

**Comment by dessalines** [comment]
These kinds of discussion are better suited to the community: https://lemmy.ml/c/thumbkey 

I'd like to keep the noise down on this repo, and limit it only to specific code-related issues.
