### ISSUE TITLE
Swiping for Alternate Behavior

### ISSUE THREAD

**Issue by HawksDarris** [dessalines/thumb-key#350]
- [ X ] Did you check to see if this issue already exists?
- [ X ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
# MessageEase Behavior
On the MessageEase keyboard, there is a swipe-and-back behavior that allows the user to select different symbols. 

### Symbols
Swiping on `$` produces '$', but swiping over then back on `$` produces '¥'. In that same way, `&` becomes '§'.  

### Letters 
Swiped letters (i.e., not the nine main keys) switch case. So if you turn on Caps Lock and swipe on `p`, it will make 'P', but if you swipe over and back on `p`, it will make 'p'. Doing a circle out of the main keys then back does the same thing; circling `a` produces 'A' if Caps Lock is not on. 

### Movement
Swiping to the right and back on `Backspace` deletes one word forward; swiping to the left and back deletes one word backward. Swiping to the right and back on `Space` moves the cursor back one word; swiping to the left and back moves the cursor back one word. This is basically the eqiuvalent of holding `Ctrl` on a full keyboard while pressing `Left`, `Right`, and `Backspace`. 

The user can also hold down on the `Space` to enter cursor movement mode, where the user can move the cursor with the held-down finger. I saw another Feature Request about that, but I can't find it to link here now.

**Comment by dessalines** [comment]
You're free to add these, but I don't have the time to. I'll re-open if anyone wants to work on this.

**Comment by asdkant** [comment]
@dessalines I'm willing to work on this, tho I'm not experienced in kotlin so it will take me some time. Which parts of the code are relevant for implemeting this type of functionality?

At the very least I'm guessing more values for the enum class `SwipeDirection` on `Types.kt` to begin with, but I have to find where's the logic that maps user actions to specific values of that enum

**Comment by dessalines** [comment]
Looking at this again, I don't think its a good idea to add. This is more hidden functionality where you have all these keys based on gestures. Why not just add them as explicit swipes to existing keyboards? That's simple and more transparent.

**Comment by asdkant** [comment]
The point of swipe-back gestures (do the normal swipe and go back before releasing the finger) is to add action density to the layout without spending screen real estate.

An example I used *A LOT* with MessagEase is that you don't have `¿` or  `¡` as discreet actions in the spanish layout, they are alternative characters of `?` and `!` respectively.
You can trigger the alternative character action with an upper-left swipe on the upper-left key (it's visually indicated with a highlighted "C"), or you can swipe-back to get the opening character instead of the closing one

Something important to note: "hidden functionality" like swipe-back can be made optional. You can always straight up have it disabled by default and let it only be discoverable by people who dig into the config (which I'm guessing is a big part of the userbase here, but that's another discussion).

**Comment by dessalines** [comment]
> An example I used A LOT with MessagEase is that you don't have ¿ or ¡ as discreet actions in the spanish layout, they are alternative characters of ? and ! respectively.

The existing spanish layouts already do have those (at least `¿`) as clearly marked actions. That's far preferable than adding the layers of hidden functionality that messageease did. These should be done at the keyboard level, and I'm happy to merge additions to existing ones, or new keyboards that have all the characters you need.

BTW where did thumb-key get linked from? We have a lot of message-ease users all of the sudden.

**Comment by asdkant** [comment]
MessagEase decided to turn subscription-based and a lot of us are scrambling to get a keyboard that will not saw off the floor from under our feet. thumb-key fits the bill but some of the differences BREAK MY BRAIN and I am sure it's the case for other MessagEase users.

Which means you'll get a bunch of people like me who basically want the MessagEase feature set. You'll probably want to add a disclaimer or something to save you the arguments, maybe point them to [my fork](https://github.com/asdkant/open-thumb), or wherever else you think is appropriate.

**Comment by BlueDrink9** [comment]
I independently stumbled across it via [lemmy](https://sh.itjust.works/comment/8466388). i'm very pleased I did! I've made my own half-hearted cracks at a messagease clone over the years.
