### ISSUE TITLE
Change Text Selection

### ISSUE THREAD

**Issue by HawksDarris** [dessalines/thumb-key#352]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
# Current Behavior
Swiping up on the `#` key selects all and copies all.

# Requested Behavior
I would like an option to `select all` without doing a `copy all`.
I do not always want to copy after doing a `select all` action. 

## Alternatively
I wonder if it is possible to make it have a *Selection Mode* where the user can move the cursor while highlighting text. Then typing any character would replace all of the text that had been selected. In other words, basically equivalent to doing a click-and-drag procedure with a mouse on a computer.

**Comment by dessalines** [comment]
Not interested in adding more clutter to the already swamped action key.
