### ISSUE TITLE
TypeSplit with #

### ISSUE THREAD

**Issue by racuna** [dessalines/thumb-key#354]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Hi, I just added the # character in the S key (both lowercase and uppercase), not because it's something of priority, but I could be comfy to type # without changing to the numeric keyboard (e.g. in social media).

Maybe I could be confusing for some, because the key to change to numeric is also a # symbol. I dunno, I'm not an UIX expert.

[TypeSplitESv1.1.zip](https://github.com/dessalines/thumb-key/files/12381207/TypeSplitESv1.1.zip)

**Comment by dessalines** [comment]
Typesplit ES already exists, click on edit on that file.

**Comment by racuna** [comment]
I did it, I hope it worked fine. Thanks.

**Comment by dessalines** [comment]
There don't appear to be any open pull requests, so it didn't work. Go to that keyboard file on github and click the edit button.

**Comment by racuna** [comment]
Sorry, it is the first time I do this.

![imagen](https://github.com/dessalines/thumb-key/assets/3275691/d3c91233-ac4a-4397-8eaa-52115c305321)

I hope now is ok. Thanks
