### ISSUE TITLE
TypeSplitFinv1

### ISSUE THREAD

**Issue by EmGrGit** [dessalines/thumb-key#366]
- [x ] Did you check to see if this issue already exists?
- [x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
Hi, I tried to make TypeSplit keyboard for Finnish language. This is the first time I have ever tried to do this, so I do not know if it is made correctly.
[TypeSplitFINv1.txt](https://github.com/dessalines/thumb-key/files/12441824/TypeSplitFINv1.txt)

**Comment by mockballed** [comment]
Thanks for your contribution!

Is the Finnish layout based on the QWERTY layout?
![finnish_layout](https://github.com/dessalines/thumb-key/assets/8158663/caa7e135-ad64-427a-bf53-dd091c5134ed)
(https://kbdlayout.info/KBDFI)

If so, by "typesplit logic" the 12 center keys should be something like:

> etio
> askl
> cvnm

I'll look into it

**Comment by EmGrGit** [comment]
Hi,
I used this https://en.m.wikipedia.org/wiki/Letter_frequency to look at the most frequent letters used in Finnish, and I put vowels to the right and consonants to the left. I think I read somewhere in the guides that is how it supposed to be made, but I can definitely be wrong on that.
