### ISSUE TITLE
Add release notes popup

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#375]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

I need to add a popup for release notes, that gets marked as viewed after closing. Similar to jerboa.

**Comment by penn5** [comment]
I saw how you're implementing this.
Wouldn't it make more sense to store the most recently viewed changelog in the database, and then display it if the last viewed one is not the most current one?
Otherwise you need a way of detecting upgrades, which in practice is going to result in ugly code.

**Comment by dessalines** [comment]
Good point, that would be a better way to do it... as long as I can get the current version code from within the running code.

**Comment by penn5** [comment]
Use `BuildConfig.VERSION_CODE`
