### ISSUE TITLE
Stop using alorma preferences UI?

### ISSUE THREAD

**Issue by penn5** [dessalines/thumb-key#378]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

The Alorma preferences UI library is not flexible and results in ugly code. For example, it forces you to `remember` all values even though they ought to update directly from Room. It also doesn't support any clean ways of defining the multi-select default state as used in the layout picker (resulting in ugly code like `rememberIntSetSettingState(keyboardLayoutsSetFromTitleIndex(settings?.keyboardLayouts))`)

Removing this would increase the maintainability of the application. Currently I'm trying to add a preference and it's quite difficult due to the ugly code.

**Comment by dessalines** [comment]
What's your alternative to alorma?

**Comment by penn5** [comment]
I would do it all without a library. The current code is inflexible and has a lot of boilerplate (e.g. all the states). Implementing the same thing manually would probably not increase the SLOC, and would certainly reduce the APK size.

Plus, the current way of doing it results in weird behaviour if the database changes while the settings screen is open (all the `remember { mutableXXXState(...)}` result in Compose not updating the states when the DB changes externally. For example, if the keyboard position was shown in the settings menu, this would not update if the keyboard is opened and the change position key activated.

**Comment by penn5** [comment]
Unfortunately I don't have the time to rewrite your settings screen, I'm focusing on the features that will make a difference to real-life usage.

**Comment by dessalines** [comment]
I don't plan to migrate away from using a standardized settings library like alorma. 

> For example, if the keyboard position was shown in the settings menu, this would not update if the keyboard is opened and the change position key activated

I'm sure there's a way to override the alorma remember state, to track the DB directly. If not, we could do PRs to alorma directly.

**Comment by penn5** [comment]
Feel free, but I think it will be more painful that way. Jetpack Compose provides many features that allow easy, customisable preference screens.
