### ISSUE TITLE
Add swipe to keyboard selection

### ISSUE THREAD

**Issue by RiKkzu** [dessalines/thumb-key#379]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I use multiple keyboards. To switch the keyboard, you have to use the system settings, which is long and inconvenient. Please add a swipe function to open the keyboard selection menu, for example: swipe left on the "settings" key. Sorry for my bad English, I'm writing through a translator.

**Comment by dessalines** [comment]
This is done, swipe left on the number key.

**Comment by RiKkzu** [comment]
I apologize for not answering for a long time. The problem is not in changing letters, but in changing the keyboard program. Made 2 screenshots with buttons.
1. Unexpected Keyboard https://github.com/Julow/Unexpected-Keyboard
![Key1](https://github.com/dessalines/thumb-key/assets/132186188/2505004b-5dce-4263-95ed-be748ae13d13)
2. KDE Connect
![Key2](https://github.com/dessalines/thumb-key/assets/132186188/c8c35c0b-3544-4d75-b0cb-c11b7d4e04b6)

Please see how they work, I think it's very convenient.
Maybe this swipe button can be put here
![key3](https://github.com/dessalines/thumb-key/assets/132186188/2e2a5662-e6c3-4b1a-a45d-4e37946e7ba9)

**Comment by dessalines** [comment]
Dupe of #380
