### ISSUE TITLE
Add button to change to other keyboard apps.

### ISSUE THREAD

**Issue by kcryptonian** [dessalines/thumb-key#380]
- [ ] Did you check to see if this issue already exists?
- [ ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I'm tired of having to go to my phone settings everytime because I wanna change back to Gboard when I wanna type a loooong but emergency message coz I haven't gotten naturally used to thumbkey and would delay me alot to type such messages.
Include a "change input method" switch key. Thanks.

**Comment by penn5** [comment]
Dupe of #379?

**Comment by dessalines** [comment]
This is done, swipe left on the number key.

**Comment by penn5** [comment]
I can't see a commit? 😅 
The issue is asking to support changing to other _apps_, not _layouts_

**Comment by dessalines** [comment]
Oh other keyboard apps. Isn't that done through an android dropown from the notif bar?

**Comment by penn5** [comment]
Yep that is possible, but it's more effort than a swipe left :)
