### ISSUE TITLE
Database migrations incorrectly use constants

### ISSUE THREAD

**Issue by penn5** [dessalines/thumb-key#381]
**Thumb-Key Version**
All

**Describe the bug**
The database migration code must not use constants that can be modified between schema versions, as this would change the migration.

**To Reproduce**
Example:
```
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(database: SupportSQLiteDatabase) {
        database.execSQL(
            "alter table AppSettings add column key_borders INTEGER NOT NULL default $DEFAULT_KEY_BORDERS",
        )
    }
}
```
Should be:
```
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(database: SupportSQLiteDatabase) {
        database.execSQL(
            "alter table AppSettings add column key_borders INTEGER NOT NULL default 1",
        )
    }
}
```

**Comment by dessalines** [comment]
I'd rather just have a rule in a code comment, that you can't change these constants without re-creating the DB from scratch.

Other parts of the code use those constants, so I'd like to keep them uniform.

**Comment by penn5** [comment]
That's the whole point. The constants must not be kept uniform. If the constants are kept uniform but modified, the migration will break.

A migration is immutable; it must always remain the same. If you want to copy-paste the constants into the migration, that works. But if a constant is modified, and it is used in a migration, it will change the migration, which is equivalent to breaking the migration.

**Comment by dessalines** [comment]
> If the constants are kept uniform but modified, the migration will break.

This is a **good thing**. It means that someone changed the constant in the code, but forgot to create a new migration to replace that constant. I don't want to have to keep track of two separate defaults.

**Comment by penn5** [comment]
True, but this has a side effect.
Consider schema v1 has default 1. v2 has default 2.
so migration 1->2 changes default from [existing default (1)] to DEFAULT_VALUE (2).
Now we create v3 where default is 3.
Migration v2->v3 changes default from [existing default] to DEFAULT_VALUE, and we set DEFAULT_VALUE to 3.
But the migration named v1->v2 now actually migrates v1->v3, because DEFAULT_VALUE was modified.
If the migration v2->v3 uses this default in any way, it will act in unintended ways. This could include reinserting rows into the database, where the value is set to undefined, or reading when there are no stored settings.
This is a very subtle bug but it is a bug. Please fix it.

**Comment by dessalines** [comment]
This is **not a bug** , it's a code preference of **yours** that you want me to implement. When you make your own keyboard app, you can have control over these things.

**Comment by penn5** [comment]
It's not a code preference, it's defined explicitly in the Room documentation, and will cause bugs in your code.
![image](https://github.com/dessalines/thumb-key/assets/5600962/a2b30fd5-b4d2-4c5d-bdc6-83c97a1c44a5)
https://developer.android.com/training/data-storage/room/migrating-db-versions

**Comment by alerque** [comment]
I'm not familiar with Room or most Android libraries here, but I have some experience with database migrations in other context and I have to say this does look like a bug waiting to manifest someday. In general migrations are very sensitive to ordering. You can't skip straight to a new end point by changing a value later. You need to keep the original migration to a specific value and add a new migration to the updated value. As such using a valuable for a value here does smell like a bug: a hard coded value will make it more apparent that if/when the default does change again a new migration needs to be appended to the chain.
