### ISSUE TITLE
Icons in LookAndFeelActivity should have null contentDescription

### ISSUE THREAD

**Issue by penn5** [dessalines/thumb-key#382]
**Thumb-Key Version**
main branch

**Describe the bug**
```
icon = {
                        Icon(
                            imageVector = Icons.Outlined.Swipe,
                            contentDescription = minSwipeLengthStr,
                        )
                    },
                    title = {
                        Text(minSwipeLengthStr)
                    },
```
A screen reader reading this tree will read the text `minSwipeLengthStr` twice. So the `contentDescription` of the `Icon` should be null, as the same string is already exposed to the accessibility tree by `Text`

**Comment by dessalines** [comment]
That doesn't sound correct... then the icons wouldn't have a meaning.

**Comment by penn5** [comment]
Indeed they don't have a meaning, they are only used visually.

**Comment by dessalines** [comment]
Since all of these have text associated with them, I'll null them out. But I really don't know if that's correct from a a11y perspective. I can revert if there are issues.
