### ISSUE TITLE
Layout suffer from unexpected line break

### ISSUE THREAD

**Issue by Vander567321** [dessalines/thumb-key#397]
**Thumb-Key Version**
1.14

**Describe the bug**
The last settings line 'Animationshelfergeschwindigkeit:###' is to long for the line, forcing a line break.
The layout of the next line (factory reset) is not aware of this and get to close.

**To Reproduce**
1. system setting german, to force the settings language profile
2. may also depend on screen resolution and aspect ratio

To think of an shorter translation I would need to know what exactly is it doing?
Anyway, this would not change the GUI awareness for unexpected line breaks.

**Comment by Vander567321** [comment]
![IMG_20230910_113213](https://github.com/dessalines/thumb-key/assets/144587391/2cc295d3-ca96-4e8c-bbbd-c10c79eb0e2a)

**Comment by dessalines** [comment]
That's as issue you should open up on the settings library we're using: https://github.com/alorma/Compose-Settings
