### ISSUE TITLE
Non square layot

### ISSUE THREAD

**Issue by Vander567321** [dessalines/thumb-key#399]
- [ y] Did you check to see if this issue already exists?
- [ y] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I scale the keys already bigger than default (64->80), still got unused side space and a huge spacebar.
The 3x3 key layout should  stay square, but how about the combined space:enter bar?
would save some space to give it a max px limitation. Independent from what the keyboard layout defines.
Some setting like the bottom distance.

**Comment by dessalines** [comment]
I don't plan on adding non-square *keys*, but feel free to create wider / split layouts, and I'll add them.
