### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [dessalines/thumb-key#400]
[diff.zip](https://github.com/dessalines/thumb-key/files/12568262/diff.zip)

Could you please take a look? Thanks!

**Comment by dessalines** [comment]
We've had this error before, but I've changed nothing about the signing. All I did was upgrade some dependencies. I'm sure it'll resolve itself like before: in a few releases, f-droid will start working again, and I'll still have changed nothing about the signing config.

**Comment by linsui** [comment]
It's not about the signing config. How do you build your apk?

**Comment by dessalines** [comment]
`./gradlew assembleRelease` 

That also hasn't changed, and there's been working and broken f-droid builds before and after that.

**Comment by licaon-kter** [comment]
And again today, fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c5375a76ae39f6f180c1ec15d2977b1138855e0f

difflog: 
[thumb34.log](https://github.com/dessalines/thumb-key/files/12682160/thumb34.log)

**Comment by dessalines** [comment]
What usually causes these?

**Comment by linsui** [comment]
Different jdk versions, Android studio, or cache not cleaned. Which jdk do you use to build your apk?

**Comment by dessalines** [comment]
Uh oh, `./gradlew --version` says I'm using:

`JVM:          17.0.8.1 (Oracle Corporation 17.0.8.1+1)`

Yet my `java --version` is:  

`openjdk 17.0.8.1 2023-08-24`

Maybe these lines are incorrect? https://github.com/dessalines/thumb-key/blob/main/app/build.gradle#L54

**Comment by linsui** [comment]
Maybe the oracle jdk produce different binaries. Those lines are correct.

**Comment by dessalines** [comment]
Okay, it looks like doing [this](https://stackoverflow.com/a/71491506/1655478) is the only true way to figure out what java is being used in the build process. 

I'll try setting my `JAVA_HOME` explicitly to my openjdk version for the next build, and ensuring that it uses it for the process. What a mess.

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/2060e300fb57f492478bd3fe94c309a03b63b71b

**Comment by dessalines** [comment]
Not sure what I should do to fix it. This one was built with openjdk 17 .

**Comment by licaon-kter** [comment]
36 was ok :shrug: https://gitlab.com/fdroid/fdroiddata/-/jobs/5227631297#L635

**Comment by linsui** [comment]
Hmm, insteresting...

**Comment by dessalines** [comment]
I upgraded to gradle 8.3 for that one, not sure what else I did to make that one work.

**Comment by licaon-kter** [comment]
@dessalines not only gradle, also these https://github.com/dessalines/thumb-key/commit/c19472211797c14f2aa2a150ec70734d8a551cc2

**Comment by linsui** [comment]
2.5.2 is reproducible.

**Comment by dessalines** [comment]
*Might have been the upgrade to gradle 8.4* , but I have no idea lol. I apologize for these.

**Comment by licaon-kter** [comment]
reopen https://monitor.f-droid.org/builds/log/com.dessalines.thumbkey/43#site-footer

**Comment by licaon-kter** [comment]
Difflog: 
[thumb43.log](https://github.com/dessalines/thumb-key/files/13319665/thumb43.log)

Local APK: 
[com.dessalines.thumbkey_43.apk.ZIP](https://github.com/dessalines/thumb-key/files/13319667/com.dessalines.thumbkey_43.apk.ZIP) (remove `.ZIP`)

**Comment by linsui** [comment]
2.6.5 failed again. 
[diff.zip](https://github.com/dessalines/thumb-key/files/13826861/diff.zip)

**Comment by dessalines** [comment]
No idea what causes these. This one is even stranger since I update zero gradle deps: https://github.com/dessalines/thumb-key/compare/2.6.4...2.6.5#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/5964721139#L502 fyi

**Comment by licaon-kter** [comment]
at least it's a new error https://gitlab.com/fdroid/fdroiddata/-/jobs/6133897492#L566

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6145358484#L600

`Only in /tmp/tmp2thsd9qi/tmp_binaries_com.dessalines.thumbkey_57.binary/content/assets: RELEASES.md`

**Comment by linsui** [comment]
It's generated with https://github.com/dessalines/thumb-key/blob/main/generate_changelog.sh.

**Comment by dessalines** [comment]
I spose I just need to make sure that one is added to git then. I'll try that for the next release.

**Comment by dessalines** [comment]
Why did `2.6.15` fail? I added the missing file for that one.

**Comment by licaon-kter** [comment]
difflog: 
[thumb58.log](https://github.com/dessalines/thumb-key/files/14311308/thumb58.log)

**Comment by dessalines** [comment]
I'm not sure how to read these, but it says that even things like ArrayList differ.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6197859388

**Comment by licaon-kter** [comment]
I keep building newer versions locally, no success yet.

will rebuild latest asap

**Comment by licaon-kter** [comment]
new difflog: 
[thum65.log](https://github.com/dessalines/thumb-key/files/14459789/thum65.log)

**Comment by licaon-kter** [comment]
one good for now: https://gitlab.com/fdroid/fdroiddata/-/commit/f1f0d948f3fa27085f6e652d405219b27c4fd7ac

**Comment by dessalines** [comment]
Nice. Again I wish I knew what causes these.

**Comment by licaon-kter** [comment]
:shrug: https://gitlab.com/fdroid/fdroiddata/-/commit/8fb6877c1ccca1b1756601972b9674d17a6d243a

**Comment by dessalines** [comment]
It fixed itself and we have no idea why lol. I'll take it.

**Comment by licaon-kter** [comment]
Don't jinx it now :)

**Comment by licaon-kter** [comment]
and :( again https://gitlab.com/fdroid/fdroiddata/-/jobs/6554341767#L547

**Comment by dessalines** [comment]
Not even a dep update with that one 🤷

**Comment by licaon-kter** [comment]
I'am just keeping you ~~annoyed~~informed :)

**Comment by licaon-kter** [comment]
@dessalines pls always build APK from Tagged commit, eg. https://github.com/dessalines/thumb-key/releases/tag/3.1.0 -> https://github.com/dessalines/thumb-key/commit/1abe5ce59dfb9cd52aea5a5c5575259067efbee6

else https://gitlab.com/fdroid/fdroiddata/-/jobs/6702007748#L1257

not to mention that the commit is the one with the right versionCode and Name :(

**Comment by dessalines** [comment]
Oops my bad. I'll reupload another one shortly.

**Comment by dessalines** [comment]
Can re-open in the future when builds break again 😂
