### ISSUE TITLE
holding keys to access the numeric layout

### ISSUE THREAD

**Issue by wuqtas** [dessalines/thumb-key#403]

**Comment by racuna** [comment]
How this will work in the TypeSplit layout?

**Comment by dessalines** [comment]
What does this mean?

**Comment by wuqtas** [comment]
MessagEase has an option to let user hold a key to access its equivalent on the numeric layer... that would be a cool boolean at Settings

**Comment by dessalines** [comment]
Its an explicit choice not to have any tap-and-hold actions. You can create a keyboard tho that adds numbers as swipes.
