### ISSUE TITLE
What's new popup has bad contrast on text

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#409]
**Thumb-Key Version**
1.15.0

**Describe the bug**
What's new popup has bad contrast on text. Screenshot:
![Screenshot_20230915-175704_Thumb-Key](https://github.com/dessalines/thumb-key/assets/21956756/b3781611-a8b8-4cd0-ab52-12ce5a026187)

**To Reproduce**
1. Update the app
2. see popup

**Comment by sslater11** [comment]
It turns out this is only when we have dark theme enabled on our system.

The fix is pretty simple, we can just set the background color to white. In Dialog.kt add to line 67 "containerColor = Color.White,"

```
            AlertDialog(
                containerColor = Color.White,
                text = {
```

**Comment by KraXen72** [comment]
don't set the background color to white, it will look ugly.
rather, set the test color properly, lol.

**Comment by sslater11** [comment]
But it's the easy, lazy way haha.

Okay, figured out how to change the text colour, it's pretty easy, one line.
```
// Change this
MarkdownText(markdownText)
// to this(and add an if statement for checking whether dark theme)
MarkdownText( color = Color.White, linkColor = Color.Magenta, markdown = markdownText)
```
The reason why I thought to change the background, is because the text also has links in it, but turns out it's easy to do.

Hows this?
![dialog_magenta_small](https://github.com/dessalines/thumb-key/assets/43177940/de02be58-aa17-484f-bb72-37de40a41127)

Blue doesn't work.
![dialog_blue_small](https://github.com/dessalines/thumb-key/assets/43177940/26cc21ee-3ed7-4585-ba68-749b6d060a8b)

**Comment by KraXen72** [comment]
Have you tested this in light mode too? shouldn't it use the color that Monet theme generates for text, instead of white? sometimes, dark themes can be pretty low-contrast if they're generated based on a wallpaper, and white might not be the right option.

**Comment by sslater11** [comment]
The light mode will display the same as it does currently, and the dark mode will have these colours we choose.

When I switch from light to dark mode, the colours change properly, which is lovely.

**Comment by KraXen72** [comment]
i think it would be better to use the proper colors provided by the android Monet theming API, but this is good enough i guess. Also, i can't really go complaining about something like this for much longer before you tell me to go implement it myself lol.

**Comment by sslater11** [comment]
I'm looking in to where to get these colours from lol, but at the moment I do have it working nicely.

**Comment by sslater11** [comment]
What about if we use the colours that are already in ThumbKey?
ThumbKey has different coloured themes, how about if we used the text colour from those? Not sure if there's a good second text colour for the links though.

**Comment by sslater11** [comment]
Thanks dessalines, I was wondering what colours would work best. This looks good in light and dark mode :).

**Comment by KraXen72** [comment]
yes, it looks great. thanks!
