### ISSUE TITLE
Acceleration based spacebar swiping

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#410]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
add a new checkbox "swipe acceleration" that takes into account acceleration of the swipe on spacebar. 
- Currently, with a pretty high Slide Sensitivity (38), i can get a pretty good precision on spacebar swipes when i only want to swipe by one letter, but when i want  to skip whole words by swiping quickly, i have to swipe the entire spacebar multiple times. I could lower the Slide Sensitivity, but then it becomes annoying to precisely move by one or two letters.
- With the new checkbox, swiping quickly would move by more letters, but swiping slowly will move by less - allows for fine-grained precision when needed, but also to quickly move the cursor by several words using only one swipe.

**Comment by LenzGr** [comment]
FWIW, I would find this helpful, too.

**Comment by alerque** [comment]
I also agree, I think. I've found the cursor motion a bit harder to get right in thumb-key (having come from MessagEase). I don't know exactly what heuristic ME used, but it was pretty reliable to move 1 character or 1 word. If this is the missing ingredient then I'm all for implementing it here.

**Comment by KraXen72** [comment]
nice!!!!!!!!!!!!!
