### ISSUE TITLE
Settings subheading for spacebar sliding

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#411]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
Currently, all the sliders are grouped together. This can confuse people as 'Minimum Swipe Length' and 'Slide Sensitivity' are pretty similar sounding, but affect completely different things. I'm proposing either dividing the settings more / adding sub headers, or at least group the spacebar sliding settings together.

**Comment by dessalines** [comment]
What would those sub-headings be?

**Comment by KraXen72** [comment]
If i were to re-organize the settings, this is how i would do it:
Categories:  
- Layout - layout list with checkboxes
- Look & Feel
    - Appearance (sub-heading)
        - Theme, Theme color, Position
        - Hide letters, hide symbols
        - Key borders
        - key size, bottom offset sliders
        - animation speed, animation helper speed sliders
    - Feel (sub-heading)
        - Vibrate on tap, play sound on tap
- Behaviour (name subject to change)
    - Auto-capitalize, Spacebar multi-taps, Spacebar sliding cursor
    - minimum swipe length slider
    - slide sensitivity slider
- User Guide
- About
- Reset to defaults button (can be moved into look&feel and/or behaviour)

**Comment by sslater11** [comment]
I've made a PR to group the slider and checkbox together, and to disable the slider when the checkbox is unticked, and to set spacebar cursor sliding to enabled by default.

Whilst testing, I was moving the slide bar, and saw the feature didn't work. Later on I noticed the checkbox wasn't ticked, so the feature was turned off lol.
