### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by knoxydev** [dessalines/thumb-key#42]
button for switching languages

**Comment by dessalines** [comment]
While I'm hestitant to add settings directly into the keyboard rather than on the settings page, this is one I could see being justified. But I don't think other settings should go here, because it could get overly complicated very quickly.

**Comment by knoxydev** [comment]
Will you not add language switcher ? i wanna test your keyboard, but i cannot do it because it has not switcher. Absence of language switcher stop me to test your keyboard.

**Comment by dessalines** [comment]
**Thumbkey already has a language switcher**, its in the settings. Again, I'm not against adding an *additional* language switcher into a 2nd place inside the keyboard.

**Comment by knoxydev** [comment]
it will be great if you add additional language switcher into a 2nd place inside the keyboard. i will wait this possibility)

**Comment by DaviDChereDnik** [comment]
my vote is for the switcher in style of the original MessageEase -- left-right swipe on the right button

**Comment by ilyakooo0** [comment]
How can I help implement this?

**Comment by dessalines** [comment]
There are many potential places to put it. I don't know if a popup from within the ime is possible, but that would be my preferred way of showing the list of all languages.

**Comment by ilyakooo0** [comment]
Maybe it would be possible to offer different languages as separate input methods like the GrapheneOS keyboard does?

![Screenshot_20230322-133245.png](https://user-images.githubusercontent.com/6209627/226992700-568d5dab-62d1-4bcc-a7bd-a33b78da3024.png)

**Comment by Shura0** [comment]
> Maybe it would be possible to offer different languages as separate input methods like the GrapheneOS keyboard does?
> 
> ![Screenshot_20230322-133245.png](https://user-images.githubusercontent.com/6209627/226992700-568d5dab-62d1-4bcc-a7bd-a33b78da3024.png)

It's too slow in use

**Comment by parsarch** [comment]
What about having a settings keyboard like how we have a numeric keyboard? 
For example tapping on the cog brings up a layout showing selected layouts, keyboard alignment etc

**Comment by dessalines** [comment]
It already has a settings button on the top right.

**Comment by Chirikumbrah** [comment]
How about changing languages by swiping up the space button?

**Comment by dessalines** [comment]
The settings button now goes directly to the full size settings page, so I don't think this is necessary anymore. I jast tested it, and you can change keyboards in less than a second. 

Having a custom view just for one setting doesn't seem necessary anymore. 

I'd rather save the keyboard swipes for non-settings related actions.

**Comment by Chirikumbrah** [comment]
> It already has a settings button on the top right.
> 
> Edit: I've made the settings button go directly to the look and feel page, so this will already be a bit faster.

I was also thinking about on option to select only necessary layouts instead of current approach with list where you choosing only one layout.
So then it will be logical to implement a language switcher by swiping space or something else)

**Comment by Chirikumbrah** [comment]
> It already has a settings button on the top right.
> 
> Edit: I've made the settings button go directly to the look and feel page, so this will already be a bit faster.

I was also thinking about on option to select only necessary layouts instead of current approach with list where you choosing only one layout.
So then it will be logical to implement a language switcher by swiping space or something else.
In my opinion it would be much more comfortable)

**Comment by knoxydev** [comment]
I agree with you. language switcher by swiping space is more comfortable and faster)

**Comment by knoxydev** [comment]
I agree with you. language switcher by swiping space is more comfortable and faster)

**Comment by dessalines** [comment]
Swiping space to cycle through every language to get to your correct one would take a really long time. Much slower than just clicking settings and changing your language.

**Comment by dessalines** [comment]
That would require 2 layers / types of defaults.

**Comment by Chirikumbrah** [comment]
What does it mean? Is it bad?

**Comment by dessalines** [comment]
Yes. Lots of unecessary complication. Adding a 2nd setting for a 2nd type of default, adding another table for subselecting these secondary defaults.

All when changing the language already takes less than a second.

**Comment by knoxydev** [comment]
what about adding special button for this action ? For example, you tap button to show special window where i can change language.

**Comment by dessalines** [comment]
Tap the settings button, it goes straight to your settings.

**Comment by ilyakooo0** [comment]
I think the monolingual people don't quite understand how diruptive the current language switching is. It doesn't take less than a second for me. It's more like 3 seconds in total (with exiting out of the settings screen)

The couple of seconds it takes to switch languages right now is _extremely_ disruptive when you need to switch the language three or four times within one sentence. This is more enough for me to loose my thought halfway thorugh writing a message.

I honestly consider this to be a blocker for using this keyboard for multi-lingual people.

**Comment by dessalines** [comment]
Understood, those are very good points. 

I'll have to refactor the settings table to allow multiple defaults. Also I'll go with something close to the messageease standard of swiping left on either the settings or the numeric button, with an indicator of the current language code if you have more than one default selected.

**Comment by EymirKing** [comment]
ayo klk manin, esta bastante wapo esto no? AYO?Esto esta wapisimo hermano

**Comment by dessalines** [comment]
Swipe left on the number key to switch languages. This info is also in the readme.
