### ISSUE TITLE
Haptic feedback does not work

### ISSUE THREAD

**Issue by LenzGr** [dessalines/thumb-key#420]
**Thumb-Key Version**
2.0.0 (installed from GitHub)

**Describe the bug**
Even though the haptic feedback option is enabled in the settings, there's no haptic feedback. This happens on a OnePlus 7T, running OxygenOS 12.1 (Android12). 

**To Reproduce**
1. Ensure that haptic feedback is enabled in the settings. 
2. Type some text.
3. Observe that no haptic feedback is provided.

**Comment by dessalines** [comment]
Its an android system issue, go to your android settings -> vibration and haptic strength -> touch feedback ON

**Comment by alerque** [comment]
It might be worth adding a comment under this setting that it must also be enabled in the system settings. This isn't the fault of this app but it is a common point of confusion with apps that have their own haptic settings.

**Comment by dessalines** [comment]
I'm not sure of a less verbose way to say that for the setting.

**Comment by LenzGr** [comment]
I wonder if there is an alternative way to generate this haptic feedback even if touch feedback is disabled?
The Android [Game Vector Pinball](https://github.com/dozingcat/Vector-Pinball) is capable of triggering short vibration events even when the setting is off.

**Comment by alerque** [comment]
I'm sure there is. Personally I would prefer it respect the global default so that I can toggle them system-wide from a tile and/or notification profile. I don't appreciate it when apps don't respect the system settings and do their own thing.

**Comment by LenzGr** [comment]
> I'm sure there is. Personally I would prefer it respect the global default so that I can toggle them system-wide from a tile and/or notification profile. I don't appreciate it when apps don't respect the system settings and do their own thing.

Well, then this option should be removed, as it does exactly that, doesn't it?

**Comment by alerque** [comment]
No. This option allows the ability to not have feedback for the keyboard even if the system level general feedback option is on.

**Comment by dessalines** [comment]
> Vibrate on tap
(requires touch feedback to be enabled in system settings)

@alerque This seems like the best solution to me.
