### ISSUE TITLE
[small nitpick] have emoji keys respect vibrate on tap setting

### ISSUE THREAD

**Issue by jeremiah-miller** [dessalines/thumb-key#421]
**Thumb-Key Version**
2.0.0.

**Describe the bug**
The emoji keys don't vibrate when you tap them like the regular ones do. Just a super small issue, the emojis are a game changer for me, I'm really excited to finally try thumb-key for real! 😁

**Comment by dessalines** [comment]
I don't think there's a way for us to do that, since its a completely separate android keyboard view we have little control over.
