### ISSUE TITLE
missing key borders in emoji view

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#422]
**Thumb-Key Version**
2.0.0

**Describe the bug**
missing borders. see screenshots:
normal keyboard:
![Screenshot_20230919-092039_Keep Notes.png](https://github.com/dessalines/thumb-key/assets/21956756/1333890a-d1a4-404a-9ebb-ab01d3ce4090)

emoji view:
![Screenshot_20230919-092025_Keep Notes.png](https://github.com/dessalines/thumb-key/assets/21956756/3e3d0053-bd96-4df2-bd1f-4c2589b9077a)

**To Reproduce**
1. Go to emoji view
2. Make use of ocular apparatus (see)

**Comment by dessalines** [comment]
Which borders are missing? We can't change how android lays out its emoji view.

**Comment by sslater11** [comment]
If you look at your screenshot, you'll see the borders were displaying, but they were black.

I've added the fix it to a PR. It looks like this now. There's not a white border around the keyboard its self though.
![emoji_borders](https://github.com/dessalines/thumb-key/assets/43177940/fbcd6683-6dac-495a-9440-7011167f6b98)

**Comment by KraXen72** [comment]
> Which borders are missing? We can't change how android lays out its emoji view.
  
I mean the borders around the abc, symbols, backspace and enter keys are missing (see my screenshots)

> I've added the fix for this in PR https://github.com/dessalines/thumb-key/pull/426
thanks for the pr! hopefully it fixes what i meant.

also,
why do you have the category titles and i don't have them?
also, why are yours black (the contrast's pretty bad)?

**Comment by sslater11** [comment]
I have no idea why you don't have the category titles and I do. I know the font colours on mine are rubbish, I've tried to change the colour, but I can't figure out how. It's funny, because the emoji picker has a .setBackground() method, but no .setForeground(). There's a .foreground value that I can change, but that draws a colour over the whole keyboard, blacking it out haha.
