### ISSUE TITLE
Should autocapitalize "I" be optional? 

### ISSUE THREAD

**Issue by storvik** [dessalines/thumb-key#429]
Not completely sure I this should be classified as a bug or feature request, and I'm pretty sure I have read a discussion about it before, but couldn't find it. 

When typing other languages than English autocapitalize "i" isn't necessarily right. Not sure how to solve this though. Atm I'm using my own fork with [this line](https://github.com/dessalines/thumb-key/blob/19eb6871bd26fc263a60acb75776d4dac622ef10/app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt#L454) removed. 

One idea is to make it possible to enable / disable autocapitalize functions on a per layout basis. For instance I'm using Norwegian layout and whenever that's enabled I can say for certain that "i" shouldn't be capitalized. In Norwegian "i" means "in", and is frequently used. 

I was going to look into this myself, but as there's no apparent solution to this I figured it should be discussed before doing anything.

**Comment by alerque** [comment]
Yes, anything to do with capitalization, punctuation, and auto-correction in general is definitely language specific. I'm not quite sure on the best intersection of layout, language, and preference settings though ... there is a lot of overlap. One layout may be used for 2 or more languages and 1 language may also have more than one layout. Preferences may hold true for some/most combinations but not all.

**Comment by dessalines** [comment]
I would very much be in favor of making an optional autocapitalize config for each keyboard (obvi different keyboards could import that same config, rather than copy-pasting).

**Comment by fuxoft** [comment]
I very much second this. In Czech language, the word "i" means "also" and should not be capitalized. This is a very frequent word and, as a result, the default auto-capitalization is very annoying when writing Czech.
