### ISSUE TITLE
FR for type-split english

### ISSUE THREAD

**Issue by Docbroke** [dessalines/thumb-key#433]
In current layout some of the keys require sliding thumb inward, e.g., q and z for left thumb, and j for right thumb.
My suggestion is to change this characters location so that thumb is moved outward. In my view we should place all characters in positions that require only  downward and outward movement of thumb.

**Comment by racuna** [comment]
When the "key" is on the outer edge of the keyboard, and the keyboard is not centered. It is more difficult to slide outward than inward in cases where the phone has a protruding physical edge (rugged phones, or protective cases).

Use case: have the keyboard aligned to the right (right-handed typing with the right thumb only). On the assumption that the J would be shifted to the right on the "key" L. Trying to make the slide out, if the thumb collides with the physical edge of the phone it is more likely that the letter that appears will be the L and not the J. 

Source: I have had this happen to me several times with the "?" symbol on the "M" key.

**Comment by Docbroke** [comment]
1. Just to make sure that you have not misunderstood my suggestion. I am specifically talking about type-split keyboard, where one uses both thumbs. Left thumb for (e,t,a,s,c,b) and right thumb for (i,o,h,l,n,m). With this setup there is no question of typing with only right thumb, or keyboard aligned to right.

I agree with you in limited use cases of rugged phone or protective cases, but that can be mitigated by reducing keyboard size few millimeters. What my point is, for thumbs outward and downward movements are more natural. In may case I have to use extra focus when sliding inwards otherwise I mistype the character.

**Comment by racunaATneuronet** [comment]
>  type-split keyboard, where one uses both thumbs

I understood. But you talk like TypeSplit can't be used with just one Thumb? 

The keyboard can easily moved to the center when using both thumbs, or to the right/left when using just one thumb. No need to change the entire layout with totally different letter distribution. 

> or keyboard aligned to right

Why not? Is more efficient using the same layout always and just change the alignment.

**Comment by dessalines** [comment]
I just want to note, that I will add anyone's keyboard, and variants of them, and this is partially the reason for the `v1`, `v2`, etc. So yall could create 10 different typesplit variants if you want (even if you're the only one using them), and I'll add them.

**Comment by Docbroke** [comment]
> I understood. But you talk like TypeSplit can't be used with just one Thumb?
It can be, but I think it kills the purpose of creating split keyboard. 
It is like using full sized qwerty keyboard with two index fingers only. I can't argue here, as there are more people using full sized keyboard with two index finger compared to people doing touch typing with all fingers.

> I just want to note, that I will add anyone's keyboard, and variants of them, and this is partially the reason for the `v1`, `v2`, etc. So yall could create 10 different typesplit variants if you want (even if you're the only one using them), and I'll add them.

thanks, I will try creating one. It will be cool to have personalized layout.

**Comment by Docbroke** [comment]
I just realized while looking at the code of type-split, even though characters j/q/z are on inner side swiping outward also types the same character, the character are not displayed on the keyboard but they are there in the code.

This solves my issue, so I am closing this.
