### ISSUE TITLE
French MessagEase layout is missing "secondary" symbols

### ISSUE THREAD

**Issue by pulkomandy** [dessalines/thumb-key#434]
**Thumb-Key Version**
1.13.0

**Describe the bug**
The MessagEase French layout is missing several symbols.

Here is a screenshot of the MessagEase French layout in the MessagEase app:

![image](https://github.com/dessalines/thumb-key/assets/2964297/5af2655f-c471-4097-8afb-4ac1f8a8ece0)

The layout in ThumbKey is missing all the dark grey symbols except on E and S (and S is incomplete)

On the "numbers" keyboard I think some are placed differently:

![image](https://github.com/dessalines/thumb-key/assets/2964297/60b681a0-6c93-497f-849d-849ed717f429)

- '-' should be on 1-right instead of 8-downright
- < and > should be on 7-left and 9-right instead of 7-downleft and 9-downright
- * should be on 7-right instead of 8-downleft
- , should be on 8 downleft instead of 8-left
- : should be on 8-downright instead of 7-downright

**To Reproduce**

Configure ThumbKey with MessagEase French layout and try to type an ! or one of the other missing symbols

(by the way, thanks for writing a MessagEase replacement! It will be very helpful to me and I'm happier using free software!)

**Comment by dessalines** [comment]
@pulkomandy You can go to [this file](https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/MessageEaseFR.kt), click edit, and make the changes necessary.
