### ISSUE TITLE
Any way to manually capitalize letters?

### ISSUE THREAD

**Issue by NastyFlytrap** [dessalines/thumb-key#436]
- [ ] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

**Describe the feature request below**
It'd be neat if i could capitalize letters manually, because if i have to delete the auto capitalized letter then i'll need to exit the textbox to try again

**Comment by Docbroke** [comment]
You can turn "Auto-Capitalize" off from settings.

**Comment by alerque** [comment]
Slide up on the rightmost letter key in the middle row (next to the number button). Once to capitalize, two swipes to move to caps lock, or slide down to lowercase.

**Comment by NastyFlytrap** [comment]
> You can turn "Auto-Capitalize" off from settings.
Yea but thats not my issue. The issue is that i dont know if/how i can capitalize letters manually


> Slide up on the rightmost letter key in the middle row (next to the number button). Once to capitalize, two swipes to move to caps lock, or slide down to lowercase.
This is the kind of answer i was looking for, thanks!
