### ISSUE TITLE
Ability to hold backspace to delete continously

### ISSUE THREAD

**Issue by NastyFlytrap** [dessalines/thumb-key#437]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

**Describe the feature request below**
This is holding thumbkey back severely. Having to tap so many times to delete most of a long URL sucks

**Comment by KraXen72** [comment]
duplicate of #48

**Comment by KraXen72** [comment]
also, if you enable swipe gestures, you can swipe on delete to delete parts of a word/url

**Comment by dessalines** [comment]
Dupe of #48
