### ISSUE TITLE
Add interpunct to French layout

### ISSUE THREAD

**Issue by SuperMeepBoy** [dessalines/thumb-key#440]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.

**Describe the feature request below**

French inclusive writing requires a lot of interpunct (the following symbol: ·).
I couldn't find it on the French keyboard layout and it's a big problem for me.

Do you think it is possible to add it ? If that is important, in inclusive writing, we use it a lot, along with letters so it must be accessible. On classic keyboard it is hard to get as we must go to special characters evrytime we need it...

**Comment by dessalines** [comment]
You can add it to that keyboard by clicking edit.

**Comment by SuperMeepBoy** [comment]
Where is that edit button you are talking about ? Also, ls there a way to add emojis ?

**Comment by dessalines** [comment]
Watch a video on how to contribute on github. We already have emojis.

**Comment by SuperMeepBoy** [comment]
Just realised F-Droid version is not correct. I know about Github, I'm a dev. 😉

**Comment by SuperMeepBoy** [comment]
Just an issue with F-Droid not having the correct version. Closing the issue.
