### ISSUE TITLE
Auto-repeat on keys

### ISSUE THREAD

**Issue by hydrargyrum** [dessalines/thumb-key#441]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

When I want to remove multiple characters, most keyboards allow me to stay pressing the "backspace" key until I want to stop erasing characters. In thumb-key though, I have to mash backspace many times, which is a pain. Letting backspace having auto-repeat would be great!

On the same issue, after searching the bugtracker, I found that spacebar can be used to move the cursor, great (but I shouldn't resort to the bugtracker). However, it moves only one character. If I keep pressing spacebar, I want the cursor to continue moving until I stop holding spacebar. Auto-repeat again.

**Comment by dessalines** [comment]
Newest versions of thumbkey have a `slide` setting that you can turn on and test out. Check the readme for how to use it.
