### ISSUE TITLE
Backspace up gesture

### ISSUE THREAD

**Issue by Ingegneus** [dessalines/thumb-key#442]
hey everyone
I think it would be very convenient to be able to swipe up on the backspace button, to move the selection cursor up. So combined with the current left swipe to delete, it would be very convenient and intuitive to delete larger blocks of text

**Comment by dessalines** [comment]
The spacebar / backspace slide delete serves this far better.

**Comment by Ingegneus** [comment]
idk if I conveyed my feature request properly. I'll give it another shot just in case:
I would like to have an addition to the current backspace slide (left and right to delete), where you can swipe up and down to delete everything in between your current cursor position and the new cursor position on a different line (much like on a windows pc when pressing SHIFT + UP/DOWN and right after that pressing BACKSPACE)
![image](https://github.com/dessalines/thumb-key/assets/78076361/88569dcd-c7dc-4411-8bb9-724a7f3b4fc6)
![image](https://github.com/dessalines/thumb-key/assets/78076361/f7116e80-baa1-4901-bcd1-0bf248be3712)


If you already understood what I meant then ignore this, if not then I would ask you to reopen this issue.
