### ISSUE TITLE
Can't theme the background colour.

### ISSUE THREAD

**Issue by WadeWT** [dessalines/thumb-key#443]
**Thumb-Key Version**
2.1.0

**Describe the bug**
The non keyboard area of the keyboard is always grey.  I have tried changing all of the colours in Color.kt but the sides of the keyboard will always be grey.  For proper theming support this colour should be able to be changed.  I tried myself but don't really know what's causing it.

**Comment by dessalines** [comment]
Could you circle / highlight which area this is? I can't really tell.

**Comment by WadeWT** [comment]
![Screenshot_20230928-050240](https://github.com/dessalines/thumb-key/assets/7088087/bcf975f9-a81e-4a18-8b97-2206f0275620)

These areas.

**Comment by dessalines** [comment]
We can't theme that unfortunately, its based on the application's background. If you have a launcher or some other app that uses transparency, you'll see that thumb-key *only takes up as much space as it shows*.

**Comment by WadeWT** [comment]
Ahh, I see. Perhaps an option for it to extend the full width of the device with some themeable element would be nice.

**Comment by WadeWT** [comment]
#464
