### ISSUE TITLE
'emojii swipe right' should toggle between positions

### ISSUE THREAD

**Issue by flauta** [dessalines/thumb-key#444]
With keyboard on the left, "swipe right on emojii icon" moves the keyboard from left to center, then from center to right; at this point it's not possible to move the keyboard with swipe anymore.

**Comment by dessalines** [comment]
I don't understand this one. It toggles between the 3 positions, left, center, and right. Just keep doing it.

**Comment by flauta** [comment]
sorry, maybe 'toggle' wasn't the right word: I was meaning 'circling' between the 3 positions. 
As I wrote, when the keyboard is in the 'Right' position, user must use Settings to move it back to Left or Center:  
IMHO the right-swipe should always work, taking the keyboard from the Right back to Left, then Center and so on - as if the 3 positions were in a circle.

**Comment by dessalines** [comment]
It does circle between the three positions. What version are you on, and post a video of the behavior.

**Comment by flauta** [comment]
updated this morning to 2.1.1  - nothing has changed

https://cloud.disroot.org/s/iCQP3rBnMR3YfpT

**Comment by dessalines** [comment]
You are swiping off the screen, into your computer so its losing that info, you need to stay on the button. 

Also why is there a mouse on your screen? You should be testing this from android.

**Comment by flauta** [comment]
I can't record the phone screen from the phone, so I was using scrcpy/OBS but the screen recording IS my Android phone (connected via USB) and the mouse arrow is the same as swiping with the finger on the screen. 
When the keyboard is in the Right position there's no room to swipe right on the phone, but on scrcpy the arrow goes outside.

Sorry, I don't want to waste your time. If the function works for you, that's fine. It's not an important feature after all, since from Settings can always be altered. Thanks for your work.
