### ISSUE TITLE
No layout swap button

### ISSUE THREAD

**Issue by DobriniaMerk** [dessalines/thumb-key#446]
**Thumb-Key Version**
2.1.0

**Describe the bug**
Layout change action is absent in a Wide Layout English Programmer.

I maybe will try to fix this tomorrow.

**Comment by dessalines** [comment]
Layout swap is on the emoji key now, why would it need to be added to a specific keyboard?

**Comment by dessalines** [comment]
Ohh I see it doesn't have that key. Ya feel free to add the emoji key to that keyboard.

**Comment by dessalines** [comment]
Closed by #448
