### ISSUE TITLE
pipeline broken for lint check

### ISSUE THREAD

**Issue by thedroppedpocket** [dessalines/thumb-key#450]
the pipeline for lint check keep failing with "network wp_01hbeazmxd7pygejervkk3nsh4_0_default not found" or similar issues on each PR. I had two failures for network issues on my PR and the current open PR has an identical lint check network failure. I don't understand how these pipelines work.

**Comment by dessalines** [comment]
Its not your fault, its gotta be an issue with those CI runners. We'd have to search for those errors to figure out what's going on.

**Comment by dessalines** [comment]
Seems fixed now since I tweaked the memory.
