### ISSUE TITLE
integrated keyboard editor

### ISSUE THREAD

**Issue by Ingegneus** [dessalines/thumb-key#455]
- [x ] Did you check to see if this issue already exists?
- [x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey
I would very much like to edit a few of the keyboards that are available, without having to request an entirely new layout, just to tweak the position or selection of a few characters. also it would only clutter the already ample list of keyboards.
so would it be possible to make a copy of an existing layout and modifying that?

**Comment by dessalines** [comment]
Yes that is the case. Keyboard *editing* must be done on strictly-typed kotlin files, and I don't plan on building any type of "in-keyboard" editing, or importing of non-compile-checked keyboards. You can see the few closed issues as to the rationale for that.

That said, I will merge anyone's custom layout, so if there's a multi-language layout with specific keys and symbols that suit your needs, I won't hesitate to merge it.

> also it would only clutter the already ample list of keyboards.

Don't worry about that one, android will handle a long list just fine.

> I could submit that mixed English/Turkish. but there are also quite a number of customizations I've made to symbols that other people just aren't going to want. 

That isn't an issue, many people have submitted keyboards that likely only they use (but who knows, if you find it useful, there's a good chance others would too).

**Comment by Ingegneus** [comment]
> Don't worry about that one, android will handle a long list just fine.

I didn't mean the technical aspect of cluttering, but more from usability point of view. 

> You can see the few closed issues as to the rationale for that.

I couldn't find anything decisive, but that might be that I didn't look well enough.#

> importing of non-compile-checked keyboards

this is the one baffling me the most. I understand that other in-app editing features are probably a lot of work, but this one doesn't seem too hard and would make it easier to test out new layouts. like I don't know if my layout is going to be better or not and I would have to wait until a new version is published to try my new layout. one could argue that I could compile the app myself and all that, but honestly I have no idea how to do that. also having to edit the kotlin files directly isn't really accessible to the less tech savvy.

having said all that I know nobody can make any demands of you since you are doing this in your free time and for that I'm very grateful! I just think that making this more accessible would help the project grow its user base and therefore maybe bring more skilled ppl on board
