### ISSUE TITLE
export/import settings

### ISSUE THREAD

**Issue by Ingegneus** [dessalines/thumb-key#456]
- [x ] Did you check to see if this issue already exists?
- [x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I would like to be able to import and export my config, to share with other ppl and to back it up. also this would be very useful if #455 gets implemented

**Comment by dessalines** [comment]
This wouldn't be too difficult, as there is nothing stored outside the SQL DB. A SQL import / export could be taken from other projects and implemented here.

**Comment by Torpedro1978** [comment]
I would need this feature to!
I like to use it on all my other devices like i did with massagease
