### ISSUE TITLE
IT keyboard - new version

### ISSUE THREAD

**Issue by flauta** [dessalines/thumb-key#466]
I submit you a new version of the Italian keyboard. 

I moved the 'c' letter swapping it with 'à'. C was the only common letter in the italian alphabet that was placed in a corner position, requiring a diagonal move.

I added the two symbols ə and ɜ (schwa and reversed-e) that today some people use to avoid male-or-female desinence in words.

Sorry I'm not using the pull request since I don't know exactly which and where modify files, to take off V1 and put V2 keyboard in. Maybe you will want to keep both.

Thanks for your work

[ThumbKeyITv2_schwa.kt.zip](https://github.com/dessalines/thumb-key/files/12837413/ThumbKeyITv2_schwa.kt.zip)

**Comment by dessalines** [comment]
Should this be a new keyboard, or just an edit of the existing one?

**Comment by flauta** [comment]
> Should this be a new keyboard, or just an edit of the existing one?

I leave to you the choice: after all I moved only a letter and added 2 symbols. 

And as you were saying in https://github.com/dessalines/thumb-key/issues/455 I'm probably the only one user of this italian keyboard B-)

**Comment by dessalines** [comment]
In that case you can edit the keyboard directly, here it is: https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyITv1.kt

**Comment by dessalines** [comment]
I can re-open should you decide to add this.

**Comment by flauta** [comment]
Thanks, I'm actually working on the IT-split keymap.
