### ISSUE TITLE
Voice input engine select

### ISSUE THREAD

**Issue by AeliusSaionji** [dessalines/thumb-key#468]
This IME option exists: https://play.google.com/store/apps/details?id=org.futo.voiceinput

Also, this uses the voice input API rather than being an IME https://github.com/ewheelerinc/LocalSTT

**Comment by dessalines** [comment]
This already works using futo, I'm using it right now.

**Comment by AeliusSaionji** [comment]
only after you disable your other voice input keyboards.

There is no selection. Thumbkey just defaults to one.

**Comment by AeliusSaionji** [comment]
There is still the question of the formal API. As noted here:

> LocalSTT should work with all keyboards and applications implementing speech recognition through the RECOGNIZE_SPEECH intent or Android's SpeechRecognizer class.

Not a pressing matter to me at the moment though.
