### ISSUE TITLE
Copy function like MessageEase

### ISSUE THREAD

**Issue by AeliusSaionji** [dessalines/thumb-key#469]
With ME, if nothing is selected, "copy" performs a select-all then copy.

Currently thumbkey's implementation does nothing in this scenario.

Thanks!

**Comment by KraXen72** [comment]
this would be great! thumb key used to have a select all & copy combo key, but it was split into two. this would be the best of both worlds imo.

**Comment by sslater11** [comment]
I can implement this, it's pretty easy to do, but I wonder if anyone would remember it? It seems like maybe a hidden feature that you either know, or you don't, so probably only us 3 would use it :laughing:.

**Comment by dessalines** [comment]
Thx! @sslater11 in the future tho, use a feature-specific branch off of main. I know its sometimes more work but it makes the git history a lot more feature-specific, esp when we squash and merge these.

**Comment by sslater11** [comment]
Ah yes, that makes a lot of sense. Sorry, I was trying to lessen the PRs for you, but I do see how this could have been it's own PR since it's a pretty simple feature to implement.

**Comment by sslater11** [comment]
@dessalines Please close this as it was included in my PR and now completed.

Thanks for the great idea, I use this feature all the time! It's been so handy to cut all the text that I was texting to someone, then write a new response, whilst keeping the previous one to finish writing in a moment.
