### ISSUE TITLE
High contrast version of keyboards

### ISSUE THREAD

**Issue by IndivContrib** [dessalines/thumb-key#477]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I struggle a bit with my vision capabilities and therefore set my mobile to high contrast and bold text. That works fine with the thumb-key keyboard. Except the "function buttons" which are slightly shaded. Their contrast is at the limit for me.
Could you provide an optional "high contrast setting" which shows every key including the function keys and all the little ones in the corners as just black and white?
That would be of great help.

**Comment by WadeWT** [comment]
This is a great idea, I'd be happy to make a high contrast theme.

**Comment by WadeWT** [comment]
#478 

I did two!  would love some feedback as to how well these work for you
