### ISSUE TITLE
emoji view changes keyboard height

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#483]
**Thumb-Key Version**
2.3.0

**Describe the bug**
with the new key border setting, the emoji picker's built-in border makes the kebyboard taller than in any of the other layers. you can even see it on key border:1
this makes the keyboard jump up and down when going from and to emoji picker, which is annoying

**To Reproduce**
1. with key border enabled, go to emoji picker & see

**Comment by dessalines** [comment]
Looks like this bug got introduced with #473 . @WadeWT could you take a look?
