### ISSUE TITLE
Customizable right swipe on emoji key

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#494]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I would like to request a dropdown select setting for the right-swipe action on the emoji key. Instead of hard-coding it to the move keyboard action, which i barely use, allow us to select from a few pre-determined actions:
- Move keyboard (current)
- Previous language cycle (would cycle in the opposite direction; useful if user has more than 2 layouts, to cycle back & forth)
- Toggle hide letters
- Toggle auto-capitalize (should show popup message like when switching keyboard)
- Toggle spacebar multi-taps (should show popup message)
- **optional ones, if you want to:**
  - Toggle slide gestures (should show popup message)
  - Toggle hide symbols
  
 I thinks this is a good amount of customizability while not implementing full layout customization. and i feel like that key is the least used, atleast for me. Users which do use it can just keep the move keyboard action.

**Comment by dessalines** [comment]
This isn't anything I'd want to support. Only the most used settings, statically picked, should be on that emoji key. For everything else, it's really not too much work to just change a setting.
