### ISSUE TITLE
Emoji picker does not respect key border setting

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#496]
**Thumb-Key Version**
2.4.0

**Describe the bug**
In this version, the bug with too thick of a border was fixed, but now there's no border at all.
please make it so that the Box that houses the emoji picker view also gets the same border as a key would.

**To Reproduce**
1. Go to Emoji Picker
2. See

**Comment by WadeWT** [comment]
Working on this now.

**Comment by WadeWT** [comment]
#515 should have fixed this.
