### ISSUE TITLE
Pressing space after a character while editing a block of text converts that character to a comma

### ISSUE THREAD

**Issue by jeremiah-miller** [dessalines/thumb-key#499]
**Thumb-Key Version**
2.4.0

**Describe the bug**
I sometimes make typos or want to rephrase things, and often when I go back and want to add text in the middle of something I wrote. Sometimes i'll move the cursor by tappin,  where I want the cursor to go, press space to start typing a new word, and then the letter to the left of the cursor gets converted to a comma, as if i'd double tapped the space bar.

**To Reproduce**
1. type some text, about a paragraph (it worked in the paragraph above, see "tappin,  ")
2. tap in the middle of the text such that the cursor is in between the end of a word and a space
3. press the space button
4. the last letter of the word should have been converted to a comma, with two spaces after it

**Comment by KraXen72** [comment]
this is being tracked in #242, however, nice explanation!

**Comment by jeremiah-miller** [comment]
Oh nice, I looked to see if the issue existed but missed that. Thanks!
