### ISSUE TITLE
Auto capitalize "I'm" and "I'd"

### ISSUE THREAD

**Issue by jeremiah-miller** [dessalines/thumb-key#500]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
Currently thumbkey will auto-capitalize "i " to "I ". It would be nice if it was the same for i'm and i'd.

**Comment by jeremiah-miller** [comment]
Not at my computer otherwise i'd make a pull request, but could just add

```
else if (textBefore == " i\'") {
            ime.currentInputConnection.deleteSurroundingText(2, 0)
            ime.currentInputConnection.commitText(
                "I\'",
                1,
            )
```

**Comment by Kommynct** [comment]
you should close this
