### ISSUE TITLE
"Hide symbols" shouldn't hide numbers

### ISSUE THREAD

**Issue by nullbasis** [dessalines/thumb-key#501]
- [ X ] Did you check to see if this issue already exists?
- [ X ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Hiding symbols to keep the keyboard nice and tidy also hides numbers on the numberpad. I mean, I know where all the numbers are so it's not critical, but it seems odd.

**Comment by dessalines** [comment]
Doesn't seem preferred, since numbers aren't symbols. Can re-open should you want to work on adding another hide number setting.

**Comment by nullbasis** [comment]
I'm confused. I wasn't suggesting to hide numbers, I was suggesting to *stop* hiding numbers since, as you say, they aren't symbols.

**Comment by dessalines** [comment]
:eyes: Oops, my bad.

**Comment by cepdizei** [comment]
@dessalines wouldn't a "hide numbers" option be nice to have tho? especially since there are a couple of layouts that have numbers on the main page and it's kinda weird to have everything hidden except for numbers

**Comment by dessalines** [comment]
You can add this feature if you want it. The above person who I fixed it for clearly didn't.
