### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by Kommynct** [dessalines/thumb-key#505]
I'd like to be able to pick the hex values for all of the colors in the app, there aren't that many and and this would allow me to set an oled background, which would be very nice.

**Comment by dessalines** [comment]
Check the theming guide in the README. Run-time picked non-material_v3 colors is not anything I want to support, but you can add themes following the instructions in the readme.

**Comment by Kommynct** [comment]
As a samsung phone user, material v3 themes are extremely limited and conflict with other theming options, because I use a custom theme engine material v3 themes always appear as the default colors, and this cannot be changed without messing up the themes in the apps that support Hex, as a result, i'm left unable to actually change the colors beyond the predefined ones, furthermore this seems needlessly complex for custom theming when there's only 4 colors in the app.

Is there any particular reason you don't want to support this? Code complexity? Furthermore, this would also be good for backwards compatibility, there are many phones that don't support material v3 or even v2 that will never be able to theme properly without this. Please reconsider.

**Comment by KraXen72** [comment]
adding a custom theme should be pretty easy tbh

**Comment by Kommynct** [comment]
And another reason to just add the custom colors is bloat, right now, look at the list of layouts, there's an absurd number of them, the same thing could happen to custom colors as people want their custom colors added to the app, this would be much simpler and streamline the process meaning you won't end up with needless pull requests just for colors.

**Comment by dessalines** [comment]
Ah sry, Ya the theming guide is on jerboa, I'll make an issue to add that here.

I'll re-open this issue if someone decides to work on it, but I don't plan to.
