### ISSUE TITLE
Missing letter in russian layout

### ISSUE THREAD

**Issue by DobriniaMerk** [dessalines/thumb-key#51]
In the middle button there are two 'г' letters but no 'к' letter anywhere.

**Comment by urmomseksy** [comment]
29

**Comment by dessalines** [comment]
Now that the keyboard file is added, please do a PR / edit to the file directly: 

https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyRUv1.kt
