### ISSUE TITLE
Separate colors for right hand icons and secondary colors

### ISSUE THREAD

**Issue by Kommynct** [dessalines/thumb-key#510]
![image](https://github.com/dessalines/thumb-key/assets/13646790/e6b16b5f-9059-4384-8d55-b37cbb4279f7)

Right now there's no way to make the emoji button and arrows a different color than the small legends, it would be nice for my theme if that could be white as well

**Comment by WadeWT** [comment]
There's a few other small things that share colours or are difficult to change as well, such as the swipes on the secondary keys always being a 50% opacity version of the legend colour.  I'd be interested in changing some of these things, but am unsure of the best way to go about it, and I'd want to be pretty certain of what I'm doing as it would likely require fixing all the existing themes, too.

**Comment by dessalines** [comment]
I'm fine with any changes, as long as they use Material v3 colors, and not hardcoded colors. There's really on primary, secondary, tertiary, and neutral: https://m3.material.io/styles/color/the-color-system/key-colors-tones

**Comment by dessalines** [comment]
Will re-open should someone want to work on this.
