### ISSUE TITLE
Ability to type symbols in the gaps in the letter mode

### ISSUE THREAD

**Issue by Eletroboss** [dessalines/thumb-key#529]
In MessagEase, one could type symbols on the letter page without needing to press the symbol button so long as it didn't have a letter replacing it. This behaviour would be useful, especially for brackets.

**Comment by dessalines** [comment]
There are alternate symbol-specific layouts for those. They won't be added globally because every keyboard is different.

**Comment by Eletroboss** [comment]
I think this would be much better if it were an option one could opt into globally rather than having 2^n keyboards for each language where n is the number of features. E.g. English with number long press, compose accents, and type symbols would be one of 8 (2^3) keyboards. As features grow this number would grow exponentially and this would be unwieldly tothe user, whereas three checkboxes wouldn't.
