### ISSUE TITLE
Ability to type accents

### ISSUE THREAD

**Issue by Eletroboss** [dessalines/thumb-key#530]
In MessagEase, one could type accents by typing its combined character after - e.g. a + ` would yield à. This does not seem to occur in ThumbKey, but maybe that's a bug? If so, please relabel this accordingly. It would be very useful to language learners like me who only use their other languages occasionally but need a way to type accents without having to learn an entire other layout or use a separate keyboard.

**Comment by dessalines** [comment]
This exists on the english thumbkey composed keyboard. Otherwise tho, its best to switch between languages.
