### ISSUE TITLE
Add ي to the arabic layout.

### ISSUE THREAD

**Issue by Limfjorden** [dessalines/thumb-key#533]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Currently, only ی is on the keyboard, which sometimes makes it impossible to write words correctly in Duolingo. I am aware that the two letters are the same, but Duolingo does not see it that way. I suggest replacing ی with ي since ي is the standard version (I think). The other could be added as a swipe off of the same button.

**Comment by XJ-9Olev** [comment]
That graph is used in both Egyptian Arabic and Classical Arabic. It would be better to simply move it.

**Comment by dessalines** [comment]
PRs welcome for that keyboard, I don't maintain it.

**Comment by Limfjorden** [comment]
I'll gladly do it, but I don't know what file is the arabic keyboard. I see no file with ARA or ARB or anything like that.

**Comment by dessalines** [comment]
I don't think there is an arabic layout, just persian. I'll re-open if someone wants to add that layout tho.
