### ISSUE TITLE
Autocapitalization doesn't work properly on two-handed layout

### ISSUE THREAD

**Issue by Kommynct** [dessalines/thumb-key#539]
There are a few issues on two handed that don't appear on the standard layout

I is not automatically capitalized, ever

Every text field also starts capitalized, even passwords and URL's

And although this issue was closed: https://github.com/dessalines/thumb-key/issues/432

It is still occuring on the latest master with two-handed.

I tried to look at the layouts to figure out what was different between the standard thumb-key and two-handed, i'm not finding any difference, but i'm very unfamiliar with this.

**Comment by Kommynct** [comment]
https://github.com/dessalines/thumb-key/pull/549

**Comment by dessalines** [comment]
In the future you can put `Fixes #ISSUE_NUM` in the commit message or the pull request.
