### ISSUE TITLE
Toggling capslock should result in no caps, rather than shift

### ISSUE THREAD

**Issue by Kommynct** [dessalines/thumb-key#550]
As it currently seems to work, it seems to go to a copyright symbol for some reason, which isn't even typed. (I'm very confused by this behavior, but it persists across many layouts, in my recent PR i changed it to the shift icon because that's what it actually moves it to)

Pushing capslock again should just turn off shift instead of leaving the next character shifted. Alternately perhaps it should do nothing so you have to swipe down on a to exit capslock, which would make it harder to switch to shift on accident.

**Comment by dessalines** [comment]
There's already a dedicated down button to go to lowercase, so I don't see why the ^ needs to do anything other than go between shifted and caps lock.

**Comment by Kommynct** [comment]
It's fine if it goes between shifted and capslock, but as it currently stands it goes from capslock to... copyright?

Also, I don't think there's a situation in which i'd want the next character to be shifted instead of immediately ending the capslock, and seeing as the character for the two is hard to distinguish, you may accidentally swipe and cause your shift to end without expecting it. If the shift ends immediately upon that swipe, you'll see the letters shrink and it'll be much more obvious what happened.

**Comment by dessalines** [comment]
I don't understand what else we could do. There are 3 different icons showing your current mode: normal, shifted, and caps lock. Caps lock means every character is upper case. Caps lock should never end on swiping, unless its a mode change. I just don't understand what the issue is.

**Comment by Kommynct** [comment]
The issue is that it's very difficult to tell if you're capslocked or not, for example, look at how gboard displays it

![image](https://github.com/dessalines/thumb-key/assets/13646790/6115e6b5-0eab-4654-b62a-0399ebeb86f9)
![image](https://github.com/dessalines/thumb-key/assets/13646790/d11e88db-f23c-4bdb-9bd9-4f628f6a2931)

Really I was just getting approval before I applied some kind of fix to make it easier to not accidentally shift when you mean to caps, which results in an additional swipe.

It is extremely minor, so, I understand it not being worth reviewing the pull request.
