### ISSUE TITLE
When adding new language, how to add Diacritics?

### ISSUE THREAD

**Issue by namelessperson0** [dessalines/thumb-key#554]
I am trying to add few Indian languages.

Several Indian languages use Diacritic where consonants and vowels combine. 

I am not able to find out how to add Diacritics in this file https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ENThumbKey.kt

Some info about Indian languages https://en.wikipedia.org/wiki/Devanagari

**Comment by dessalines** [comment]
I don't have any expertise with this, but there is a composed layout, that adds some accents https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt#L368C9-L368C9
