### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by Ingegneus** [dessalines/thumb-key#557]
- [ x] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

it would be really handy if one could just copy paste images

**Comment by Ingegneus** [comment]
do you know how gboard odes this?

**Comment by dessalines** [comment]
Not sure
