### ISSUE TITLE
Swipes to external borders of keyboard do not work

### ISSUE THREAD

**Issue by flauta** [dessalines/thumb-key#559]
**Thumb-Key Version**
latest 2.6.0 (but see #444)

**Describe the bug**
When the keyboard is Right position, the swipes to right do not work, or in Center position work only sometimes (the same for swipe left with keyboard on the left, if the keymap has such swipes).

IMHO: this happens since there is no space enough (or no space at all) for the finger to stop movement outside the square AND inside the screen

Recordings with scrcpy from phone screen (tested with LG LM-X210, LG K100 and Asus X018D)

- with Italian - split (swipe right on right keys with keyboard in center o right position)
  https://cloud.disroot.org/s/4yTKPdLoc4aowBf
 
- with English thumbkey (swipe right on M should always give '?' )
  https://cloud.disroot.org/s/P2Edp6HMqmpCoDH

**Comment by flauta** [comment]
Maybe this issue exists only in all my old Android versions: I see developers are not interested in discussing it. 
So I'm closing this issue. 
Actually I'm using a personal  (Italian) profile in which I moved all non-working external swipes to internal swipes, and I use it every day via a Debug version of thumbkey loaded from ADB.

**Comment by racuna** [comment]
Sometimes it happens to me with the 1st row of keys. 

E.g. trying to get the "W" in the "E" key using type-split layout.  

The weird thing, is that this happened just a couple of times, and I'm using this keyboard for more than a month.
