### ISSUE TITLE
Spacebar slide gesture doesn't work in Firefox

### ISSUE THREAD

**Issue by spiffytech** [dessalines/thumb-key#560]
**Thumb-Key Version**
2.6.0

**Describe the bug**
Text boxes on websites in Firefox mobile don't support thumb sliding. The cursor appears to jump to the next letter, then quickly jumps back.

Thumb sliding on the same websites works with gboard, and with Thumb Key in Chrome.

**To Reproduce**
1. Go to pastebin.com
2. Type something into the big text area
3. Try to use the spacebar thumb sliding to move the cursor around
4. Cursor stays in place

**Comment by Kommynct** [comment]
I've found that it skips a lot of characters elsewhere as well, there seems to be some fundamental issue with slide gesturing, I haven't noticed the same for the backspace selection slide gesture.

**Comment by dessalines** [comment]
Is this still an issue for anyone? I just tested on a newer firefox, and it doesn't appear to be a problem anymore.

**Comment by Kommynct** [comment]
Resolved for me as well, weird
