### ISSUE TITLE
Hungarian layout issue

### ISSUE THREAD

**Issue by csecsoliver** [dessalines/thumb-key#565]
**Thumb-Key Version**
2.5.2

**Describe the bug**
Typing ó results an ő, typing ű results an ő and typing ú results an u.

**To Reproduce**
Use the magyar thumb-key layout.

**Comment by dessalines** [comment]
I don't maintain that keyboard, so you'll have to ask whoever did to fix it, or do a PR.

**Comment by KnockoffFeline** [comment]
Dang, you beat me to it. As the creator of the layout, I have absolutely no idea why it doesn't work, but every other just does 😢

I even tried to re-order the swipe maps to try to partially fix this issue, but that of course didn't work because WHY???

**Comment by csecsoliver** [comment]
That's unfortunate.

**Comment by dessalines** [comment]
I'm guessing you only changed the display character, and not the type character in the definition. Make a PR and I can help test it.

**Comment by KnockoffFeline** [comment]
I reviewed the code and this is not the case. I indeed matched the display character with the typed one.

**Comment by dessalines** [comment]
I figured it out. Its because someone used the wrong swipe type. I'll fix it shortly.
