### ISSUE TITLE
Slide gestures to select text not working well on long documents

### ISSUE THREAD

**Issue by MikeStirner** [dessalines/thumb-key#566]
**Thumb-Key Version**
2.5.2

**Describe the bug**
There's a bug in the Slide Gestures Select Text feature of the app. When used in long documents exceeding 1,000 characters, like in Google Keep or Google Docs, the cursor jumps back to around character 985 instead of selecting text at the current position. This makes the feature impractical for long documents.

**To Reproduce**

- Open a text-editing app like Google Keep or Google Docs.
- Create or open a document that has more than 1,000 characters.
- Navigate to a point in the document beyond the 1,000th character.
- Attempt to use the Slide Gestures Select Text feature at your current cursor position.
- Observe that instead of selecting text where the cursor is, the cursor jumps to around the 985th character, and selection starts from there.

**Comment by dessalines** [comment]
Is it really a common case to slide 1k characters? Why not just tap-hold or select all?

**Comment by MikeStirner** [comment]
No, this is just if you want to select like a word or a sentence or something. But it's really far down in the document that you're working on.
