### ISSUE TITLE
Japanese TypeSplit layout issues

### ISSUE THREAD

**Issue by Phidica** [dessalines/thumb-key#567]
**Thumb-Key Version**
2.6.1 via F-Droid

**Describe the bug**
Japanese Hiragana TypeSplit layout is missing *tsu* ( つ) and *to* (と), instead having an extra *u* (う) and *o* (お). I think @K0baU you are the maintainer for this since you added it in #541? I like the layout, and as a new Japanese learner I am trying to get fast with it but some missing characters makes for a bit of trouble :stuck_out_tongue:

The problem is the same on the Katakana layout as well.

**Comment by Phidica** [comment]
I am also not a very big fan of how the characters move around so much on the "uppercase" (dakuten/handakuten) page. For instance the "ga" characters move one space to the left of where the "ka" characters were. Why not leave them in the same place so it is easy to keep typing without looking, instead of learning a different layout again?

**Comment by dessalines** [comment]
Will re-open should someone want to work on fixing the japanese layouts.

**Comment by K0baU** [comment]
> Japanese Hiragana TypeSplit layout is missing tsu ( つ) and to (と), instead having an extra u (う) and o (お).
It was my mistake, thank you for fixing.
