### ISSUE TITLE
More precise position control

### ISSUE THREAD

**Issue by Housies** [dessalines/thumb-key#570]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

It would be useful to have a slider to precisely control the left/right position of the keyboard, rather than just selecting center/left/right.

**Comment by dessalines** [comment]
> but it would also be good to increase the maximum bottom offset of the keyboard, from 100 maybe to 200.

> Is this only a single feature request? Do not put multiple feature requests in one issue.

**Comment by Housies** [comment]
I've edited it to one issue and put the other request in another issue
