### ISSUE TITLE
Thumb-Key thinks it's forgotten my selected layouts

### ISSUE THREAD

**Issue by KnockoffFeline** [dessalines/thumb-key#589]
**Thumb-Key Version**
2.6.3

**Describe the bug**
Thumb-Key thinks it has forgotten the layout after closing it through the Recent apps screen while having another input method chosen. See below what I mean by "thinks".

**To Reproduce**
1. Open Thumb-Key from the home screen
2. Make sure your input method is set to anything but Thumb-Key.
3. Open the Recent apps screen and close Thumb-Key.
4. Repeat step 1.
5. Notice that the selected layout setting has been "reset to default".
6. The layouts may be restored by choosing Thumb-Key as your input method.

**Comment by dessalines** [comment]
Confirmed, I'll see what's going on soon.
