### ISSUE TITLE
Option to allow centre column to push columns outward

### ISSUE THREAD

**Issue by pwd-github** [dessalines/thumb-key#592]
- [x ] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
The two handed layout is uncomfortably centred, forcing users to lean in. I would like to propose an option that makes it so the centre column can be fluid and push the keys either side to the edges of the screen.

**Comment by dessalines** [comment]
I don't think there'd be a way to make the layouts "fluid" / full-width, because we've chosen to keep each key have the same height and width. There *might* be a way to add some kind of spacer tho, if someone wants to work on it.

**Comment by dessalines** [comment]
I don't plan on adding fluid / non-square layouts, as that could get complicated very quickly. #399 

If you really want to do this, then you'd have to specify height and width ratios on every key for every keyboard.
