### ISSUE TITLE
Tapping the space key with slide gestures enabled sometimes does nothing

### ISSUE THREAD

**Issue by AdRuCo** [dessalines/thumb-key#596]
## Thumb-Key Version

Version 2.6.4

## Describe the bug

Tapping the space key with slide gestures enabled does nothing, for horizontal slide gestures of  lengths between around 20 and 50 pixels.

https://github.com/dessalines/thumb-key/assets/33733078/895ca42b-bc30-46eb-9c17-bd39a1c67cb8

## Expected behavior

Any space key slide whose length lies below the slide gesture threshold should insert a "space" character.

### Preconditions
- "Pointer location data" in "Developer Options" enabled.
- Slide gestures enabled and sensitivity set to 1.

### Steps
1. Write something somewhere.
2. Try moving the mouse cursor using gestures between 20 and 50 pixels. Some of those gestures will not produce any action.

## Additional details
Moving your finger while pressing a key is usual. That's why we have movement thresholds for taps. Following are some quick tests I made:
- The tiniest slide gestures, between 1 and around 20 pixels long (variable bounds), make the space key insert a space character.
- Tiny slide gestures, from 24 pixels long to whatever the slide gesture threshold is, do nothing. This is what I'm reporting.
- Longer slide gestures move the cursor as expected.

Somewhat related to #596.

**Comment by dessalines** [comment]
Makes sense, your slide sensitivity is too low. Increase it some, and that algorithm should work fine.

**Comment by AdRuCo** [comment]
Tested it with a sensitivity of 23, to the same effect. 

Bug does not seem depend on sensitivity. Lower sensitivities make it easier to reproduce by hand though.

**Comment by dessalines** [comment]
I tried out all the acceleration modes, and they all seem to work fine. You'll need to come up with a way to reproduce this, or look in the cursor movement functions.
