### ISSUE TITLE
Add Rosé Pine Theme

### ISSUE THREAD

**Issue by Kjev666** [dessalines/thumb-key#597]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

https://rosepinetheme.com/ for info.

**Comment by dessalines** [comment]
There's a theming guide on the readme: https://github.com/dessalines/thumb-key#theming-guide

Feel free to follow those instructions and create a PR to add that theme, bc I don't plan to.
