### ISSUE TITLE
Easier access to the question mark

### ISSUE THREAD

**Issue by alensiljak** [dessalines/thumb-key#599]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I find I'm missing the question mark the most. The layout seems pretty good otherwise. 
Perhaps it would be possible to add it to the bottom row?

While I would like to keep this a single issue, I have to add that having interpunction handy makes life, ehm typing, much easier. Having comma, dot, question- and exclamation marks easier accessible would hopefully help without adding too much clutter?

**Comment by alensiljak** [comment]
I just found threads discussing similar issues and will try other layotus. But the main suggestion/question stands.

**Comment by dessalines** [comment]
Its on the symbols keyboard. Also the spacebar multitaps have the most common punctuation markings, including `?`

**Comment by alensiljak** [comment]
Just out of curiosity, what makes a star (*) a better candidate for the main keyboard than a question mark (?)?

**Comment by dessalines** [comment]
Its used in at least 3 markdown markings. You'll notice comma and exclamation already exist on the spacebar multitaps, which are for punctuation / clause endings.

**Comment by alensiljak** [comment]
Speaking of Markdown - space multitaps prevent adding indentation. I prefer having explicit control of the output. But that's a matter of preference, I guess.
Context matters. I.e. typing a sentence vs Markdown note vs OrgMode vs Termux...

**Comment by dessalines** [comment]
You can turn off spacebar multitaps in the settings.
