### ISSUE TITLE
Delete/space in English type split

### ISSUE THREAD

**Issue by alensiljak** [dessalines/thumb-key#600]
- [ ] Did you check to see if this issue already exists?
- [ ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I really like the split type keyboard. It matches how I'd expect a phone keyboard to work.
However, after years of using layouts with the big space key at the bottom, I can't get used to the big backspace key taking that place. Putting the backspace key in the middle seems like a reasonable alternative. 

Delete key gestures also act a bit weird with gestures enabled in this layout. The special characters are overridden, which results in two redundant space keys.

**Comment by alensiljak** [comment]
Thanks for the tip! I'm new here, just installed ThumbKey today.

Pinging @mockballed, the creator of the layout. What do you think about the suggestion? 

From my limited experience, I might perhaps get used to having space in the middle but the key is to small to casually hit after a word is complete. 
Using two hands, I find it more strenuous to stretch the thumb in order to hit the middle column instead of just rotating it and hitting a large space at the bottom. Not to mention that probably over 99% of the phone users have that movement in their muscle memory.
I'm also not sure I see the point of having a big delete key.
Big space allows for easier cursor movements using gestures, which is something that is also becoming a standard in phone keyboards.

Separately, I could open another issue to address the issues with gestures?

**Comment by alensiljak** [comment]
@dessalines, one way to "resolve" this would be to create a new layout based on the guidelines of https://github.com/dessalines/thumb-key/pull/292. As I would actually prefer to have a Dvorak-based layout, the new layout could be EN Dvorak Type Split.
Would that work for you? Would that be enough of a justification for a new layout?

**Comment by alensiljak** [comment]
One more item - as I commonly actively use three languages, I'd need diacritics for German and Slavic. Is there a better way to add those than simply put them into another slot on the main keys?

**Comment by alensiljak** [comment]
I found #307

**Comment by dessalines** [comment]
> Would that be enough of a justification for a new layout?

Sure, go right ahead.

> Is there a better way to add those than simply putting them into another slot on the main keys?

There is an english composed keyboard, but I didn't create it, and I'm not entirely sure how it works. I'd def recommend just being explicit and having diacritics be simple swipes, otherwise you're adding hidden functionality that no one but you will know about.

**Comment by alensiljak** [comment]
@racuna, you can try the English Double Symbols layout for comparison. This is what I did to try out a different approach. I'm still faster on Dvorak but am improving slowly.

**Comment by racuna** [comment]
@alensiljak interesting layout, but is not available in Spanish nor Portuguese (yet). But thanks for the suggestion. I really like type-split even with the weird space/delete setup.

**Comment by dessalines** [comment]
I can re-open when someone wants to work on this.
