### ISSUE TITLE
Full-width thumb keyboard

### ISSUE THREAD

**Issue by alensiljak** [dessalines/thumb-key#602]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I'd like to work out an idea. I have applied for an account at Lemmy and we can discuss at depth here once I open a thread. Not sure how many people participate there but I'll post a link here later (when my account is approved).
In any case, this issue can be used as an actual request, once the idea is complete with details.

# Background
Several concepts coming together

- using thumbs, key-size
- swiping for extra characters
- use of screen space (full-width)
- special characters accessible immediately

plus my specifics 

- using both hands for fast typing
- using Dvorak layout
- using multiple languages with diacritics

# Proposal

Considering the name of the app is Thumb Key, I think this actually fits. Although, in practice, it is based on the 3x3 layout for use with one thumb. But, perhaps not?
I like the idea behind the Type Split layout. But, why not use all the available space? 

<img src="https://github.com/dessalines/thumb-key/assets/462445/51b35f5c-3023-4e71-b57b-521b17de7ea7" width="300px" />

[pr](https://github.com/dessalines/thumb-key/pull/292)

Especially, the idea behind the modification 

<img src="https://github.com/dessalines/thumb-key/assets/462445/e43a432b-9f71-438f-bc2f-64173ff57fee" width="300px" />

[comment](https://github.com/dessalines/thumb-key/issues/307#issuecomment-1629349977)

To maximize the space and utility when using two hands, I'd propose having 2 x 3x3 grids. One for each thumb.

Benefits:
- more characters available for touch-typing
- more slots available for swipe-typing

The layout would look something like this:
![image](https://github.com/dessalines/thumb-key/assets/462445/3926b96c-e2af-4b4c-af9f-97ffa44c9655)

Also pinging @mockballed.

# Discussion

Please let's use this for any final conclusions on issues. Discussion is at https://lemmy.ml/post/10082822.

**Comment by alensiljak** [comment]
One possible way to use space:

![image](https://github.com/dessalines/thumb-key/assets/462445/e09b1a91-c067-4c1e-b1fb-a4c4e21e27d1)

That would probably eliminate the need for the bottom row, which traditionally hosts the key.

**Comment by alensiljak** [comment]
# To Work-Out

- position of space
- 3 or 4 rows? 4th may be redundant then
- exact location of characters on the keys

**Comment by alensiljak** [comment]
One possible way to place the space key:

![image](https://github.com/dessalines/thumb-key/assets/462445/e09b1a91-c067-4c1e-b1fb-a4c4e21e27d1)

Pros:
- That would probably eliminate the need for the bottom row, which traditionally hosts the key.
- special characters and options can be placed as swipe keys

Cons:
- space is also needed for other special characters, which need to move to the main 3x3 grids
- special characters can't be placed in the middle duo to symmetric even layout

**Comment by alensiljak** [comment]
Some guiding principles need to be summarized.

# Principles

- Minimize the use of diagonal swipes

**Comment by alensiljak** [comment]
# Option 1: adapted 2-hand layout

One potential option is to reuse the current 2-hand layout, with some adaptation. 
I'd remove the middle row with the special characters and place the two useful keys into the bottom row.

**Comment by dessalines** [comment]
@alensiljak Would you still like to keep this one open?

**Comment by alensiljak** [comment]
I think we can close this now. I'd be interested to see what comes out of the AI geneted layouts #169, but at this size, not just 3*3.
