### ISSUE TITLE
Interrobang "‽"

### ISSUE THREAD

**Issue by xxxserxxx** [dessalines/thumb-key#604]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request?

🚫 Is this a question or discussion? 

There are still some coveted empty gestures (in the en layout, in any case). Could the [interrobang (‽)](https://en.wikipedia.org/wiki/Interrobang) get some love?

It's recognized, if unconventional, punctuation (since 1915), and is frequently available on keyboards a-la FlorisBoard when extended latin characters are enabled.

Easiest would be adding it directly, maybe in I->N, but if empty spaces were *assignable*, as in #586, then it wouldn't be a hard choice or popularity "hunger games" contest for free space. #586 is fairly new, and hasn't yet been rejected - it's a better feature, but I'd rather have the interrobang than nothing,

**Comment by xxxserxxx** [comment]
How are you leaning on #586? I feel as if adding (yet) another layout to add a single character would be overkill. I know #467 is out there, and might change the usability (UX) of layouts and make the list less overwhelming; #467 seems like fixing the wrong problem, or a work-around, at least in this case.

**Comment by dessalines** [comment]
I'm not going to add custom keys or in-app keyboard-editing, it'd be too much work, and would then need run-time-checked keyboards. Only compile-time checked keyboards allowed.
