### ISSUE TITLE
Add adaptive icon

### ISSUE THREAD

**Issue by Commenter25** [dessalines/thumb-key#607]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
Most apps use an icon marked with a safe zone that can be cropped to different shapes for different styles. Thumb-Key does not do this, which makes it inconsistent with the rest of the system. Fixing this is a minor thing, but a major aesthetic improvement. https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

I've attached multiple images to showcase the issue, next to icons which have properly adaptive icons.

To start, the worst case scenario, the icon displayed raw on a pure black background. It doesn't exist.
![The app on a black background](https://github.com/dessalines/thumb-key/assets/35016761/133ba8d4-7579-43fa-b733-c411b7439ff5)

In a more common scenario of a colorful background, this isn't as big of an issue. However, it is still an obvious standout from the rest of the system, especially with the odd spacing making it higher up rather than centered.
![The app on a teal background](https://github.com/dessalines/thumb-key/assets/35016761/a8b38c15-79ea-4d14-a2b5-4cfa30cd7f61)

Depending on the launcher, it may try to force it into being a pseudo-adaptive icon. This fixes readability issues, but the spacing issues become even more apparent as it tries to avoid cropping the image and adds a lot of additional padding.
![The app on a black background, with a pseudo-adaptive icon](https://github.com/dessalines/thumb-key/assets/35016761/3b6a4391-5ed2-4036-8b42-22a7e86172d9)
![The app on a teal background, with a pseudo-adaptive icon](https://github.com/dessalines/thumb-key/assets/35016761/a6812cf4-feed-488b-9e70-5e7a176dcd5d)

**Comment by dessalines** [comment]
That'd be much appreciated if someone who knows how to do this could handle it.

**Comment by KraXen72** [comment]
https://www.youtube.com/watch?v=o_PnMp27DWU

**Comment by KraXen72** [comment]
I think the icon itself could use a redrawing as it currently doesen't look that great imo. if i have some idea for a better icon i'll try to whip up some svg.
