### ISSUE TITLE
Spacebar multi-tap broken since 2.6.8 in non-compose apps

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#625]
**Thumb-Key Version**
2.6.8

**Describe the bug**
Spacebar multi-tap doesen't work in non-compose apps like GitHub, Aliucord or Telegram. it just sends more spaces.

**To Reproduce**
1. Go to one of the mentioned apps
2. Tap space twice
3. See 2 spaces even when multitap is enabled

**Comment by dessalines** [comment]
Dupe of #242

**Comment by KraXen72** [comment]
this is a different issue imo. the original only happens under some specific circumstances when you move the cursor with your finger. this is about multitap not working at all in non-compose apps (it works in the thumb-key test field)

**Comment by dessalines** [comment]
They're both related to the same thing, and its the same code that needs to be fixed.

**Comment by KraXen72** [comment]
ah, okay
