### ISSUE TITLE
Option to use regular key events with slide gestures

### ISSUE THREAD

**Issue by thabubble** [dessalines/thumb-key#631]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
An option to emit regular cursor movements with slide gestures enabled would be nice in apps like Termux

**Comment by sslater11** [comment]
This feature already exists :).

@Dessalines, I'm wondering if we should reword the setting for these, as the option doesn't tell you what it does.
Currently it's under
Behaviour > Spacebar: Allow normal wipes to work with slide gestures
Behaviour > Backspace: Allow normal wipes to work with slide gestures
"Normal swipes" means nothing, that's on me I think for wording it in such an abstract way.

What about this? Lengthy, but descriptive at least 😅
Behaviour > Spacebar: Allow short swipe to move cursor up/down/left/right. A longer swipe will move the cursor using gestures.
Behaviour > Backspace: Allow short swipe left/right to delete a whole word. A longer swipe will
 delete text using the cursor using gesture.

**Comment by dessalines** [comment]
Agree yeah, this one is done :)

@sslater11 That's up to you, either work for me, because this is one of those hard-to-describe things that needs to be used in practice to figure out how it works.
