### ISSUE TITLE
Show local currency in place of € or £

### ISSUE THREAD

**Issue by priyavrat-misra** [dessalines/thumb-key#632]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
https://github.com/dessalines/thumb-key/blob/066f76267229bf3a596e4dd0daf9bb1d8a7e2aed/app/src/main/java/com/dessalines/thumbkey/keyboards/ENThumbKeySymbols.kt#L132-L137

Here's something that came to my mind (didn't try out).
```kotlin
val currency = NumberFormat.getCurrencyInstance(Locale.getDefault()).currency?.symbol ?: "€"

// ...

 SwipeDirection.BOTTOM_RIGHT to 
     KeyC( 
         display = KeyDisplay.TextDisplay(currency),
         action = KeyAction.CommitText(currency),
         color = ColorVariant.MUTED,
     ),
```

**Comment by KraXen72** [comment]
i think $, € and £ should stay, as they're pretty common. there could be a wildcard local currency swipe in the numpad elsewhere though

**Comment by dessalines** [comment]
Agree, a new spot for the wildcard currency would be good. @priyavrat-misra feel free to submit a PR.

**Comment by priyavrat-misra** [comment]
Sorry but what's a "wildcard"? Is it some feature?

**Comment by KraXen72** [comment]
wildcard would just means that it's like dynamic. for example a URL wildcard could be *.google.com - which means (anything).google.com. In this case, i used 'wildcard' because it could be any currency. but yeah it would just be a swipe which is always the user's current currency. also, possibly only show it if the user's current currency is different than $/€/£ ? no need to have 2 ways to type the same thing imo.

**Comment by priyavrat-misra** [comment]
Got it. Will checkout the code locally and raise a PR.

**Comment by priyavrat-misra** [comment]
Bottom-right to <kbd>1</kbd> seems like a good spot. Let me know your thoughts before I begin.

**Comment by dessalines** [comment]
> Bottom-right to 1 seems like a good spot. Let me know your thoughts before I begin.

Seems good to me.
