### ISSUE TITLE
Invert the settings column position

### ISSUE THREAD

**Issue by Evengard** [dessalines/thumb-key#641]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Is it possible to make a setting to change the settings column (the one with language switch/numbers switch/enter/backspace) to be placed on the left?

**Comment by dessalines** [comment]
There isn't anything, but feel free to create a layout for that. I'll re-open if you do so.
