### ISSUE TITLE
Alignment issue in Enter key

### ISSUE THREAD

**Issue by priyavrat-misra** [dessalines/thumb-key#643]
**Thumb-Key Version**
2.6.10

**Describe the bug**
If you look closely, the <kbd>Enter</kbd> key is a bit shifted to left.
![image](https://github.com/dessalines/thumb-key/assets/73816335/2cca6716-0171-4075-9945-a44ef2b2e29d)

**To Reproduce**
See <kbd>Enter</kbd> key closely.

**Comment by dessalines** [comment]
Confirmed.
