### ISSUE TITLE
Most special characters are only usable from number pane

### ISSUE THREAD

**Issue by nightkr** [dessalines/thumb-key#646]
**Thumb-Key Version**
2.6.9, from f-droid

**Describe the bug**
Compared to messagease, it's slightly annoying to type special characters.

**To Reproduce**
1. Enable MessagEase, english layout
2. Swipe left from n
3. Note that `+` is entered
4. Enable ThumbKey, english messagease layout
5. Swipe left from n
6. `l` is entered
7. Enable number mode
8. Swipe left from 2 (n)
9. `+` is entered

**Comment by nevans** [comment]
I think you simply need to enable the "english symbols messagease" layout.  That's what I've done:

![Screenshot_20240204-105853.png](https://github.com/dessalines/thumb-key/assets/6142/21875979-b781-4358-acfb-de39d06e20f3)

For what it's worth, I agree that the way this is configured is unintuitive if you're switching from MessagEase.

**Comment by nightkr** [comment]
While that's _a_ solution, I don't think it's very practical to end up maintaining a cartesian product of language * layout * display options as separate static keyboard layouts.

**Comment by nevans** [comment]
> While that's _a_ solution, I don't think it's very practical to end up maintaining a cartesian product of language * layout * display options as separate static keyboard layouts.

I agree 100%.  Related to that combinitorial explosion of layouts that should be config settings, see also #655. 😉

**Comment by dessalines** [comment]
These are what the symbols keyboards are for.
