### ISSUE TITLE
Gesture to enter numbers from letters view

### ISSUE THREAD

**Issue by nightkr** [dessalines/thumb-key#647]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

MessagEase lets you enter a number from the letters view by long-pressing the equivalent square. This does nothing in ThumbKey.

**Comment by dessalines** [comment]
Dupe of #531
