### ISSUE TITLE
Gesture to capitalize current letter

### ISSUE THREAD

**Issue by nightkr** [dessalines/thumb-key#648]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
MessagEase lets you capitalize a letter by drawing a ring on its square, or after your flick.

**Comment by yurikhan** [comment]
To expand on this, in Messagease:

* if a lowercase letter is on a tap, its uppercase equivalent can be typed by drawing a circle starting from the same key;
* if a lowercase letter is on a swipe, its uppercase can be typed by swiping in the same direction and back to the starting point without raising the finger;
* clockwise and counterclockwise circles are supported, one of those can optionally be set up to enter digits.

**Comment by MisterE123** [comment]
Please add this. Coming from Messagease, this is a major part of how I use the keyboard

**Comment by nightkr** [comment]
> also long-press actions slow things down as android has to wait to see if that's the case

Not to disagree with the rest of your comment here (your call, ultimately), but this isn't true. Detecting double-taps adds a delay, but long-taps don't. You just need to check the time of release against the time of the down event. You already need to wait for release to detect swipes correctly.

**Comment by MisterE123** [comment]
is there a reason for "no guestures"? It should be a toggle checkbox in the settings, sure, but it massively increases the usability. 

The guestures that I need are: 

Capital center letter:
![Screenshot_20240204_174152_Firefox.jpg](https://github.com/dessalines/thumb-key/assets/61124264/580a2c51-5aca-4589-b912-3ce2fb7c85c9)

Capital side letter:
![Screenshot_20240204_174346_Firefox.jpg](https://github.com/dessalines/thumb-key/assets/61124264/d0581e07-cf7b-47d1-bfd9-25f7ef956d33)

Backspace one word:

![Screenshot_20240204_174452_Firefox.jpg](https://github.com/dessalines/thumb-key/assets/61124264/02de66df-2117-48de-afab-e2682ff0d634)

Move cursor one entire word:
![Screenshot_20240204_174605_Firefox.jpg](https://github.com/dessalines/thumb-key/assets/61124264/507f5535-3352-4a15-87c9-900e6e42a53b)

And the functionality you see of drawing the path.

**Comment by MisterE123** [comment]
May I point out that swiping from the center to the side of a square (what defines thumb-key) is itself a guesture.

**Comment by dessalines** [comment]
I don't want to add any hidden functionality to keys, so everything is apparent and easily visible.

Swipes are all (or should be) explicitly shown what key they're pressing or what they do.

**Comment by MisterE123** [comment]
> I don't want to add any hidden functionality to keys, so everything is apparent and easily visible.
> 
> Swipes are all (or should be) explicitly shown what key they're pressing or what they do.

The capitalization guesture is so integral to messagease that it feels like just how one uses the keyboard. Sad that you have to draw a line here.

**Comment by dessalines** [comment]
We don't have to replicate all the behaviors of messageease, especially since a lot of that keyboards functionality was hidden by gestures that weren't easy to discover. 

Not all languages have capital letters also (or shifted keyboards), so any solution would have to account for the complexities of that.

Not allowing "hidden functionality", and having every action be explicit and obvious, as well as limiting its features to only obvious things, is a pragmatic choice given I maintain this in my free time.

**Comment by dessalines** [comment]
The other possibility is to have other different autocapitalizer functions for languages that use caps as the first letter of most words.

That also has the benefit that its a setting for each keyboard, so its language-specific, not pervasive on every single keyboard.

**Comment by nightkr** [comment]
I think the "obvious"/relatively language-independent behaviour would be to interpret the gesture as "evaluate this according to the shifted layout". Effectively a shortcut for "shift -> tap/swipe", just like shift is a shortcut for enable caps lock -> press key -> disable caps lock.

**Comment by Zwyx** [comment]
Thumb-key already has hidden gestures: the `Slide gestures` on the `space` key :slightly_smiling_face: (as well as on the `backspace` key).

I'm will also greatly miss not having the gesture to capitalise the current letter. It'd be great if this issue could be considered again in the future.

**Comment by kgwong** [comment]
+1 to reconsidering this

As a MessageEase user, the hidden features in the keyboard can be really confusing. However, the capitalize gesture is much easier and faster to use over toggling the shift layer. And I agree with MisterE123, why not add an opt-in setting for 'advanced' users so there are no hidden features by default? Is this not already similar to the `Slide gestures` in the settings as Zwyx pointed out?

**Comment by JDeeth** [comment]
Jilted MessagEase user here too but I wish I'd learned of this years ago, the basic functionality is much better! isn't the point of this keyboard to be able to touch-type or nearly touch-type with your eyes on the cursor not the keys? so discoverable gestures shouldn't need to be literally represented on the layout in every case.

For me as well as the out-and-back / circle one way gestures to capitalise a letter, i also miss the circle-the-other-way gestures to enter numbers. Almost every language uses Arabic numerals, so making them always available with circle gestures would be beneficial to nearly all users, surely?

**Comment by BenBergman** [comment]
Fellow former MessagEase user here, and quick capitals are really the main feature that has me missing it. I don't see it being replaced with better auto-caps as typing obscure names of people/places/companies, acronyms, etc. is all but impossible to get consistently right.

I understand not wanting to develop new features that you don't want - it is your project after all. Would you at least be open to a pull request that adds this as an opt-in feature?

**Comment by dessalines** [comment]
Only if it's default off, and it's not a complicated gesture, but something much simpler like long press or double tap (and that also doesn't slow down the keyboard taps). 

Also I'll only re-open if there's someone who's willing to work on this that I can assign it to.

**Comment by nightkr** [comment]
For what it's worth, I ended up implementing this in https://github.com/nightkr/flickboard, which has an explicit goal of trying to reach parity with MessagEase.

**Comment by dandv** [comment]
Just a note for a first-time user with no prior exposure to similar apps: it wasn't intuitive at all how to type a capital letter in this app. I googled and landed on this issue. Long press doesn't do anything, and double tap inserts two lowercase letters.

Eventually I figure out that I had to swipe up on A, then tap the desired letter.

**Comment by dessalines** [comment]
It's right at the top of the readme instructions for how to use it, and also linked in the app.

**Comment by dessalines** [comment]
https://github.com/dessalines/thumb-key#user-guide
