### ISSUE TITLE
Gesture to quickly resize the keyboard

### ISSUE THREAD

**Issue by nevans** [dessalines/thumb-key#653]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

I often want a smaller than usual keyboard, e.g. to make more room for what's on the screen.  I sometimes want a larger than usual keyboard, e.g. to type quickly with more accuracy when I'm using my thumb vs index finger or left vs right hand.  Entering settings, finding the setting, adjusting it, and going back to where I was... maybe deciding I under/over adjusted and repeating the process... this is too many steps for a simple common task.

FWIW, MessagEase handles this with a swipe up (larger) vs swipe down (smaller) on their "finger" button.  But those swipes are already in use on the emoji button.  I _personally_ have no need for the IME switcher (down swipe), as I have easy access to that on the Android navigation bar at the bottom of the screen, and quick access to settings is nice, but not nearly so important _(for me personally)_ as quick access to resizing.  Perhaps diagonal right up/down swipes on the emoji key would work, either for resizing or for setting/IME switcher?

**Comment by kke** [comment]
Could be the pinch-gesture you have everywhere else for zoom.

**Comment by dessalines** [comment]
No pinching or hidden functionality, so it'd have to go on one of the current settings keys. 

I don't see this being desirable or useful tho, because once you find the right size that works for you, you shouldn't be changing it, as that could mess with your muscle memory.

It'd clutter up the existing settings keys, but if someone really wants this and can't go into their settings, I spose I wouldn't be opposed.

**Comment by witcheslive** [comment]
I like adjusting the size personally, my muscle memory is working fine to type this right now on thumbkey despite there being no left handed mode which I've been using for years on messagease. Sometimes based on how I'm holding the phone or having to use the other hand or getting a papercut or to fit a particular app use or any number of things I would live resize the keyboard, it can be very useful. Please don't assume otherwise.

**Comment by nevans** [comment]
Something that I never realized until I had the ability to rapidly resize the keyboard: the best size is highly contextual.  In my last several years of experience with MessagEase, changing the keyboard size often several times a day, I don't think it impacts my muscle memory all that much at all.  At least, not insofar as it pertains to knowing where the keys are and what gestures to make.

Besides that, generally the whole point of making it "too small" is an _intentional_ tradeoff of typing speed for screen real estate.  It's okay to type slowly sometimes.  And the point of making it larger is that the size that's most comfortable (and fastest) for my index finger is far too small for my thumbs.

**Comment by Kommynct** [comment]
I think the best solution would be to allow switching to preset sizes bound to a swipe, like how you can cycle through layouts right now.

**Comment by dessalines** [comment]
Gonna close this as I'd like to reserve the settings key swipes for more useful things.

**Comment by kinland** [comment]
> Something that I never realized until I had the ability to rapidly resize the keyboard: the best size is highly contextual. In my last several years of experience with MessagEase, changing the keyboard size often several times a day, I don't think it impacts my muscle memory all that much at all. At least, not insofar as it pertains to knowing where the keys are and what gestures to make.
> 
> Besides that, generally the whole point of making it "too small" is an _intentional_ tradeoff of typing speed for screen real estate. It's okay to type slowly sometimes. And the point of making it larger is that the size that's most comfortable (and fastest) for my index finger is far too small for my thumbs.

Currently, the lack of this is my chief complaint. The thumb-key keyboard is just massive and I want something with smaller butttons that doesn't eat half my screen.

Like Nevans says, being able to resize on the fly was a fantastic feature in MessageEase.

**Comment by dessalines** [comment]
We have keyboard resizing, just not as a gesture. Go into your settings to set the preferred size.
