### ISSUE TITLE
Combined/Merged keyboard layouts for "wide mode" 

### ISSUE THREAD

**Issue by nevans** [dessalines/thumb-key#655]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Currently, there are several "two-hands" layouts which, as far as I can tell, simply duplicate the layout on the left and right.  However, it would be very useful to instead have a secondary language layout or a permanent number pad layout on one side.

Rather than require a brand new layout for wide mode, which would lead to a combinatorial explosion of keyboard layouts as different languages and numeric/symbol layouts are factored in, there should be an option for landscape or sufficiently sized portrait to combine existing layouts.

This may require the option to drop the emoji/number/backspace/enter column from the secondary layout, so it isn't duplicated.  Saving this horizontal space would allow the double-wide layout to be used with larger key sizes, wider keyboards, and smaller screens.

Related:
* #642

For context, here is what my current MessagEase layout looks like:
![Screenshot_20240204-102851.png](https://github.com/dessalines/thumb-key/assets/6142/bb44fa43-5786-4c7a-abd6-058c75580367)

**Comment by nevans** [comment]
For context, here is how MessagEase configuration handles this:
![Screenshot_20240204-102752.png](https://github.com/dessalines/thumb-key/assets/6142/d262c7fd-9159-4a73-bb7b-a8c50b8418b3)

![Screenshot_20240204-102831.png](https://github.com/dessalines/thumb-key/assets/6142/1290b0d0-a848-4185-a047-666864cf75f4)

**Comment by dessalines** [comment]
I suppose this would be alright, as long as this type of mode is default off.
