### ISSUE TITLE
Support for ctrl, alt, tab, escape keys

### ISSUE THREAD

**Issue by jpentland** [dessalines/thumb-key#656]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

These keys are useful for terminal emulators such as termux. In messagease they are optionally bound to:

* ctrl: swipe spacebar up+right
* alt: swipe spacebar up+left
* escape: gesture swiping spacebar up+right, then back to spacebar
* tab: swipe bottom left letter key down+right

**Comment by dessalines** [comment]
Use one of the programmer layouts for these. If they're missing some of those, do a PR to add them.

**Comment by amillward** [comment]
Am I correct in seeing that the "english programmer thumbkey" layout indeed has tab, but not any of the other keys/modifiers?

**Comment by dessalines** [comment]
Yes that looks correct. If someone makes a PR tho to add those keys to that keyboard, I'd be glad to merge it.

**Comment by jpentland** [comment]
I did take a quick look into this  and it requires a little more work than just adding the keys. Since the base keyboards sent "text" events rather than "keypress" events, just adding a modifier doesn't seem to be possible. There would probaply need to be a third keyboard "mode" defined where all keys are events and that get used in the case that modifiers are activated (as there are already modes for lower and uppercase).
