### ISSUE TITLE
Left-handed mode

### ISSUE THREAD

**Issue by witcheslive** [dessalines/thumb-key#661]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I really miss left-handed mode from messagease, as i am, well, left handed. Please consider implementing it.

**Comment by dessalines** [comment]
I spose it'd be possible to do a simple reverse for a left-handed mode. But I wouldn't be able to add anything more complicated than that.

**Comment by ghen2** [comment]
Ok, so a left handed ME layout can only be implemented as a separate layout?

**Comment by dessalines** [comment]
Correct.

**Comment by BlueDrink9** [comment]
I'm a righthander but used left hand mode because having the keys closest to my thumb is more comfortable. I'll have a look at converting some layouts to left hand mode.

**Comment by KraXen72** [comment]
i think it might me a good idea to mark layouts which have the rightmost colums as a toolbar to be lefthand-eligible, and have a lefthand toggle to swap the column.
it's going to be most standard-ish layouts anyway, and creating separate left/right handed layouts creates code duplication, makes it harder to maintain both for the app developer in case of some bigger changes, or the layout maintainer, and most importantly further populates the already exhaustingly long layout list - a new user would have an even harder time finding a suitable layout.

**Comment by dessalines** [comment]
Thumbkey is too flexible for that, all it demands is that your layout is a matrix. It lets you put settings and functions keys anywhere you like, in any configuration. So it wouldn't be a good idea to sacrifice that.

**Comment by BlueDrink9** [comment]
Elsewhere there is discussion about adding tags to variants; I already have a function to flip a standard layout. We might be able to have something that applies that function at runtime if the variant has a particular 'left-available' tag?

**Comment by dessalines** [comment]
I suppose that now with your function, it'd be easy to persist a setting for `swap_edge_columns` or `left_hand_mode`, with the caveat that this won't work well for many layouts.

If you need help adding a setting for this, lmk.

**Comment by dessalines** [comment]
No work done on this, but can re-open if someone wants to add it.

**Comment by dessalines** [comment]
Sure, as long as its not too complicated.
