### ISSUE TITLE
Fixes and ideas

### ISSUE THREAD

**Issue by Der-Meister-von-codes** [dessalines/thumb-key#67]
Please fix double 'г' in Ukrainian layout, pasting 'E' letter after changing to lover case in Russian layout, and, if it possible, fully rewrite system of keys for loading here from json like this: {"ru":{{}{}{}{}{}{}}{{}{}{}{}{}{}{}{}{}}}} or someone else (I'm bad in json), just implement this idea. And please, add key for changing keyboard layout, I use it now, but going to program settings and changing layout is very uncomfortable. Many thanks and good luck!

**Comment by dessalines** [comment]
cc @DobriniaMerk

**Comment by DobriniaMerk** [comment]
Done
