### ISSUE TITLE
Allow customizing width of keys/keyboard

### ISSUE THREAD

**Issue by kgwong** [dessalines/thumb-key#671]
### Describe your suggested feature

It would be nice to be able customize the width of the keys so that they can fill the empty space. It is also easier to use since it adds size to the keys without increasing height. 

Screenshots vs MessageEase for a keyboard of the same height

<img src="https://github.com/dessalines/thumb-key/assets/8847646/0a7e63ad-f2ab-4fa6-a601-23e5b50f41be" width=30% height=30%>
<img src="https://github.com/dessalines/thumb-key/assets/8847646/250ddefe-7004-4203-bd10-0856c421b0e8" width=30% height=30%>

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by kgwong** [comment]
https://github.com/dessalines/thumb-key/issues/640

**Comment by dessalines** [comment]
@kgwong do not +1 here. Use a thumbs up on issues if you want them.
