### ISSUE TITLE
Key height/width ratio option in Look and Feel

### ISSUE THREAD

**Issue by Hsad** [dessalines/thumb-key#673]
### Describe your suggested feature

The only difference between messagEase and thumbkey I can't seem to control is the height of the keys.  Thumb-key has square keys while messagEase has somewhat squat keys.  This is very valuable for highly screen real-estate constrained phones like the Unihertz Jelly. 
An option to control the height of the keys would allow for maximizing the remaining real estate on small phones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by Hsad** [comment]
It looks like there is a value to modify the width, but just no way to change it in settings.
https://github.com/dessalines/thumb-key/blob/f8a7876301b46c9950ed79ca6b9e010d7268c11a/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt#L163

**Comment by dessalines** [comment]
This is done now.
