### ISSUE TITLE
Layout-specific settings

### ISSUE THREAD

**Issue by VirtuallyUnderstandable** [dessalines/thumb-key#676]
### Describe your suggested feature

I am using an English layout with **Hide Letters** settings turned on, but when I, say, want to type in Japanese hiragana instead, I'd have to turn the **Hide Letters** settings back off & maybe even changing my theme & theme colour as well. Then when I want to go back to my main English layout, I'd have to go back to settings to turn the **Hide Letters** option back on alongside possibly changing the theme & theme colour again. 

Doing this all the time gets annoying quick, thus is it possible for a way to implement a layout-specific setting option so whenever I'd change the keyboard layout, it would also load in a preset setting for that specific layout?

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Having per-keyboard settings isn't something I have time to do. I'll re-open should someone want to take this on.
