### ISSUE TITLE
"english symbols messageease" symbols in different places in number mode

### ISSUE THREAD

**Issue by JDeeth** [dessalines/thumb-key#677]
### Steps to reproduce

Select "english symbols messageease" layout
Switch between normal and number keyboard modes

### Expected behavior

Symbols should always be in the same places in either mode

### Actual behavior

Normal symbols are in the expected places
Some numeric symbols are in different places, e.g. `-<*,£>`

![Screenshot_20240206-111547](https://github.com/dessalines/thumb-key/assets/847887/68675370-1b0d-49b1-9ddc-382eaeb91510)

![Screenshot_20240206-111559](https://github.com/dessalines/thumb-key/assets/847887/0a0def63-1e5e-46c1-b736-fd7a1c7e9544)

### Android version

n/a

### Device

n/a

### Other details

also the layout title should be `messagease` not `messageease`

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report,  in case of multiple bugs I will open a separate issue for each one  (they can always link to each other if related)
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't maintain that keyboard, so you'll have to submit a PR to fix it.

**Comment by JDeeth** [comment]
OK, looks straightforward enough. Although you don't maintain the keyboard layouts, they are part of this codebase, so can you leave the ticket open until the change is done? I think I can make the changes myself - define an explicit NUMERIC keyboard for this and perhaps the non-symbol english messagease layouts - emulating other keyboard configs.

However I am not equipped to test any changes myself. It might be preferable for someone with an Android build system set up to make the same change but with the assurance it works. If you leave the ticket open, such a person may be able to grab this one.

**Comment by dessalines** [comment]
Ya sure.

**Comment by asdkant** [comment]
I'm working on #709 which fixes this. @JDeeth please review and let me know if you find any issue there.
