### ISSUE TITLE
German Layout

### ISSUE THREAD

**Issue by rickcrash** [dessalines/thumb-key#68]
Hi,

I have tried to make the file with german layout. For the letter-frequency I just asked wikipedia. I had to add the "Umlaute" aka diphtongs i think and i decided to place near the ordinary letters, e.g. "Ö" near "O" etc. Same thing for the "ß".

I hope I did not destroy the syntax with the extra-letters. It was great if you could yous my proposal.

Greatings
Rick

https://adelheidi.de/nextcloud/index.php/s/H5CnabrMpQZ7DMG

**Comment by dessalines** [comment]
I'll merge this as is, but I **highly suggest** moving the `O` and its umlaut variant to the right side of the keyboard, maybe swapping for either the `C` or `L` . Right side of the keyboard should be vowels, left side consonants.

**Comment by rickcrash** [comment]
Thank you for that advice. The layout should be consistent over all languages, so I'll change it as it is proposed.

Thank you for your extremely fast reaction.


-------- Ursprüngliche Nachricht --------
Von: Dessalines ***@***.***>
Gesendet: 23. März 2023 19:22:04 MEZ
An: dessalines/thumb-key ***@***.***>
CC: Rick ***@***.***>, Author ***@***.***>
Betreff: Re: [dessalines/thumb-key] German Layout (Issue #68)

I'll merge this as is, but I **highly suggest** moving the `O` and its umlaut variant to the right side of the keyboard, maybe swapping for either the `C` or `L` . Right side of the keyboard should be vowels, left side consonants.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/dessalines/thumb-key/issues/68#issuecomment-1481691816
You are receiving this because you authored the thread.

Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem GrapheneOS-Gerät mit K-9 Mail gesendet.

**Comment by dessalines** [comment]
No probs! It'll be in the next release.
