### ISSUE TITLE
Use Tab-Key

### ISSUE THREAD

**Issue by bcm314** [dessalines/thumb-key#681]
### Describe your suggested feature

I'm using: DEMessageEaseSymbols.kt

In Messagease you can swipe BOTTOM_RIGHT from the t-key to use tab-key.
Can this be done with "\t"?

So adding something like this:
```
SwipeDirection.BOTTOM_RIGHT to
                                KeyC(
                                    display = KeyDisplay.TextDisplay("->|"),
                                    action = KeyAction.CommitText("\t"),
                                ),
```
Of course displaykey should look better.
Here is a Screenshot about the symbol used: https://pbs.twimg.com/media/Et2tNQXWYAIndGX.jpg

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Feel free to submit a PR for that keyboard, I don't maintain it.

**Comment by JDeeth** [comment]
to answer the question: other layouts have `KeyAction.CommitText("/t")` so, yeah, should be fine!
https://github.com/search?q=repo%3Adessalines%2Fthumb-key%20CommitText(%22%5Ct%22)&type=code
