### ISSUE TITLE
Spanish thumb and messagease and can use symbols in normal  layout and numbers

### ISSUE THREAD

**Issue by marcossmtp** [dessalines/thumb-key#682]
### Describe your suggested feature

I think in spanish is better to have the ? symbol in abc layout than ¿ , when you normal type most of people only write the last ? to abreviate. And only in formal writing used the ¿.
It would be can enter numbers with a long press in abc layout.

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't maintain that keyboard, so you'll have to open up a PR / edit that file directly.

**Comment by marcossmtp** [comment]
ok

**Comment by dessalines** [comment]
It isn't maintained by me, I didn't create that layout. You'll need to edit that file directly / do a PR. Watch a video on how to do this.

**Comment by ZePotente** [comment]
Is it ok if I make them "?" and "!" in the main mode and "¿" and "¡" in the shifted mode? It worked similarly on MessagEase. 
This would display and write a "¿" if you were writing in all caps though.
