### ISSUE TITLE
Remove internet permissions

### ISSUE THREAD

**Issue by dups41** [dessalines/thumb-key#683]
### Describe your suggested feature

As mentioned at https://lemmy.ml/post/11517716 it would be nice if the internet permission could be removed given that it is only used for fetching the changelog.

Thanks for the great keyboard

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by tab0r** [comment]
Came here to request this. I don't need a changelog in app, considering that I'll only be manually updating it. I imagine other privacy conscious users are the same. Those that aren't probably aren't using this kind of thing at all.

**Comment by dessalines** [comment]
Does anyone know a tool that can generate those github changelogs without creating a tag or release first? 

This would be doable then, by generating the changelog before the release, bundling it, and using it as a local rather than a network resource.

**Comment by alerque** [comment]
Yes, [git-cliff](https://github.com/orhun/git-cliff) can generate changelogs for an upcoming release before tagging, including linking GitHub stuff (although if you want the closest match for GitHub's formatting and grouping you'll need [this pr](https://github.com/orhun/git-cliff/pull/363) which is merged but not in a release yet.
