### ISSUE TITLE
Option to invert the numpad

### ISSUE THREAD

**Issue by ZeSandman** [dessalines/thumb-key#697]
### Describe your suggested feature

Would it be possible to have an option to invert the numpad, so that the keys are

789
456
123
0

Like it is on regular computer keyboards?

I find It more intuitive when used on tablets.

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by ZeSandman** [comment]
Dammit, I found a request 5min after searching for something else...   I closed this one

**Comment by ZeSandman** [comment]
t

**Comment by rommeswi** [comment]
I could not find it and it does not seem to be in the is:open list. Does that mean the other issue you found is also closed?

**Comment by ZeSandman** [comment]
It was issue #527  

I was thinking about an option just to flip the upper and lower lines of the numeric keypad and that discussion explained it would take another layout and thus wasn't really easy to do.  I thought a simple option could flip it for all layouts, not that it had to be explicitely done for each of them individually

I'm really used to a pc keyboard's numpad, I was using that option on Messagease too
I'm a touch typist so I expect the keys to be

789
456
123
0

not 

123
456
789
0

Even if "touch-typing" isn't a thing on a tablet, the muscle memory's still there, and I have 35year of it so I nearly always mess up when using that numpad. :/
