### ISSUE TITLE
Rename layouts to sort alphabetically better

### ISSUE THREAD

**Issue by BlueDrink9** [dessalines/thumb-key#702]
### Describe your suggested feature

Currently variants of keyboards are named like "[language] [variant] [base]", eg "english symbols thumb-key" and "english thumb-key". That means that in the keyboard list, they don't sort together.

I'd like to propose renaming them to be [lang] [base] [variant], so we get "english symbols messagease left" sorting with "english messagease".

### Other details

Opening this as an issue rather than doing it immediately just to avoid having too many PRs open, and to check you'd be welcome to the change. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by smurfix** [comment]
Actually a two-level hierarchy would be nice. Or even something more flexible. The single list is too long already, and with all the MessagEase refugees it's only going to get longer.

**Comment by BlueDrink9** [comment]
that's been discussed pretty extensively; check through other issues. What I'm talking about here is as a temporary measure

**Comment by dessalines** [comment]
> I'd like to propose renaming them to be [lang] [base] [variant], so we get "english symbols messagease left" sorting with "english messagease".

That's actually `[lang] [qualifier] [base] [qualifier]` , which doesn't make much sense to me. Best to group the qualifiers / variants together, and have the [base] at the end.

**Comment by BlueDrink9** [comment]
Can you talk me through your reasoning? Messagease/thumb-key seem like a "base" to me, is that where we differ?

For users, they likely only care about the options for their language, so sorting them together makes sense.

May have to table this for the tag system though

**Comment by dessalines** [comment]
I'm suggesting that we stick with the current naming:

`[langs] [qualifiers] [base]`

Qualifiers include things like `symbols`, `programmer`, etc.

**Comment by BlueDrink9** [comment]
Oh yup I agree, my bad example. I meant en sym ME left would be renamed to en ME sym left, just didn't type it out fully

**Comment by dessalines** [comment]
No probs. `en ME sym left` IE

`[langs] [base] [qualifiers]` would also work, but someone would need to go through every layout title, and I'm not sure its worth it.

**Comment by BlueDrink9** [comment]
I'll do it, looks fairly regexable

**Comment by dessalines** [comment]
Can re-open if someone wants to work on this.

**Comment by mpsijm** [comment]
I've spent some time on renaming things, what do you think? :slightly_smiling_face:
In https://github.com/mpsijm/thumb-key/commit/34bca6100d3e9f4204956eb05f3cc59ffdffa79e, I've renamed the layout titles.
See https://github.com/mpsijm/thumb-key/compare/layout-en-messagease-two-hands-symbols...mpsijm:thumb-key:702-rename-layouts for all my changes so far (also renaming the constants).

**Comment by dessalines** [comment]
@mpsijm Those all look good so far! Feel free to open up a draft PR, then mark it as ready for review whenever.
