### ISSUE TITLE
spacebar after a number should return to alphabet keyboard

### ISSUE THREAD

**Issue by amillward** [dessalines/thumb-key#713]
### Describe your suggested feature

In messagease when typing numbers then hitting space, it automatically returns to the main letters keyboard. It'd be great to replicate this functionality in thumb key

### Other details
![20240211_095624](https://github.com/dessalines/thumb-key/assets/1857493/80390940-0bc7-41e9-a61d-be70b7e52416)

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by pavlov-p** [comment]
If that gets implemented, I would like it to be optional. As it's not uncommon to enter numbers (or symbols from the number layout, if you use no-symbol main layout) with spaces in-between.

**Comment by dessalines** [comment]
Agree, I'd dislike this also. If someone wants to implement this setting tho, I can re-open.
