### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by asdkant** [dessalines/thumb-key#718]
### Describe your suggested feature

A PR template so that contributors have useful info at hand when they attempt to open a PR.

Off the top of my head I can think of reminding them to run `./gradlew formatKotlin` and `prettier` so the CI will pass, but there's probably something else that should be included.

### Other details

docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I really wish there was the equivalent of something like husky for kotlin / android, or if someone knows how to do proper automated git-hooks setup, that'd be appreciated.
