### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by bcm314** [dessalines/thumb-key#723]
### Describe your suggested feature

How about having more (flexible) number of layers but only 3?

For example:
```
            KeyboardDefinitionModes(
                main = MAIN,
                shifted = SHIFTED,
                numeric = KEYBOARD,
                extra1 = EXTRA1,
                extra2 = EXTRA2,
            ),
```
And somewhere else use something like this (or simply give the number of the layer 0-4 or 1-5):
```
                action = KeyAction.ToggleMode("extra1"),`
```

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I'm not against this, as long as its not used to store other language layouts. Should just use the language switcher for that.

**Comment by bcm314** [comment]
> I'm not against this, as long as its not used to store other language layouts. Should just use the language switcher for that.

Could be used for CTRL, ALT, or a lot other special chars. 😏

**Comment by bcm314** [comment]
And one more idea, I like to do first, as long-tap is implemented, now:

I've read some like to use long-tap for uppercase (I haven't tried).
In MessagEase by default long-tap is used for the relating numbers, which I'm using.
(How about a setting about the time need for tapping to get long-tap?)

So I would like two layers with lower letters with different long-tap definition, using depending on the text you write.

**Comment by dessalines** [comment]
No multiple issues please. I don't think I want to add multiple long tap durations, this is getting way too complicated too quickly.

**Comment by bcm314** [comment]
> No multiple issues please. I don't think I want to add multiple long tap durations, this is getting way too complicated too quickly.

Sorry, you missunderstood me. I don't speak about multiple long tap things.

I'm waiting for adding more layers, so in one layer I can configure long-tap as uppercase and in an other layer the same long-tap as numbers.

**Comment by dessalines** [comment]
Should be fine, its done at the key level: https://github.com/dessalines/thumb-key/blob/4b011deb3d9fbc0387d10331d04cff0f170a7611/app/src/main/java/com/dessalines/thumbkey/utils/Types.kt#L43

And multiple layers have different keys.

**Comment by bcm314** [comment]
> Should be fine, its done at the key level:
> 
> https://github.com/dessalines/thumb-key/blob/4b011deb3d9fbc0387d10331d04cff0f170a7611/app/src/main/java/com/dessalines/thumbkey/utils/Types.kt#L43

This belongs longPress.
It looks, like I missed one thing: for using longPress for uppercase, 9 keys are not enough. 

How about adding longPress also to KeyC?
Working like: tap down, swipe, wait, untap (and use time between tap down and untap)
(Or exact: when untapped in time use normal function, but after a defined time whilte tapped use longtap, for example write a character and so the user knows it's time to untap, now)

> And multiple layers have different keys.
Sorry, I don't understand.
Maybe I used the wrong word "layers" and had better spoken about "modes".
As written in the opening post, I like to have more than 3 configurable modes to switch between.
But KeyboardDefinitionModes contains only 3 fixed modes, using fixed functions Toggle...

**Comment by dessalines** [comment]
Rather than adding endless numbers of modes, it'd be better to just create alternate keyboards, and use the language switcher. Much more flexible, customizeable, and less complex.
