### ISSUE TITLE
Untrusted keyboard

### ISSUE THREAD

**Issue by yorikvanhavre** [dessalines/thumb-key#726]
### Steps to reproduce

Open the keytrade bank app

### Expected behavior

The bank app opens

### Actual behavior

The bank app closes, and I'm being redirected to https://www.keytradebank.be/app-exit-en , stating:

> Dear client,
>
> The app has closed due to security reasons.
> A possible cause might be that you are using:
>
>    A rooted or jailbroken device
>    Untrusted keyboards
>    Untrusted screen readers
>
> To solve this issue, you can use the default iOS or Android system keyboards or default screen readers.
> Please contact our Contact Centre if you have any questions.

### version of the program

2.6.9 (f-droid)

### Android version

Android 12

### Device

Xiaomi Poco X3

### Other details

Just reporting this FYI (I don't expect a resolution, feel free to close if not doable). I suppose "untrusted" would mean untrusted by Android, hopefully you don't need to go get trusted by each and every bank app out there... Messageease, for ex, is apparently "trusted". I coudn't find any doc on the internet about that process, if it exists, though :/

*Edit* - Tested further, other bank apps (BNP, Argenta) don't complain. So it might actually be bank-specific... I suppose there is not much to be done, but I'll let you close the issue).

Thanks for the amazing work on thumb-key!

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
No probs! Ya we have no control over random bank apps.

**Comment by alerque** [comment]
> Messageease, for ex, is apparently "trusted".

I believe this *might* have to do with the Internet permission that Thumb-Key currently has. This has already been discussed for other reasons (see #688) and removed, but the version you are using is older than the first release where that permission was dropped. I know some other (non bank) systems that flag the use of apps that A) have access to sensitive content and B) have internet permissions so they could theoretically exfiltrate data as a security risk. That might be what was happening here, you could try updating and see if this is still a problem.

**Comment by yorikvanhavre** [comment]
Apparently not, I'm now using 2.6.16 I took from github a few days ago, and the problem is still there.

Not sure if wrong permissions could still be there from a previous install? Looking at the app permissions, I see nothing related to internet access...

<img src="https://github.com/dessalines/thumb-key/assets/1136856/b8ffde51-bd95-4839-a1d4-4563379ac278" height=30% width=30%> <img src="https://github.com/dessalines/thumb-key/assets/1136856/744adb29-ba8a-4691-8c56-ced9cd7a6c85" height=30% width=30%>

**Comment by dessalines** [comment]
Reinstalling still gives the same issue?

**Comment by yorikvanhavre** [comment]
Uninstalled + reinstalled, still same result. But it seems not everything is removed on uninstall? I still have my thumb-key preferences kept from before...

**Comment by yorikvanhavre** [comment]
Tried wiping everything, still no changes (using 2.6.20 now). I guess ultimately it depends on that particular bank app and there is not much to be done except go complain to that bank app on the app store :) (I'll try that too, who knows we raise awareness)... Anyway, thanks to both of you for having looked into this!
