### ISSUE TITLE
Multiple action

### ISSUE THREAD

**Issue by bcm314** [dessalines/thumb-key#737]
### Describe your suggested feature

How about multiple action, something like this:
```

action = (
    KeyAction.SendEvent(
        KeyEvent(
            KeyEvent.ACTION_DOWN,
            KeyEvent.KEYCODE_CTRL_LEFT,
        ),
    ),

    KeyAction.CommitText("a"),

    KeyAction.SendEvent(
        KeyEvent(
            KeyEvent.ACTION_UP,
            KeyEvent.KEYCODE_CTRL_LEFT,
        ),
    ),
),

```
?

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
How about it? Feel free to make that an array and add it to whatever keyboard you want.

**Comment by bcm314** [comment]
> How about it? Feel free to make that an array and add it to whatever keyboard you want.

Sorry, I don't understand. Currently it's not working.
Should I change the code to define it as array there?

**Comment by dessalines** [comment]
I don't understand either. Which keyboard and what action do you want to add? You need to open a PR if you want to add this.

**Comment by bcm314** [comment]
> I don't understand either. Which keyboard and what action do you want to add? You need to open a PR if you want to add this.

I could open only a PR, if I would have implemented this feature already. But I'm not familar with the code and would need a lot of time to understand it and can make secure implementations. So I thought, someone knowing the code well could implement it in a more easy way.

The feature I asked is very simple: when tapping on one key, multiple actions should be done, like sending KEYCODE_CTRL_LEFT-down, than key 'a' and than finaly KEYCODE_CTRL_LEFT-up.

**Comment by dessalines** [comment]
I don't understand, because your request is too general. Why do you want multiple actions? Which keyboard and keys do you want them on?

**Comment by bcm314** [comment]
> I don't understand, because your request is too general. Why do you want multiple actions? Which keyboard and keys do you want them on? What are the multiple actions you think are necessary?
> 
> An issue needs a use-case before it should be added.

I guess, we can stop discussion. It looks like we are not "compatible" to understand each other.
