### ISSUE TITLE
Requesting - Yiddish Layout

### ISSUE THREAD

**Issue by Kjev666** [dessalines/thumb-key#740]
### Language

Yiddish

### Kind of request

New Layout

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
See the readme instructions for adding layouts. You'll have to do this yourself.
