### ISSUE TITLE
Filipino English MessagEase Layout

### ISSUE THREAD

**Issue by Lysalana** [dessalines/thumb-key#743]
### Describe your suggested feature

Just a few change to the English MessagEase layout like adding the peso sign (₱), the letter /ñ/ (also in the shifted keyboard), and the hyphen [-].

### Other details

First time using this site. No idea how to commit or whatever github does (I can't for some reason). So I edited an existing code there with another keyboard layout in reference and then put my desired changes in the code below. Not familiar with the programming language either.

[PH_EN_Messagease.kt.txt](https://github.com/dessalines/thumb-key/files/14348003/PH_EN_Messagease.kt.txt)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by Lysalana** [comment]
Adding proposed fix to the missing capslock function on the shifted keyboard. I just initially copy pasted the code from non-shifted keyboard to the shifted keyboard and then make everything in capital letters. Please double check if I did it right this time. Thanks in advance.

[KB_EN_PH_MESSAGEASE.kt.txt](https://github.com/dessalines/thumb-key/files/14373813/KB_EN_PH_MESSAGEASE.kt.txt)

**Comment by dessalines** [comment]
That file exists now, so you need to click edit on it through github or make a PR.
