### ISSUE TITLE
Futo is not always used for speech to text in Whatsapp

### ISSUE THREAD

**Issue by frederickjh** [dessalines/thumb-key#746]
### Steps to reproduce

1. Confirm that Futo Voice Input is installed on your device.
2. Confirm that Thumh-Key is configured to use Futo-Voice Input
3. Open Whatsapp and go to a chat
4. Tap on a text field to bring up the Thumb-key keyboard
5. Swipe to the microphone to bring up the speech to text
6. Repeat number 5. multiple times.
7. Note that the Google speech to text some times comes up and not Futo Voice Input

### Expected behavior

When swiping to activate speech to text I expect Futo-Voice Input to always be used.

### Actual behavior

When swiping to activate speech to text  sometimes  Futo-Voice Input is used and sometimes Google speech to text input is used.

### version of the program

2.6.9

### Android version

13

### Device

Galaxy A51

### Other details

I searched through the Whatsapp settings to see if this was a configuration issue with Whatsapp but did not find any settings that seemed to apply.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Did you disable / uninstall google's TTS? If its before it in the list, we can't do anything.

**Comment by frederickjh** [comment]
@dessalines Funny that you asked that, as I thought after filing the issue, I wonder if I can disable the Google Voice Typing. I did this and now Futo is used all the time. However at least on my phone I could not find a way to reorder the keyboard list, including voice input ones.

Also, in the User guide it states under the heading, **Emoji Key**

> Swipe to bottom-left to toggle voice input. Requires FUTO Voice Input.

However it appears that it will use whatever voice input is installed and seems to randomly switch between multiple ones if they are enabled.

Is this something that could be a setting in Thumb-key to select the voice input that should be used?

**Comment by frederickjh** [comment]
But I think that is my point, that there does not seem to be a default voice input method. Maybe in versions of Android higher than what I am running  (Android 13) there is, but the fact that it kept randomly choosing one makes me wonder if the apps can have a setting to choose the voice input the user wants to use with them.
