### ISSUE TITLE
Bug from issue #743 English Wikang Tagalog MessagEase capslock bug

### ISSUE THREAD

**Issue by Lysalana** [dessalines/thumb-key#752]
### Steps to reproduce

1. Press the shift key
2. Press the shift key again to toggle CAPS LOCK.

### Expected behavior

TOGGLE THE CAPS LOCK.

### Actual behavior

Still remain in the shifted keyboard and only Capitalize The First Character.

### version of the program

2.6.18

### Android version

Android 9

### Device

Samsung Note 8

### Other details

Re-adding the code for missing caps lock function from EN MessagEase keyboard layout to the bugged shifted keyboard should fix it. I initially just copy pasted the code from non-shifted keyboard to the shifted keyboard and then make everything in capital letters. Please double check if I did it right this time. Thanks in advance.

[KB_EN_PH_MESSAGEASE.kt.txt](https://github.com/dessalines/thumb-key/files/14374041/KB_EN_PH_MESSAGEASE.kt.txt)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
That keyboard already exists, so go to the file and click edit to make the changes you want. If you can't figure out how to do this, watch a video on it.

**Comment by Lysalana** [comment]
I already made the commit proposal. Thanks for telling me. Hope I did it right.

**Comment by dessalines** [comment]
It didn't, because I see no open prs here.
