### ISSUE TITLE
Automatically change keyboard layout to dual mode on landscape orientation

### ISSUE THREAD

**Issue by Lysalana** [dessalines/thumb-key#754]
### Describe your suggested feature

There should be different layout settings whenever the user is sets the device orientation to landscape mode apart from the portrait settings (especially when playing games or browsing on a landscape mode). Typing on a single grid keyboard over a large surface area felt so troublesome like how I have to reach my thumbs over a small space at the center of the screen. Making it larger or moving the keyboard to either side of the screen is not an option either, I want to use both my thumbs for faster input.

Add an option to automatically use a dual keyboard or a split type keyboard whenever the device goes on landscape mode. Like how the Thumb-Key English layout should automatically go Dual Thumb-Key English on landscape mode.

### Other details

Make it a feature instead of another keyboard layout or that would mean another set of hundreds of keyboard layouts again... the dual mode and the split mode.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by Lysalana** [comment]
![Screenshot_20240222-211437_Thumb-Key](https://github.com/dessalines/thumb-key/assets/40502878/14fdc05d-732f-4c30-bd64-2e2056ca4daa)
![Screenshot_20240222-211451_Thumb-Key](https://github.com/dessalines/thumb-key/assets/40502878/964f225d-29bb-45ef-986f-01049968905d)

**Comment by Lysalana** [comment]
This one feels like I have to reach the kb farther with both my fingers.
![Screenshot_20240222-220733_Thumb-Key](https://github.com/dessalines/thumb-key/assets/40502878/f3adcb05-aaf0-453d-aa58-6c78f45d40d0)

**Comment by dessalines** [comment]
This isn't something I'm interested in adding, but if someone wants to work on it, I'll re-open.

**Comment by Atemu** [comment]
This would be much needed for landscape to work sensibly; thumb-key currently takes up wayyy to much precious vertical space in landscape.

It'd be great if the spacebar and enter keys could also be made to be at the center between the two grids to save a whole row.

**Comment by dessalines** [comment]
If you want to work on this, let me know and I'll assign it to you.

**Comment by Atemu** [comment]
I'd like to but I can't make any promises.

This would likely require changing a bit how layouts work at a basic level as there'd then have to be two actual layouts for each layout: one landscape and one portrait. You'd likely also want the landscape alignment to differ from portrait.

I don't know how the current layouts work. Do the regular 3x3 ones follow some sort of standard so that they could be transformed into a split layout generically?

**Comment by dessalines** [comment]
This would require setting a default, specifically chosen keyboard for portrait, and another for landscape mode.

**Comment by Atemu** [comment]
That doesn't strike me as a great solution. There are already too many overlapping layouts as is and this would necessarily double the amount.

Wouldn't you want the same base layout in both orientations anyways? All that would need to change to adapt for landscape is the layout of the buttons "around" the base 3x3 layout: spacebar, enter, backspace, numbers and settings buttons.

**Comment by dessalines** [comment]
There is no guarantee of a 3x3 layout, and we have a lot of layouts that aren't. There is no clean way to convert any given layout to a "landscape mode".

**Comment by Atemu** [comment]
This wouldn't work for the non-3x3 layouts of course. Those would need separate standards on how to transform them into short horizontal layouts that facilitate landscape use.

So in solving this issue properly I'd need to define a standard for regular 3x3 layouts I take it?

**Comment by dessalines** [comment]
I don't think this could be solved in any other way than what I described: let people create landscape-oriented keyboards, and optionally set portrait and landscape keyboards to what they like.

There's is a way in code to manipulate every keyboard into a *landscape mode.*

**Comment by Atemu** [comment]
> There's is a way in code to manipulate every keyboard into a _landscape mode._

Sorry I think you typo'd here. For clarity: There *is* or there *isn't*?

**Comment by dessalines** [comment]
Sorry, isn't a way
