### ISSUE TITLE
Add the possibility to remove the text to speech shortcut

### ISSUE THREAD

**Issue by oldriku** [dessalines/thumb-key#757]
### Describe your suggested feature

I never use that feature and it's annoying and cumbersome when I hit it by mistake and I have to go change my keyboard back to this one.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't see myself working on this or wanting it, but if someone wants to work on it, I'll re-open and assign it to them.
