### ISSUE TITLE
"@" character doesn't work on spanish MessagEase layout alphabetic layers

### ISSUE THREAD

**Issue by asdkant** [dessalines/thumb-key#759]
### Steps to reproduce

1. (configure and) switch to "español messagease"
2. try to type `@` character (bottom-left swipe from "R") on lower or upper case alphabetic layers

### Expected behavior

`@` is detected

### Actual behavior

Either nothing is detected, or the tap symbol (`R` or `r`) is detected. The symbol on the numeric layer works fine.

### version of the program

2.6.18

### Android version

14 (OneUI 6.0)

### Device

Samsung Galaxy S21 FE

### Other details

This looks like thumb-key is not parsing the layer definition correctly. I checked the code and the layout definition seems correct:
- [lower case](https://github.com/dessalines/thumb-key/blob/22177df517ac1076b77e78265793c330ae399cbf/app/src/main/java/com/dessalines/thumbkey/keyboards/ESMessageEase.kt#L226)
- [upper case](https://github.com/dessalines/thumb-key/blob/22177df517ac1076b77e78265793c330ae399cbf/app/src/main/java/com/dessalines/thumbkey/keyboards/ESMessageEase.kt#L567)

Also tested and reproduced on:
- v2.6.16 & v2.6.18 (Galaxy Tab S5e, androdid 11, OneUI 3.1)
- v2.6.17 (same S21 FE)
- v2.6.18 (Galaxy A52, android 13, OneUI 5.1 )

So it doesn't seem to be device-specific.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Probably has to do with an incorrect swipetype.

**Comment by asdkant** [comment]
You mean the `SwipeDirection.BOTTOM_LEFT` thing? But that's correct:

```kotlin
// lower case
SwipeDirection.BOTTOM_LEFT to
    KeyC(
        display = KeyDisplay.TextDisplay("@"),
        action = KeyAction.CommitText("@"),
        color = ColorVariant.MUTED,
    ),
// upper case
SwipeDirection.BOTTOM_LEFT to
    KeyC(
        display = KeyDisplay.TextDisplay("@"),
        action = KeyAction.CommitText("@"),
        color = ColorVariant.MUTED,
    ),
// numeric
SwipeDirection.BOTTOM_LEFT to 
    KeyC(
        display = KeyDisplay.TextDisplay("@"), 
        action = KeyAction.CommitText("@")
    ),
```

**Comment by asdkant** [comment]
How can I properly debug this issue?

**Comment by asdkant** [comment]
Ohh, ok, I get it now. I'm working on some changes to this keybard (a rework on the placement of `¿` and `¡`, mostly, I've been test driving it for a few days) so I'll include it there and do the PR later today if nobody fixes it before
