### ISSUE TITLE
Remove clause-ending punctuation from english keyboard, move to spacebar additional taps.

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#76]
Add these to the spacebar extra taps. Do it by decreasing frequency, so:

`,.?!:;`

I'll leave the other keyboards alone, and let them remove them if they wish.

#73

**Comment by breversa** [comment]
Displaying those characters on the spacebar (in muted color) would go a long way to remembering they exist in the first place, and in which order. :)
