### ISSUE TITLE
So many numeric keypad layouts. Let us choose them as well.

### ISSUE THREAD

**Issue by Lysalana** [dessalines/thumb-key#763]
### Describe your suggested feature

Just like the keyboard layouts, I just discovered that there are also more than one numeric keypad layouts available out there. So I'm requesting to have us choose our preferred numeric keypad.

As far as I know, there the different numeric keypads out there. For example, the original Thumb-Key has its own numeric keypad [NUMERIC_KEYBOARD], so is ENMessagEase [KB_EN_MESSAGEASE_NUMERIC], and ESMessagEase [KB_ES_MESSAGEASE_NUMERIC]. There are probably many other numeric keypads out there that other keyboard layouts use.

### Other details

In issue #677, if I understand it right, the symbols placement discrepancy issue of ENMessagEaseSymbols keyboard is fixed by changing the Thumb-Key [NUMERIC_KEYBOARD] to [KB_EN_MESSAGEASE_NUMERIC] in its numeric keypad.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't see why having multiple numeric keyboards is necessary in the first place. I'd rather get rid of them all than add a separate layout chooser.
