### ISSUE TITLE
Typing too quickly causes multiple letters to be capitalized

### ISSUE THREAD

**Issue by GabrielDTB** [dessalines/thumb-key#765]
### Steps to reproduce

1. Be in normal capitalize mode
2. Tap two letters at the same time
3. See both letters output as capital

### Expected behavior

Only the first letter should be capitalized.

### Actual behavior

Both letters are capitalized.

### version of the program

2.6.19

### Android version

Android 14

### Device

Google Pixel 5

### Other details

This happens quite often during normal typing for me, as I type fast enough on a slow enough phone that the time between tapping the first letter and tapping the second letter is long enough that both letters come out as capital.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I used to get this, but at least in recent releases of jetpack compose, the rendering has been fast enough that I can't replicate. Test on version `3.1.1` and tell me if you still get this, and I can re-open.

**Comment by pavlov-p** [comment]
I'm still getting the issue, even with v.3.1.1

**Comment by bkp23** [comment]
I'm still experiencing this with version 5.0.6. It's always been the case that I need to pause slightly after typing the first capital letter.
