### ISSUE TITLE
Letters and symbols aren't evenly spaced out

### ISSUE THREAD

**Issue by StevenAlexander44** [dessalines/thumb-key#789]
### Steps to reproduce

1. Reset to defaults
2. Set key size smaller

### Expected behavior

I think the letters used to touch the borders of their keys.

### Actual behavior

 Letters are all squished towards the middle.

### version of the program

3.6.23

### Android version

Android 13 (lineage)

### Device

Pixel 4

### Other details

I can submit a picture if it isn't reproducable.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
They shouldn't touch the borders, no.

**Comment by StevenAlexander44** [comment]
This is what I mean:
![IMG_20240303_120800](https://github.com/dessalines/thumb-key/assets/64290624/2a83724e-320d-4d20-8b09-f60191bc45b9)
It's purely visual, but a little annoying.
(It becomes more visible as I set the keysize smaller. This screenshot was 42 I think)

**Comment by locrianz** [comment]
I swear this is a new problem. It didn't used to be like this.

**Comment by StevenAlexander44** [comment]
F-droid doesn't let me downgrade to confirm, but I think it's only an issue in 3.6.23
