### ISSUE TITLE
Second symbols layer

### ISSUE THREAD

**Issue by Lysalana** [dessalines/thumb-key#790]
### Describe your suggested feature

There is a hidden additional symbols layer on MessagEase keyboard that is only accessible if you do the drag-and-return gesture on the symbols which is confusing.

Since Thumb-key doesn't support drag-and-return gesture issued on #648 yet (unless someone is willing to work on it), let us have the shifted symbols layout instead to make it visibly obvious.

Make this additional symbols layout appear by having us [swipe the '6' key upwards] on the symbols layout.

### Other details

In MessagEase keyboard, I only discovered these additional symbols by typographical accident and was confused where did those symbols came from. (It would be nice if that layer is visible in the first place there)

Most qwerty keyboards have two layers of symbols by the way.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by Lysalana** [comment]
On MessagEase keyboard, using the drag and return gesture on symbols layout on will transform the following...

$ becomes ¥
- becomes ÷
+ becomes ×
` becomes ‘
´ becomes ’
^ becomes ˇ
/ becomes – (n-dash)
\ becomes — (m-dash)
! becomes ¡
? becomes ¿
= becomes ±
$ becomes ¥
€ becomes £
% becomes ‰
{([ become })] only outputs the counterpart, I suggest retaining the same {([ 
< becomes ‹
> becomes ›
_ becomes ¬
| becomes ¶
@ becomes ª
~ becomes ˜
¨ becomes ˝ (this set doesn't exist on Thumb-key ENMessagEase symbols layout)
" becomes “ (open quotation mark)
' becomes ” (close quotation mark)
& becomes §
° becomes º
* becomes †
# becomes £ (why there are two pounds here, I suggest adding a musical sharp♯here instead as well as adding flat♭ on [top-left swipe on 9], and natural♮)
; becomes ; (unchanged, make this ♮ instead)
: becomes „
, becomes ‚
. becomes …

So I propose adding this shifted second symbols layout with some improvements by having us [swipe the '6' key upwards].

I'm willing to work out on it.

**Comment by dessalines** [comment]
Why not just create an additional `EXTRA_SYMBOLS` keyboard for all these?

**Comment by Lysalana** [comment]
How does `EXTRA_SYMBOLS` work?

My bad for presenting it that like they are an uppercase of those symbols... but it is not really an uppercase though. Just think of it as another symbols layer accessible by using the same gesture like how Microsoft Swiftkey and Samsung keyboard access the second layer of symbols by pressing the same key on the exact same position as their shift button. Maybe just replace the _^_ display on the shift gesture into 1/2 (first layer) and 2/2 (second layer) like how Samsung keyboard does it for clarity. :)

**Comment by Lysalana** [comment]
```
$ becomes ¥
- becomes ÷
+ becomes ×
` becomes ‘
´ becomes ’
^ becomes ˇ
/ becomes – (n-dash)
\ becomes — (m-dash)
! becomes ¡
? becomes ¿
= becomes ±
$ becomes ¥
€ becomes £
% becomes ‰
{([ become })] only outputs the counterpart, I suggest retaining the same {([ 
< becomes ‹
> becomes ›
_ becomes ¬
| becomes ¶
@ becomes ª
~ becomes ˜
¨ becomes ˝ (this set doesn't exist on Thumb-key ENMessagEase symbols layout)
" becomes “ (open quotation mark)
' becomes ” (close quotation mark)
& becomes §
° becomes º
* becomes †
# becomes £ (why there are two pounds here, I suggest adding a musical sharp♯here instead as well as adding flat♭ on [top-left swipe on 9], and natural♮)
; becomes ; (unchanged, make this ♮ instead)
: becomes „
, becomes ‚
. becomes …
```
I only wrote this list down as a reference to their placements.

**Comment by dessalines** [comment]
Check out the MATH keyboard for an example. We don't need additional symbols layers, you can just create another layout with the symbols you want.

**Comment by dessalines** [comment]
Can re-open if necessary, but feel free to create a symbols layout if you like.
