### ISSUE TITLE
Voice input button not working

### ISSUE THREAD

**Issue by sidgames5** [dessalines/thumb-key#796]
### Steps to reproduce

1. Open the keyboard
2. Press voice input button
3. Doesn't work

### Expected behavior

It should open the voice input keyboard

### Actual behavior

It doesn't do anything and instead I have to click the keyboard button to switch to that keyboard

### version of the program

2.6.24

### Android version

Android 14 / CalyxOS 5.4.0

### Device

Google Pixel 4a 5G

### Other details

Expected behavior (shown on android default keyboard)
https://github.com/dessalines/thumb-key/assets/68089579/646942da-6fe6-4fed-8d4b-1e5d34681766

Actual behavior (thumb key)
https://github.com/dessalines/thumb-key/assets/68089579/c6f1a7a7-41a6-41d9-8606-03cb24317e32

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Its in the user guide: https://github.com/dessalines/thumb-key?tab=readme-ov-file#user-guide

You need to install futo voice input, and disable the other methods.

Can re-open if that doesn't work.

**Comment by sidgames5** [comment]
Thanks! This worked.

**Comment by dessalines** [comment]
No probs!
