### ISSUE TITLE
Put on f-droid

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#8]

**Comment by gmankab** [comment]
+

**Comment by ilyakooo0** [comment]
It seems to already be on f-droid. Maybe this issue should be closed?

**Comment by dessalines** [comment]
It isn't on f-droid yet, only on izzyondroid.

**Comment by IzzySoft** [comment]
Congrats for achieving an F-Droid listing with reproducible builds, @dessalines :star_struck: At this point, given a decent overlap of about 2 weeks, I usually remove apps from my repo – unless the author explicitly requests I shall keep them. I see your Readme here still has my badge, so I assume that was an implicit request to keep it? :smile: So shall it stay? Thanks to reproducible builds and a decent APK size, I'd see no problem with that – so the decision is yours.

**Comment by dessalines** [comment]
Yes please keep it if you would. f-droid builds can often take a week or more, and I've also had their build system fail me at many times when using the newest versions of jetpack-compose, then requiring manual intervention to fix.

**Comment by IzzySoft** [comment]
> Yes please keep it if you would.

Sure! Marked it for keep, linking here (you will see that on my web front-end after the next sync).

> when using the newest versions of jetpack-compose

Or when upgrading to a pre-release gradle, as that's usually non-free – or to a just-released-one which is not yet configured… Yes, I'm aware of those issues.

> I prefer your repo, as it just takes my builds directly, but some might like to see it on f-droid also.

Thanks to reproducible builds, this doesn't cause any issues (or confusion) with signatures either. So to make sure, one could install from F-Droid and then update from wherever a new version shows up first (where might that be :see_no_evil:).

OK, all set then – thanks!
