### ISSUE TITLE
Do not flash/show the character typed when in a password field

### ISSUE THREAD

**Issue by frederickjh** [dessalines/thumb-key#800]
### Describe your suggested feature

Currently Thumb-key acts the same in a password field as in a normal text field. When a character is type the button changes color and shows the selected character. This also happens when in a password field allowing over the shoulder snooping of passwords even if they do not know the keyboard.

This feature request is to add a setting to allow then turning off the flashing of the character when typed when in a password field. Further more I would recommend that this should be the default setting for password fields and that a user needs to turn character flashing back on for password fields.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I think I follow. This probably doesn't need to be a setting, but should just by default, not provide the helper animation text for password fields. They're pretty rare anyway.

**Comment by frederickjh** [comment]
Android makes me type in my password on my phone regularly to unlock it even though I have fingerprint unlocking setup and then more importantly there my password database program that does this at times too. In an case the frequency of these password fields showing up is a mute point, the security risk is what I am concerned about.

**Comment by frederickjh** [comment]
This feature request is akin to shielding the number pad at an ATM, so prying eyes cannot see it, when you enter your PIN.
