### ISSUE TITLE
Replace Euro sign with Russian ruble sign in Russian layout

### ISSUE THREAD

**Issue by ligurio** [dessalines/thumb-key#802]
### Language

Russian

### Variant

₽

### Kind of request

Changes on an existing layout

### More details

Russian layout contain a symbol € [^1], see screenshot. However, Russian ruble (currency of the Russian Federation) [^2] has it sown sign - [₽](https://en.wikipedia.org/wiki/%E2%82%BD). I propose to replace Euro sign with Russian ruble sign in Russian layout because it is more in demand on this layout.

![thumb-key](https://github.com/dessalines/thumb-key/assets/1151557/d36af345-7c5e-4504-afb6-0ab1e71385a0)

[^1]: https://en.wikipedia.org/wiki/Euro_sign
[^2]: https://en.wikipedia.org/wiki/Russian_ruble

Version: 2.6.10

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Feel free to make a change to that keyboard.

In the meantime, [this logic](https://github.com/dessalines/thumb-key/blob/eb09507b113d4c2a8d3b9e31013bd6ed807e3de3/app/src/main/java/com/dessalines/thumbkey/keyboards/Numeric.kt#L35) in the numeric keyboard means the bottom right of one of those keys, should be your local currency.

**Comment by yorikvanhavre** [comment]
@dessalines this is a bit off topic but about that logic you pointed above... I'd like to add the "-" sign to the numeric keyboard, ideally right to number 1 to match most alpha keyboards. However, the swipes under number 1 use `buildMap()` instead of `mapOf()` and I'm unsure how to add one more swipe there... Should I put one more `put()` under the existing buildMap()? Or append a mapOf() afterwards? Thanks!

**Comment by dessalines** [comment]
The `-` sign is already on the numeric keyboard, bottom right of 8.

**Comment by dessalines** [comment]
Can re-open if necessary.
