### ISSUE TITLE
Slide guestures janky in Firefox text fields

### ISSUE THREAD

**Issue by bojidar-bg** [dessalines/thumb-key#803]
### Steps to reproduce

1. Open Firefox Android (v123.1.0 -- might happen elsewhere too, but I can't observe it under Chrome Android)
2. Load a page with a text field; e.g. a [DuckDuckGo search](https://duckduckgo.com/?q=example&t=fpas&ia=web)
3. Put cursor inside text field, and slide gesture to the left (or right) with the spacebar key

### Expected behavior

* Cursor smoothly slides to the left (right) and goes to the end of the word.

### Actual behavior

* Cursor "rubberbands" in-place, and never moves more than a few characters -- or if it does, it never moves to the start (end) of the word.
* Normal spacebar swipes still work.

### version of the program

2.6.9 (FDroid) & 2.6.25 (from releases)

### Android version

Android 13

### Device

Moto G54 5G

### Other details

<details><summary>Screen recordings</summary>

Sorry for the low quality, I blame my phone's inbuilt gif recorder.

[gif-20240312-215132.webm](https://github.com/dessalines/thumb-key/assets/5276727/2cd6dfc9-1e37-4663-a944-efcaafa92080)

[gif-20240312-212337.webm](https://github.com/dessalines/thumb-key/assets/5276727/bc8bc258-0559-45b1-9c3d-6a6b2d2d71dd)

</details>

The same field works fine with MessagEase's back-and-forth skip-a-whole-word swipe, and it also works fine with Gboard's swipe-on-spacebar-to-move-cursor feature. Not sure what might be going on exactly.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I just tried this again, and can't replicate. I'll re-open if necessary.
