### ISSUE TITLE
Frecency based sorting recent emojis

### ISSUE THREAD

**Issue by pxeemo** [dessalines/thumb-key#812]
### Describe your suggested feature

The recent emojis section can have better sorting by considering frequency and recency of usage like messengers and other keyboards.

### Other details

Each emoji can be assigned by a score count and  increase it by 1 in every subsequent use. When a query is made, we calculate frecency based on the last time the emoji was used:
|Last used 	|Frecency|
|:---|:---|
|Within the last hour 	|`score * 4`|
|Within the last day 	|`score * 2`|
|Within the last week 	|`score`|
|Within the last month 	|`score / 2`|
|Otherwise 	|`score / 4`|

This can also have an aging to lower the score and limit by the max recent emojis. Then the emojis will be sorted by frecency.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
We just use the android emoji picker and have no control over this. It also already has a recently used section.
