### ISSUE TITLE
spanish type-split: 'qu' and 'e' on the same key.

### ISSUE THREAD

**Issue by Eloitor** [dessalines/thumb-key#817]
### Language

spanish

### Variant

type-split

### Kind of request

Changes on an existing layout

### More details

The Spanish type-split keyboard has `qu` and `e` on the same key, which is odd, since it is a very frequent combination.

From a wordlist I found online:
- qua: 6
- que: 14875
- qui: 8737
- quo: 2

I do not know how to improve it....

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You could open up a PR to fix this one.

**Comment by Eloitor** [comment]
Where should I place "qu"?

**Comment by dessalines** [comment]
Up to you, doesn't matter to me since I don't use that keyboard.
