### ISSUE TITLE
Discussion outside of Lemmy

### ISSUE THREAD

**Issue by urmomseksy** [dessalines/thumb-key#82]
I know you setup a Lemmy community, but I'm sure there are others like me who don't really want to join another community.

It would be awesome to have at least one pinned discussion thread or possibly a couple discussion threads here on GitHub based on topics:

- speed results for Monkeytype or other sites (I think some way to have people compete on here would help gather momentum for your keyboard)
- layout options, request, and discussion regarding your custom layout versus the old Messagease layout, and whether your current  layout can be optimized better)

**Comment by dessalines** [comment]
These types of community discussions are exactly what the http://lemmy.ml/c/thumbkey community is for. Github should be primarily for developers and contributers, not for general discussion.
