### ISSUE TITLE
Double-Mapping Swipes

### ISSUE THREAD

**Issue by JulianVJacobs** [dessalines/thumb-key#820]
### Language

English

### Variant

Type-Split

### Kind of request

New Layout

### More details

![keyboard](https://github.com/dessalines/thumb-key/assets/61211025/8f2ebdab-4f7c-4b39-b7b4-5af5685ff2c4)
I would love a keyboard formatted as above. The idea of it being that where there is only one character in the swipe-space between click characters, all swipes in the direction of that character map to the character. I bring this up because I've found that with the standard English Type-Split, I would sometimes swipe right on "A" to get "F", but "F" was actually mapped as left on "S". I don't see why it couldn't just be true for both.

Other changes I would like to test is adding digits so that there's no need to swap keyboards. Also, since the Type-Split resembles QWERTY, the space bar might be better placed on where the backspace is, however I concede this might simply be a muscle memory issue and I might get used to the formatting, having the space bar be larger than the backspace seems to suggest that action is happening for often when that's almost certainly not the case. 

This last point is maybe best placed in a different suggestion but if the answer is obvious maybe that isn't necessary: is there a testing environment where I could easily make these changes to test their efficacy? What's the easiest way to change the gesture maps? And if the answer is cloning either logging an issue or cloning the repository and doing it manually through Android studio, is there any work being done to just add a feature where keymaps can be personalised? It feels like a great way to crowdsource configurations and also avoid having so many requests for different layouts.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
The only way to test is through android studio. I'm not sure about a lot of these but you could start with one of the existing typesplit keyboards and edit it from there.
