### ISSUE TITLE
New type-split layout inspired by Dvorak and Thumb-Key

### ISSUE THREAD

**Issue by Azurite0923** [dessalines/thumb-key#822]
### Language

English

### Variant

type-split

### Kind of request

New Layout

### More details

It's a variant of the type-split and would like for it to be a new layout available to everyone.

The issues I've had with english type-split were common trigrams and very awkward feeling when speeding up my typing speed.

I am not a programmer and have zero experience so if someone could create this layout it would be a huge favor to me. I'm a student and don't have enough time to understand code.

It was inspired by Dvorak's objective of alternating between hands (in this case fingers) and your fingers naturally coming to the homerow. One side is split into vowels and the other into consonants, while switching some letters for easier flow into the thumbs. Check it out please.

(I did this layout on my free time throughout the day. I've edited it a couple times and tested by "touch typing" and pretending the letters were changed. It feels comfortable and able to keep up at a consistent speed. If there are any suggestions, I would be happy if this new layout got some improvements over time)

Here is a picture of the layout 'cus I don't know how to use any sketching or graphing programs xD
![IMG_20240401_174825](https://github.com/dessalines/thumb-key/assets/134894742/9b3eac36-8283-4e84-a454-188a49b25bb2)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Follow the instructions for creating and adding this in the readme.

**Comment by dessalines** [comment]
@Azurite0923 You don't need to code anything. The instructions clearly say that you can copy a sample keyboard file, edit the keys you want to change, paste it here. Only a simple text editor is required.

I'll re-open this if you decide to do it.
