### ISSUE TITLE
Cannot be built with current gradle

### ISSUE THREAD

**Issue by alerque** [dessalines/thumb-key#831]
### Steps to reproduce

Have a fresh system (e.g. Arch Linux) with Gradle 9.0

Run `gradle build`.

### Expected behavior

A build.

### Actual behavior

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

### version of the program

HEAD

### Android version

Not relevant, we're not able to build yet much less run.

### Device

Not relevant, we're not able to build yet much less run.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Thx, I'll get to this shortly.

**Comment by dessalines** [comment]
[Gradle 9.0 doesn't exist yet](https://gradle.org/releases/), and our CI is passing fine: https://woodpecker.join-lemmy.org/repos/138/pipeline/1291/5

Also, don't use your system gradle to build any android projects, use the gradle wrapper: `./gradlew buildDebug`

**Comment by alerque** [comment]
My apologies, it appears that messages is an advance warning of an upcoming deprecation. The actual error was somewhat before that in the build log but not clearly surfaced as an error and I misinterpreted the later warning as the error since it was nearly the last thing in the log.

**Comment by dessalines** [comment]
No probs!
