### ISSUE TITLE
Set the keyboard font

### ISSUE THREAD

**Issue by sphh** [dessalines/thumb-key#833]
### Describe your suggested feature

Comparing to the competitor, the layout of Thumb-key is not as readable as it could be:
![Screenshot_20240409](https://github.com/dessalines/thumb-key/assets/4856462/568eb0fa-4f98-44a8-b5f1-d942d5537e24)

I wonder if there is a way to set the keyboard font and I have missed it. If not, would it be feasible to add such a setting?

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
We're only going to use your system font.

**Comment by sphh** [comment]
What about adjusting the size and weight of the font – both for the primary and secondary letters/symbols? I guess, that would be enough to make the letters easier to read.

**Comment by dessalines** [comment]
There's already an issue for size customization.

**Comment by dessalines** [comment]
Actually I don't see one for size, I'll create one.

**Comment by sphh** [comment]
… and maybe also the font weight?

**Comment by dessalines** [comment]
Probably not, that should be a key-specific thing.

**Comment by sphh** [comment]
Ok, but why?

**Comment by dessalines** [comment]
I checked the code, and everything is already using FontWeight.Bold anyway.

**Comment by sphh** [comment]
Fair enough. But what is the reasoning behind it? I mean, some users might want to use non-bold letters/symbols on their keyboard, so a simple switch to turn `bold` on or off would be really great (as you can see on the example in my OP).

**Comment by dessalines** [comment]
Its work for a feature I don't think would be useful in adding the extra complication. PRs welcome if you want to do that work.
