### ISSUE TITLE
Cursor up and down on (english layout) using i-swipe-up and s-swipe-down

### ISSUE THREAD

**Issue by fietzero** [dessalines/thumb-key#834]
### Describe your suggested feature

As in MessagEase use the 'i' and 's' keys (the keys in the top and bottom row in the rightmost column) to move the cursor up and down.

These two key's swipe up or down functions are currently unused, and do not cause the same problems as when using the space bar's up/down swipe.

I could not find a possibility to configure this behavior in the settings of 2.7.3.

See also issue #480.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
The spacebar already works for this.
