### ISSUE TITLE
option to choose accent color

### ISSUE THREAD

**Issue by phanirithvij** [dessalines/thumb-key#84]
![Readme](https://camo.githubusercontent.com/189e00c443a9c31c6b9907f3f6f77b5cc568a660a4ecfac3c76ef51b1a201917/68747470733a2f2f692e706f7374696d672e63632f525a6a5a477a46472f53637265656e73686f742d323032332d30332d31362d30302d31342d32382d3033392d656469742d6170702d6f6c61756e6368657263662e6a7067)
 I prefer this theme from the readme, than the pink and the green. Is it possible to have a color pallete of sorts in the settings page in the look and feel page?
From what I gather https://github.com/dessalines/thumb-key/issues/34#issuecomment-147526133, is it possible to have an accent chooser? Without the hassle of copy pasting many things? 
Like say an example, microsoft launcher. Screenshots: [this](https://user-images.githubusercontent.com/29627898/227689387-4b27bbc8-b2f1-4830-9143-f01e2e21d433.jpg) and [this](https://user-images.githubusercontent.com/29627898/227689391-c55976e4-80f2-4f27-a4ec-82e26eae78ac.jpg). 
I'm on android 11

**Comment by dessalines** [comment]
No, because material 3 themes have many colors that each android app needs now. By default, thumb key uses the dynamic theme generated from your wallpaper.

If you'd like to add a theme tho, or have me generate one based off a specific color set, I'd be glad to do so tho. Here's the material 3 theme generator: 

https://m3.material.io/theme-builder#/dynamic

**Comment by phanirithvij** [comment]
I get the pink theme as the default no matter what wallpaper I set. It is set to dynamic (not pink), I'm not using a live wallpaper either. I have v0.0.6-alpha installed, and am on android 11.

**Comment by dessalines** [comment]
That sounds correct. I think the dynamic material stuff only works on android 12 or later. 
 https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/ui/theme/Theme.kt#L23
