### ISSUE TITLE
fixes to bugs/oversights in Eng-esp-cat keyboard layout

### ISSUE THREAD

**Issue by Norgus** [dessalines/thumb-key#841]
### Language

Engligh, Spanish, Catalan

### Variant

thumbkey

### Kind of request

Changes on an existing layout

### More details

Since trying the layout I submitted (https://github.com/dessalines/thumb-key/pull/826#issue-2222627477), I've realised I missed & mistook a couple of details.

I accidentally replaced 'z', so that's missing in the layout! 

I'd like to:
1. put 'z' back on the right side of the bottom-middle square
2. move 'í' to the left of that same square
3. add 'ï' to the top left corner of the same square (I forgot it entirely).
4. reinstate the down arrow for shifting from capitalised back to lower case. I must have removed it by accident.

I could attempt to fix them and make a new pull request if that's easiest (let me know).

I read the things but I'm still a clown  🤡

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Yes, please do a pull request for these fixes, thx.
