### ISSUE TITLE
hoỏk and underdọt in vietnamese composed layout

### ISSUE THREAD

**Issue by VoKi21** [dessalines/thumb-key#843]
### Language

Vietnamese

### Variant

composed thumb-key

### Kind of request

Changes on an existing layout

### More details

without these tonemarks the layout isnt fully functional. also among all other layouts, thats name is only capitalized. should be renamed into "vietnamese composed thumb-key"
for underdot, the dot symbol can be used.
for hook - question mark
also the more symbols the better of course, but æ and å have nothing to do with vietnamese. you can learn about vietnamese tonemarks from this [article](https://vietnamesetypography.com/tone-marks/) for example 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by VoKi21** [comment]
![Screenshot_20240412-125709_Thumb-Key](https://github.com/dessalines/thumb-key/assets/74360792/aa16b65b-fe09-4e2f-a9c9-21680a6a0980)
cant even write a language name

**Comment by dessalines** [comment]
> without these tonemarks the layout isnt fully functional. also among all other layouts, thats name is only capitalized. should be renamed into "vietnamese composed thumb-key"

No. All language name titles must be in their original script. Look at every other language name.

The person who created the vietnamese keyboard would have to make these changes.

**Comment by hiepoggy123** [comment]
> ### Language
> Vietnamese
> 
> ### Variant
> composed thumb-key
> 
> ### Kind of request
> Changes on an existing layout
> 
> ### More details
> without these tonemarks the layout isnt fully functional. also among all other layouts, thats name is only capitalized. should be renamed into "vietnamese composed thumb-key" for underdot, the dot symbol can be used. for hook - question mark also the more symbols the better of course, but æ and å have nothing to do with vietnamese. you can learn about vietnamese tonemarks from this [article](https://vietnamesetypography.com/tone-marks/) for example
> 
> ### Acknowledgements
> * [x]  I have written a short but informative title.
> * [x]  I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
> * [ ]  I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
> * [x]  I have filled out all of the requested information in this form.

Hello, I am a proponent of Vietnamese keyboard. Can you give me contact information? I'm not good at using github.

**Comment by dessalines** [comment]
Can re-open should you want to work on this, or find the creator of that layout.

**Comment by VoKi21** [comment]
finding the creator would be better: i have no experience with writing layouts for thumb-key and i dont speek/write vietnamese, just noticed a lack of certain vietnamese symbols
