### ISSUE TITLE
App (partially) not working on 2.6.9 or above.

### ISSUE THREAD

**Issue by masiv1001** [dessalines/thumb-key#847]
### Steps to reproduce

Step 1. Install any version above 2.6.9
Step 2. Try to access the settings page/the app itself

### Expected behavior

It should work regardless of device.

### Actual behavior

It can be set as a keyboard on the OS settings, but without working settings it cannot be configured.

### version of the program

2.6.9

### Android version

Android 12, MIUI 14.0.3

### Device

Xiamo Redmi Note 9S

### Other details

This issue might be caused by the dependency upgrade that took place in 2.6.9 (#628), rendering the app un-configurable on some devices (I have yet to proof this on other devices)
The upgraded dependencies of gradle are:
com.android.application (8.2.1 -- 8.2.2)
com.android.library  (same as above)
androidx.compose.material:material-icons-extended-desktop (1.6.0 release candidate 1 -- 1.6.0)
androidx.compose.ui:ui  (same as above)
androidx.compose.runtime:runtime-livedata (same as above)
androidx.compose.ui:ui-tooling (same as above)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by masiv1001** [comment]
I forgot to mention, but the app does indeed open, but a gray background is all there is; also, when trying to access the settings button on the keyboard itself, it does nothing.

**Comment by alerque** [comment]
I ran into something like this too but was using my own debug builds and chocked it up to not having done something right. The "solution" to get into the app settings was to go into the Android settings and make sure the keyboard is enabled and the security warning about input methods acknowledged. With that done manually opening up the app worked fine.

**Comment by dessalines** [comment]
I'll try to see what's going on with a fresh install.
