### ISSUE TITLE
vibration length option

### ISSUE THREAD

**Issue by Hate9** [dessalines/thumb-key#859]
### Describe your suggested feature

most keyboard apps have really short little vibrations on-tap, but for some reason thumbkey's are like 2-3x longer. an option to choose the vibration length would be *excellent*.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I'm not going to add the complication around this. Its only going to use your system vibration settings.

**Comment by Hate9** [comment]
ah, then perhaps this should be a bug report: the keyboard doesn't seem to be following my system touch settings. all other touch feedback (including other keyboards) is following my system touch settings. I'll make a bug report.
