### ISSUE TITLE
Auto-capitalize off problems

### ISSUE THREAD

**Issue by michalhasko** [dessalines/thumb-key#86]
Love the keyboard so far, but I don't use auto-capitalization, and I think there are two problems with the keyboard when auto-cap is turned off.

1. Keyboard starts in uppercase, and continues in uppercase (as if using cap lock). I think it should start in lowercase, just like other keyboards (e.g. gboard)

2. When using auto-cap, the slide-up on A acts as shift. When auto-cap is off, it acts as caps lock, making all letters uppercase. This should be consistent with auto-cap off. I think it would be nice if one slide-up on A acted as shift, and second slide-up as caps lock. A slide-down would bring it back to lowercase.

Note: I will try to fix this myself, although I am new to Kotlin and Android development. I'll let you know if I am not successful.

**Comment by dessalines** [comment]
The first one I could fix very easily, but the second would require a bit of work, adding another mode.

**Comment by michalhasko** [comment]
I think the first one is UtilsKt#getKeyboardMode, the second one is adding new KeyboardMode.CAPS_LOCKED and fixing onToggleShiftMode in KeyboardScreen.kt (and usages), plus showing the up arrow on A in SHIFTED mode, and perhaps some other parts that I haven't discovered yet.

Am I on the right track?

**Comment by dessalines** [comment]
Yes, and it would need the autocapitalization mode as a function to param to decide whether to start in shifted on main mode. 

The 2nd one, CAPS_LOCKED would not be on KeyBoardMode, but a new type enum type : `ShiftMode: { AUTO_SHIFT, CAPS_LOCKED }`

But ya you're on  the right track.

**Comment by michalhasko** [comment]
Here's a draft for #1 https://github.com/dessalines/thumb-key/pull/88
Any comment is appreciated.

**Comment by michalhasko** [comment]
I'm clearly out of my depth, so I closed the review. I'd be happy if you could fix it yourself. Thank you for all the help though.

**Comment by dessalines** [comment]
It's no probs, I should be able to get to this soon, and I'll ping you on the PR. Def join the dev chat on matrix tho, because this is a fairly simple and small project, that if you wanted to use it to learn jetpack compose, it would be good for that.

**Comment by michalhasko** [comment]
Thank you. I am currently too busy with life, but otherwise I'd join the chat. Maybe some time in the future.
