### ISSUE TITLE
keyboard does not follow system haptic settings

### ISSUE THREAD

**Issue by Hate9** [dessalines/thumb-key#862]
### Steps to reproduce

1. install app on my phone
2. adjust system touch feedback settings
3. use keyboard

### Expected behavior

the keyboard should follow system touch feedback settings, as all other apps and keyboards.

### Actual behavior

The keypresses' feedback is *significantly* longer than any other keyboard, as well as other apps and system feedback (like nav buttons and such).

### version of the program

3.1.0

### Android version

Android 11

### Device

Unihertz Jelly 2

### Other details

I recall this was also an issue on my Pixel 4a, iirc

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
[Here is the code](https://github.com/dessalines/thumb-key/blob/1abe5ce59dfb9cd52aea5a5c5575259067efbee6/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt#L170), I can try changing that.

**Comment by dessalines** [comment]
[This answer](https://stackoverflow.com/a/70285552/1655478) suggests one possible solution I'll try, because jetpack compose only has `LongFeedback` currently.

**Comment by Hate9** [comment]
ah, that makes sense. thanks!
