### ISSUE TITLE
Letter Öö (O-Umlaut) missing

### ISSUE THREAD

**Issue by cbiere** [dessalines/thumb-key#868]
### Language

German

### Variant

english deutsch thumb-key v2

### Kind of request

Changes on an existing layout

### More details

The letter is missing from the layout. The key exists but it results in the normal letter O or o. This is not the case with äÄ or Üü. So it seems to be a missing in the mapping.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You can fix this yourself by editing the keyboard in github, or making a PR. Watch a video on how to make a pull request on github if you can't figure this out.

**Comment by roomfullofcommits** [comment]
Looking at [the file](https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ENDEThumbKeyV2.kt) it looks like it should send the umlaut but it doesn't, for some reason.

The last commit where this file was edited was before this issue and it is still present in 3.2.4.

```
                KeyItemC(
                    center =
                        KeyC(
                            display = KeyDisplay.TextDisplay("o"),
                            action = KeyAction.CommitText("o"),
                            size = FontSizeVariant.LARGE,
                            color = ColorVariant.PRIMARY,
                        ),
                    swipeType = SwipeNWay.FOUR_WAY_DIAGONAL,
                    swipes =
                        mapOf(
                            SwipeDirection.BOTTOM_LEFT to
                                KeyC(
                                    display = KeyDisplay.TextDisplay("u"),
                                    action = KeyAction.CommitText("u"),
                                ),
                            SwipeDirection.TOP_LEFT to
                                KeyC(
                                    display = KeyDisplay.TextDisplay("ü"),
                                    action = KeyAction.CommitText("ü"),
                                ),
                            SwipeDirection.BOTTOM to
                                KeyC(
                                    display = KeyDisplay.TextDisplay("ö"),      <-- here
                                    action = KeyAction.CommitText("ö"),
                                ),
                        ),
                ),
```

**Comment by dessalines** [comment]
Remove that swipetype line in a pr.

**Comment by roomfullofcommits** [comment]
`swipeType = SwipeNWay.FOUR_WAY_DIAGONAL,`
This one? I assume it works kind of like a filter?
