### ISSUE TITLE
Typing first PIN number results in disappearing Thumb-key

### ISSUE THREAD

**Issue by tothpsk** [dessalines/thumb-key#872]
### Steps to reproduce

1. I am opening any app which has a PIN number lock
2. After typing the first number from PIN, Thumb-key disappeares
3. When clicking on the field with PIN numbers, the second and the rest numbers from PIN can be typed normally
4. This appears with any app I have on my android device (Nothing Phone 2, fully updated until 30th of April 2024). See the video for demonstration

https://github.com/dessalines/thumb-key/assets/11166910/4702f3f1-4414-4f53-83a1-c111f4a5e8fc

### Expected behavior

Numeric keypad shouldn't disappear when typing PIN numbers 

### Actual behavior

Numeric keypad disappears after typing the first number from PIN. The rest of the numbers can by typed normally 

### version of the program

3.1.1

### Android version

Android 14

### Device

Nothing phone 2

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by Lysalana** [comment]
I also have problems writing OTP passwords like what is happening to you. Thumb key disappears in every key press.

**Comment by dessalines** [comment]
Thumbkey is closing because the text area is finished.

Don't really know what to do with these ones. These apps aren't using standard text inputs, so thumbkey is properly seeing that you're finished with one. 

I don't have any app that uses these strange inputs, so you'd need to debug these apps.
