### ISSUE TITLE
Add colon to swipe n-right-down [deutsch thumb-key]

### ISSUE THREAD

**Issue by sphh** [dessalines/thumb-key#882]
### Language

German

### Variant

deutsch thumb-key

### Kind of request

Changes on an existing layout

### More details

The colon `:` in often used in the German texts, but hard to reach (switch to symbol keyboard). Would it be possible to add a swipe right-down to the `n` key (bottom row, left column)? This is the same place as in the symbol keyboard.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't maintain that keyboard, so you'll have to do this yourself. You can click edit on the keyboard you'd like to change, and change this. If you don't know how to do this, watch a video on how to make a pull request in github.

Try to keep the symbols on the same key tho.
