### ISSUE TITLE
Add quotation mark to swipe s-left-top [deutsch thumb-key]

### ISSUE THREAD

**Issue by sphh** [dessalines/thumb-key#883]
### Language

German

### Variant

deutsch thumb-key

### Kind of request

Changes on an existing layout

### More details

The quotation mark `"` is very often used, but hard to reach (switch to symbol keyboard). Would it be possible to add a swipe left-top to the `s` key (bottom row, middle column)? This is the same place as in the symbol keyboard.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't maintain that keyboard, so you'll have to do this yourself. You can click edit on the keyboard you'd like to change, and change this. If you don't know how to do this, watch a video on how to make a pull request in github.

Try to keep the symbols on the same key tho.

**Comment by sphh** [comment]
@dessalines: So who maintains that keyboard? According to the the [history](https://github.com/dessalines/thumb-key/pull/69) it is you.

**Comment by dessalines** [comment]
I added it on someone's behalf. I don't speak german. You'll have to make these changes yourself.

**Comment by sphh** [comment]
Well, a colon and a quotation mark is nothing special to German I would have thought …
