### ISSUE TITLE
"Y" is missing in german layout

### ISSUE THREAD

**Issue by reedts** [dessalines/thumb-key#90]
Just as title says, while trying out the german layout v2 I noticed that the "Y" key is missing.

**Comment by dessalines** [comment]
![Screenshot_2023-03-26-14-09-23-226-edit_com.dessalines.thumbkey.jpg](https://user-images.githubusercontent.com/930215/227795465-ac7ef498-cdb4-45c4-85fe-6edfc56c694e.jpg)

**Comment by dessalines** [comment]
I'm fairly sure it's in 0.0.6, but if not, it'al be in the next deploy.

**Comment by reedts** [comment]
Interesting, there might be another error involved. I have two "Z"s, on in the position where the "Y" is supposed to be. Im Running 0.0.6-alpha. 
![thumb_key_0_0_6_alpha](https://user-images.githubusercontent.com/5320412/227798224-0c0ff0ea-522e-49cb-adcd-c374c54b8eda.png)

**Comment by dessalines** [comment]
https://github.com/dessalines/thumb-key/commit/f51ca55f3a76a5111e411b665239a0e4abf4b7c9

It'll be in the next release.
