### ISSUE TITLE
Vibration on tap stopped to work after update

### ISSUE THREAD

**Issue by geck093** [dessalines/thumb-key#910]
### Steps to reproduce

I updated from the 3.0.0 to the last version 3.1.7 and the vibration stopped to work. I then downgraded one version at the time until 3.1.0 when the vibration returned to work

### Expected behavior

Vibration on tap

### Actual behavior

No vibration on tap

### version of the program

3.1.1 to 3.1.7

### Android version

Android 13

### Device

Samsung Galaxy A52

### Other details

I checked the program and system configuration to confirm nothing changed and tried other keybords, that worked fine.
The sound on tap worked fine on all version 3.1.0 to 3.1.7

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
We switched to a shorter tap vibrate length, but its still the exact same vibrate, and its working for mine. Are you sure you have touch feedback enabled in your system settings?

**Comment by geck093** [comment]
The touch feedback was enabled both in the app and in the system settings, even changing the vibration intensity has no effect. However, using the Samsung keyboard, the vibration works correctly. I am currently using version 3.1.0 which does not give me any problems.

**Comment by dessalines** [comment]
This is the only PR that changed anything to do with vibration since then: https://github.com/dessalines/thumb-key/pull/863 . I don't know what I can do about this, as it should've only changed the vibration length.

**Comment by geck093** [comment]
Is it possible that the vibration is too short for my phone to start the motor? In this case is it possible to add a parameter in the settings to change the vibration length?

**Comment by ondrachwiedziuk** [comment]
Vibrations have also stopped working on my device (Samsung Galaxy A22 5G) in the current version (3.2.1). I guess there might be a problem with Samsung devices, where the vibration length is shorter than Samsung's minimum length.

**Comment by KraXen72** [comment]
I am also experiencing vibrations not working on Thumb-key 3.2.6
Samsung Galaxy M21 Android 12 OneUI 4.2
Regardless of the vibration strength in settings, even if vibrate on touch feedback is enabled. DND is off, system sounds, ringtone, alarm and media are all at maybe 70%.
Vibrations are working on Gboard.

**Comment by dessalines** [comment]
You can look at #863 , I'm guessing its for samsung devices then, they won't start the motor with the `KEYBOARD_TAP` vibration length.

**Comment by KraXen72** [comment]
sorry, what am i supposed to do with the pr?
fyi, gboard allows customising vibration length in ms with a slider with a 1ms step, so i think adding vibration length customization wouldn't be out of place.

there could be some preset buttons that would move the slider, but otherwise you can adjust it freely.

this could solve the problem for samsung devices if they can simply increase the vibration duration.

**Comment by dessalines** [comment]
I don't think I'd want to add custom vibration length. [Here's the specific line that changed this](https://github.com/dessalines/thumb-key/pull/863/files#diff-3bc9336fe7ff0684da30ca8801f2dfb8e4ec42479e990cf6585d5df55cf6fdd7R170). The possible ways forward for this are:

- Open up an issue on why samsung isn't supporting the KEYBOARD_TAP_LENGTH above.
- Open up an issue for jetpack compose to support a short haptic feedback tap length, not just `LongPress`
- Create a PR to add a setting that switches which type of feedback we do, based on these two conflicting and incompatible ways to do haptic feedback.

**Comment by KraXen72** [comment]
i tested the foss futo keyboard that just came out, and it's a fork of AOSP latinIME, and it supports vibration (i set it to 30ms) could you possibly check if they are using some different method/api?

**Comment by dessalines** [comment]
You should've done this work as it's samsung weirdness workaround, but I did it for you.

https://github.com/futo-org/android-keyboard/blob/dd0ba32804411863e61d166d355c3ec953a61383/java/src/org/futo/inputmethod/latin/AudioAndHapticFeedbackManager.java#L121

They seem to be using the same thing we are, but also adding a most likely deprecated custom vibrate function in addition to the standard. 

Reach out to samsung support about this issue and link it here.
