### ISSUE TITLE
Drag-and-return gesture depends on where the gesture ends instead of where it begins

### ISSUE THREAD

**Issue by izomiac** [dessalines/thumb-key#926]
### Steps to reproduce

On the Messagease keyboard layout:
1) Tap and hold the "o" in the center
2) Swipe north-west over "q"
3) Swipe the opposite direction (south-east)
4) Stop on the "j"

### Expected behavior

A capital "Q" should be typed

### Actual behavior

A lowercase "j" is typed

### version of the program

3.1.9

### Android version

Android 13

### Device

Galaxy Tab S7+

### Other details

This may affect circle gestures as well, but those are more finicky so it's harder to verify.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I can't seem to replicate. All it has to do is return back to the key.

**Comment by izomiac** [comment]
Here is a screen recording of the behavior.

https://github.com/dessalines/thumb-key/assets/6551261/5c1b15d4-2935-43f9-b4ed-0abd1867fdb6

**Comment by dessalines** [comment]
It looks like instead of going back to the center of the key, you went to the edge. I agree that the logic could be tweaked to be more forgiving tho. 

cc @feathecutie @glm4610
