### ISSUE TITLE
writing problem while writing in japanese 

### ISSUE THREAD

**Issue by ashu-py** [dessalines/thumb-key#927]
### Steps to reproduce

1. try to kyo 
2. but we can only write kiyo 
3. きよう (kiyou)
きょう (kyou) 

### Expected behavior

the size of よ should be able to change between small and normal they are also othere key which also require this feature  つ や ゆ 

### Actual behavior

no change in size

### version of the program

latest 

### Android version

android 11

### Device

vivo y21

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You'll have to ping the creator of that keyboard, or do a PR to fix this issue yourself for the multiple japanese keyboards. I don't speak japanese so I can't help.

**Comment by K0baU** [comment]
@ashu-py
Dakuten key makes normal=>small.
I made PR to show "小" to make this clear.
