### ISSUE TITLE
[FRTypeSplit] spacebar should be switch with backspace

### ISSUE THREAD

**Issue by styfore** [dessalines/thumb-key#935]
### Language

French

### Variant

FRTypeSplit

### Kind of request

Changes on an existing layout

### More details

In the french split layout FRTypeSplit,  the backspace key is positioned at the bottom of the bar, which is particularly annoying because this kind of key (size and position) is normally a space bar, and the reflex is to press it to make a space (but here it deletes).

currently : 
![IMG_20240601_091811](https://github.com/dessalines/thumb-key/assets/7504006/c39e8068-0efa-4e14-bc70-ad96feb3203e), 

should be something like this : 
![image25](https://github.com/dessalines/thumb-key/assets/7504006/68573f96-e8a2-441c-b738-4c8508c53ee2)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
I don't maintain that keyboard, so could you make these changes? Thx.
