### ISSUE TITLE
add en-dash and em-dash to english layouts

### ISSUE THREAD

**Issue by pranabekka** [dessalines/thumb-key#943]
### Language

English

### Kind of request

Changes on an existing layout

### More details

currently, only hyphens are available, which are most appropriate for joint words or word breaks[1], but not date/number ranges or sentence interruptions/asides.

hyphen, en-dash, and em-dash: -, –, —

an en-dash is used to connect numbers or dates in a range: "between 5–10"

an em-dash is used when inserting a related sentence into another (like parentheses), or interrupting a sentence. for example: "here i am talking ab — oh, we can ..." (this is an interruption)

reference: https://www.merriam-webster.com/grammar/em-dash-en-dash-how-to-use

[1]: joint words are like "para-social" (though they usually loose the hyphen over time). word breaks are when a whole word doesn't fit on a line, and part of it must go on another line. this is usually handled by layouts.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
These wouldn't go on any language keyboard, but the symbols keyboard. But also I don't think we'll support them: there's an endless number of unicode variations of nearly every symbol, and we have limited space.
