### ISSUE TITLE
cant move to a new line on discord when the return key is pressed

### ISSUE THREAD

**Issue by noornee** [dessalines/thumb-key#950]
### Steps to reproduce

https://github.com/dessalines/thumb-key/assets/71889751/5d64fe41-1c53-478d-a019-7996a8717334

### Expected behavior

it should move to a new line.

### Actual behavior

check title

### version of the program

3.2.3

### Android version

Android 14

### Device

Redmi note 12 4g

### Other details

I experience a slightly similar behavior on whatsapp but instead of it not movin to a new line, i have to double press the return key 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You didn't search for this existing issue. Hold the enter key for a forced newline, that was added to support these broken apps.
