### ISSUE TITLE
A gesture for changing keyboard position

### ISSUE THREAD

**Issue by somehare** [dessalines/thumb-key#96]
While typing with two hands, it is probably better to use the keyboard centralized. However, when you type with one hand it is more ergonomic to locate the keyboard in right/left.

I think it would be convenient to have some gesture to quickly change the keyboard positioning to adapt on how you are typing at the moment, without having to open the settings menu.

Maybe swipe left/right on settings button for that?

**Comment by dessalines** [comment]
I'll add this shortly.

**Comment by KraXen72** [comment]
this is good, but imo i'd much rather see the emoji picker shortcut in this swipe's position when it comes. but maybe that's just me.
