### ISSUE TITLE
Diferent sounds for key differentiation

### ISSUE THREAD

**Issue by C0baltFlynt** [dessalines/thumb-key#963]
### Describe your suggested feature

Instead of having a single sound for all keys, each key (regardless of swipe/tap/etc) could have a slightly different sound ([think about your contacts app, each one of the keys in the t9 layout makes the same sound but shifts the pitch](https://youtu.be/JCGqMvWmWUI)).

This could make it easier to make sure you are hitting the correct keys without looking. Also the special keys (delete/space/switch keyboards etc) could have another sound + pitch variation (because they can mess up your typing more easily)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
This isn't a feature I'm going to work on, as it'd be extremely cumbersome to set these different sounds for every key, and probably annoying for anyone using it. If you'd like to tho, I can re-open and assign it to you.
