### ISSUE TITLE
Swipe-return on captitalization key should capitalize the current word

### ISSUE THREAD

**Issue by gitterrost4** [dessalines/thumb-key#964]
### Describe your suggested feature

Similar to MessagEase, doing a slide-return gesture on the capitalization key (swipe up on the key left to the "#" key) should capitalize the first letter of the word under the cursor. If the first letter is already capitalized, it should capitalize every letter in the word under the cursor. Swipe-returning down on that key should do the reverse.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Fixed by above PR. In the future put `Fixes #ISSUE_NUM` in your commit message, and merging it will automatically close the issue.
