### ISSUE TITLE
Option to set the language in layouts with multiple languages

### ISSUE THREAD

**Issue by zgll2022** [dessalines/thumb-key#969]
### Describe your suggested feature

Hello,

I know there is an option to switch between different languages by switching between different layouts, but there are many layouts that have more than one language.

I think the Android spell check only detects the first one in these cases, it would be great if there was an option to be able to switch between different languages within the same layout.

Thank you very much for your time.
Best regards.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
We don't have the keyboards tagged to specific languages (many of them are multi-lingual), but more importantly, people might not want to have *all* layouts for their language selected. The way it works currently is best, where you explicitly choose which layouts you want in your quick switcher.
