### ISSUE TITLE
Some keyswipes don't work in EN writer layout

### ISSUE THREAD

**Issue by locrianz** [dessalines/thumb-key#972]
### Steps to reproduce

I don't know if this is something I did wrong when I made the layout or not, but some of the key swipe directions on T just don't do anything -- I can't type the n-dash, m-dash, or single open quote.

I'm attaching a video; it starts with me swiping all the letters off the center key to show that I can, in fact, swipe in the correct directions.

https://github.com/dessalines/thumb-key/assets/152659636/d08fe14e-857d-485a-bcbd-1ae697156da3

### Expected behavior

Swiping should type the expected symbol.

### Actual behavior

Instead, a different symbol is typed, one of the ones adjacent to the expected symbol. (For example, open double quote instead of open single quote.)

### version of the program

3.3.1

### Android version

Android 14

### Device

Nokia XR-21

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Its because you have the incorrect `swipeType` on those keys. You should either remove those lines (so it uses the default), or use the correct specific one.
