### ISSUE TITLE
Add copy, paste, select all buttons

### ISSUE THREAD

**Issue by kartikynwa** [dessalines/thumb-key#98]
[Originally suggested here:](https://lemmy.ml/comment/407209)

> Do you think it’s possible to add something like a copy paste select all buttons on the free space of the keyboard? I was using FlorisBoard and one of the coolest features is that, specially since there are applications on Android that won’t let you hold to paste on some fields.

**Comment by LongJohn-Silver** [comment]
This is how Florisboard does it. Select all, Copy, Cut, Move left button, Move right button (these two can be dropped in favour of movement through the space bar, though), Paste, Delete clipboard history and Access clipboard history. There's also a second menu that has a couple more buttons, but the only ones I've used from that are two that basically work as a ctrl+z and ctrl+y which could be a very nice addition.

What about something like this:

Settings button: Left (ctrl+z), left upper corner (emoji selection), right upper corner (language switcher), right (ctrl+y), right bottom corner (access clipboard history) and left bottom corner (deleting clipboard history).

Number button: Left (select all), up (copy), right (cut), bottom (paste).
