### ISSUE TITLE
English message ease with symbols

### ISSUE THREAD

**Issue by ShacharHarshuv** [dessalines/thumb-key#980]
### Language

English

### Variant

MessageEase with symbols

### Kind of request

New Layout

### More details

I could find:
- English composed messageease in which symbols don't work as expected (it just merges it with the previous letter if it exists)
- English messageease (with no symbols). 

I'm actually not sure this is the right approach. I will not need this keyboard if the "Ghost Keys" behavior would support actually displaying those keys. 
Additionally, it's weird that you need a separate keyboard to create "composed" characters like à. Maybe there is a better UX solution for these? I think messageease had some sort of "combine" command. 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Instructions are on the readme for creating and submitting your own layout. 

We aren't going to show the "ghost keys", as that's the point of them being hidden.

**Comment by ShacharHarshuv** [comment]
> We aren't going to show the "ghost keys", as its intentional to keep them hidden.

Can you explain the rational? I feel like this could make sense, at least as an option

**Comment by dessalines** [comment]
Because that's just a 1-layer layout. You can create a 1 layer layout, IE a layout without a shifted mode if you want.

**Comment by ShacharHarshuv** [comment]
If you have one common layer for symbols and numbers, and many layers for different languages with letters, you can more easily support both the languages without symbols, and the language with symbols, and many other languages, all with the same symbols configuration. I can see a world in which someone might want to configure the symbols and layer and language layer separately. Aka - you will not need a separate keyboard for "with / without symbols", which will cut the available keyboards in half. I also think that wanted to see symbols with the letter is probably a preference that will exist in all languages that a user is using. (i.e. if I use Hebrew and English I probably want to see it in both)
So I can see a value in that feature despite a "work around" (which is creating a new keyboard) exist.
