### ISSUE TITLE
Arabic

### ISSUE THREAD

**Issue by ShacharHarshuv** [dessalines/thumb-key#981]
### Language

Arabic

### Variant

MessageEase

### Kind of request

New Layout

### More details

Kind of surprising there isn't one already right? 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Instructions are on the readme for creating layouts. I believe there's a farsi layout that could serve as a starting template for arabic.
