### ISSUE TITLE
Backspace is not firing "keyup" event in browsers when pressed

### ISSUE THREAD

**Issue by GlassGruber** [dessalines/thumb-key#986]
### Steps to reproduce

You can check here 
https://codepen.io/Gruber/pen/YzoWPGX

I've setup a simple demo, try type something in the textarea and delete, in the console you will see both keyup and keydown events logged, but not keyup when pressing backspace.

This issue caused a bit of a headache because a script depending on that event was working on a different device but not on mine, luckily I noticed the different keyboards and tested with default android and it worked on my device too.

### Expected behavior

When pressing backspace a keyup should be fired inside browsers

### Actual behavior

When pressing backspace only keydown event is triggered inside browsers

### version of the program

3.3.3

### Android version

Android 10 

### Device

Samsung

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
This probably has to do with the drag actions done on the backspace key. Might be difficult to figure this one out.

**Comment by GlassGruber** [comment]
> This probably has to do with the drag actions done on the backspace key. Might be difficult to figure this one out.

I see, the spacebar do fire both event keydown and keyup.

**Comment by dessalines** [comment]
Likely fixed by the above PR.
