### ISSUE TITLE
Add Hàn input support

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#99]
To input Hàn writing system in Chinese, Japanese, Korean and Vietnamese, something else are needed, like script conversion, candidate menu, dictionaries.
Dictionaries can be taken from Linux IME repositories.

**Comment by dessalines** [comment]
I'm not sure how all this would work, but if someone wants to try to implement it, go right ahead.

**Comment by GrimPixel** [comment]
There are some open-source Chinese input methods already there:

[ChangjieIME](https://github.com/wanleung/ChangjieIME)
[Stroke Input Method](https://github.com/stroke-input/stroke-input-android)
