### ISSUE TITLE
new simplified Slovak layout

### ISSUE THREAD

**Issue by Jastcher** [dessalines/thumb-key#993]
### Language

English

### Variant

simplified

### Kind of request

New Layout

### More details

First of all, I wanted to add this layout myself as I don't want to bother you, but I can't find the app data folder anywhere. The folder `com.dessalines.thumbkey` does not exist on my phone for some reason. If you could tell me how to add a new layout, I will do it myself.

The layout I want is a simplified "Slovenčina Thumb-Key v2," where the order of keys remains the same, but all letters not in the English layout are removed. So, there would not be "č, ú, é, ó, ô, á, ä, í, ľ, ĺ, ŕ, ý, š, ň..." letters, and all the other letters would be reordered to the center, just like in the default English layout.

Help with locating the app folder would be greatly appreciated.

Thanks in advance.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You can check any of the other PR's adding languages here: https://github.com/dessalines/thumb-key/pull/991

But its probably better to just follow the instructions on the readme: https://github.com/dessalines/thumb-key?tab=readme-ov-file#how-do-i-add-my-language-or-layout

**Comment by dessalines** [comment]
Closing, as I don't keep new keyboard requests open, but feel free to make a PR or follow those instructions above.
