### ISSUE TITLE
Long press to enter numbers

### ISSUE THREAD

**Issue by Torpedro1978** [dessalines/thumb-key#994]
### Describe your suggested feature

it would be really nice to be able to long press on the main keys in messagase layout to enter numbers,  just like in messagease

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Use the circle swipe feature.

**Comment by Torpedro1978** [comment]
The circle feature is almost never working in this verson, on no of my devices.
BTW: this is a strange way to handle a reasonable, valuable feature request

**Comment by Toldry** [comment]
@Torpedro1978 FYI with the new key modification feature, you can customize this your keyboard to do this.

https://github.com/dessalines/thumb-key?tab=readme-ov-file#example-4
