### ISSUE TITLE
The emoji key is incomprehensible

### ISSUE THREAD

**Issue by raveren** [dessalines/thumb-key#997]
### Language

Default layout

### Kind of request

Changes on an existing layout

### More details

I am trying to adopt this fantastic keyboard, but comming from Messagease I just can't do it due to the emoji key - the biggest issue with it is: I pushed the keyboard right and I can't push it back left :( the hand was also a nice button to hide the keyboard, scale and move it, but I can adjust my habits, the total usability killer for me is I have to reset the keyboard settings if I swipe right on the emoji button...

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Swipe right again, it'll move it back.

**Comment by raveren** [comment]
I tried it instinctively of course, and I couldn't swipe right, it's at the rightmost position, no swipes get registered...

But now that you said it explicitly I can do it if I'm really doing it very carefully and intentionally.

I still think this is confusing usability (for me it was usability killer, but I saw so many updates being pushed, I gave it another try to see if it was "fixed")

At least the icon on the right swipe should be something like ⇄ with a tooltip if you swipe it to the leftmost of the screen :)

**Comment by raveren** [comment]
...and I resized the keyboard to my liking - i.e. smaller and it's now totally stuck to the right border, no amount of intention and carefulness allow me to swipe right from there.

**Comment by dessalines** [comment]
That's a separate issue having to do with registering swipes outside the border. Go into your settings manually to change it back to where you want it.

**Comment by raveren** [comment]
I would consider this a usability issue, not a technical one. The long press is unbound on the emoji key, it could be bound to the "switch layout" and the left swipe that currently switches layout could move the keyboard back left, it would just be self-explanatory...

Or:

Swipe left and right: move keyboard
Long press: system keyboard switch (least used option so does not need an icon in the ui even)
Swipe down: switch layout

I'm sorry if my words seem opinionated, I am very grateful for your work, it's amazing, you're amazing!! 🤗

**Comment by dessalines** [comment]
We don't use long-press at all on any key currently. 

I'd rather not spend two separate swipes for position adjustment alone.
